### ISSUE TITLE
Reverse proxy for non-swarm containers

### ISSUE THREAD

**Issue by ibnesayeed** [lucaslorentz/caddy-docker-proxy#11]
While the Swarm mode is the way to deploy services and it might become the default at some point, many people are still deploying individual containers directly. Theoretically, the plugin should work in those situations as well, but we need to test and document it.

**Comment by pwFoo** [comment]
Would be nice to use with native docker or rancher (2.x is Kubernetes based) too. :)

**Comment by lucaslorentz** [comment]
@pwFoo For Rancher + Kubernetes I suggest looking at https://github.com/wehco/caddy-ingress-controller
