### ISSUE TITLE
Add domain to log

### ISSUE THREAD

**Issue by ahoeg** [lucaslorentz/caddy-docker-proxy#110]
How to add the domain to the caddy / proxy log? Would be nice for filtering / debugging single domains running with caddy proxy in front...

**Comment by abdusco** [comment]
You can change log format and interpolate {host} if you want:

https://caddyserver.com/docs/placeholders
https://caddyserver.com/docs/log

Default format:
```
{remote} - {user} [{when}] \"{method} {uri} {proto}\" {status} {size}
```

With host:
```
[{host}] {remote} - {user} [{when}] \"{method} {uri} {proto}\" {status} {size}
```

**Comment by ahoeg** [comment]
@abdusco 
Thanks, but how configure the caddy-docker-proxy instance to log the host? I don't want to configure each backend to log host at proxy side. Would be nice to have it global enabled for caddy proxy.

**Comment by ahoeg** [comment]
Works configured at backend. Closed
