### ISSUE TITLE
[Feature Request] Plugin option to show current caddyfile with info about parse errors

### ISSUE THREAD

**Issue by ahoeg** [lucaslorentz/caddy-docker-proxy#111]
Would be nice to have an option to output the current caddyfile with health check (OK or parse errors with associated config line for debugging)?

**Comment by lucaslorentz** [comment]
Currently, that information is already available in caddy logs. Which you can configure to go to stdout or to a specific file.

Or do you mean an URL where you can request and see that information?

**Comment by francislavoie** [comment]
With Caddy v2, you can use the config API to get the current running JSON config (or look at the `/config` storage location which will have an `autosave.json` file). Should be good enough here. Parse errors should appear in the logs as usual.
