### ISSUE TITLE
Problems with nextcloud talk

### ISSUE THREAD

**Issue by pwFoo** [lucaslorentz/caddy-docker-proxy#114]
Hi,

I try to use nextcloud talk android app behind caddy-docker-proxy, but have login / access problems.

```
error
access forbidden
invalid request
```

Maybe header related found some configs here 
https://github.com/caddyserver/examples/blob/master/nextcloud/caddy-reverseproxy-nginx-backend-nextcloud/Caddyfile

But how to set multiple header group with caddy-docker-proxy?
```
		header / {
			Strict-Transport-Security "max-age=31536000; includeSubdomains; preload"
			X-XSS-Protection "1; mode=block;"
			X-Content-Type-Options "nosniff"
			X-Frame-Options "SAMEORIGIN"
		}
```

Maybe that (or cors?!) could be a problem... Anyone have a working nextcloud / nextcloud talk config?

**Comment by pwFoo** [comment]
I think with the original nextcloud-apache image shouldn't be a backend problem and solved by reverse proxy settings. But I don't know hot to set sections / groups like limits / header.
Example config found.
```
example.com, www.example.com	{
		gzip {
			ext		*
			level	4
		}
		proxy / localhost:81 {
			transparent
			websocket
		}
		header / {
			Strict-Transport-Security "max-age=31536000; includeSubdomains; preload"
			X-XSS-Protection "1; mode=block;"
			X-Content-Type-Options "nosniff"
			X-Frame-Options "SAMEORIGIN"
		}
		limits {
			header	64kb
			body	8gb
		}
		ext	.html	.htm	.php
		root /var/www/html
		log / /var/logs/caddy/access.log {
			rotate_size		10
			rotate_age		14
			rotate_keep		10
			rotate_compress
		}
		errors /var/logs/caddy/error.log
		timeouts {
			read	5s
			header	5s
			write	0
			idle	20s
		}
}
```
https://github.com/caddyserver/examples/blob/master/nextcloud/caddy-reverseproxy-nginx-backend-nextcloud/Caddyfile

**Comment by lucaslorentz** [comment]
Limits labels:
```
caddy.limits.header=64kb
caddy.limits.body=8gb
```

**Comment by lucaslorentz** [comment]
Header labels option 1:
```
caddy.header=/
caddy.header._0=Strict-Transport-Security "max-age=31536000; includeSubdomains; preload"
caddy.header._1=X-XSS-Protection "1; mode=block;"
...
```

Header labels option 2:
```
caddy.header=/
caddy.header.Strict-Transport-Security="max-age=31536000; includeSubdomains; preload"
caddy.header.X-XSS-Protection="1; mode=block;"
...
```

**Comment by pwFoo** [comment]
Hi,
second post answers my question. Thanks! I'll test it! 👍

**Comment by pwFoo** [comment]
Tested option 2. Works with a small modification.
```
      caddy.header: /
      caddy.header.Strict-Transport-Security: '"max-age=31536000;"'
      caddy.header.X-XSS-Protection: '"1; mode=block;"'
      caddy.header.X-Content-Type-Options: "nosniff"
      caddy.header.X-Frame-Options: "SAMEORIGIN"
```
Value with special chars like ";" need double quotation marks to avoid syntax error in caddyfile.

Works now! Thanks!

**Comment by lucaslorentz** [comment]
Seems to be solved, please reopen if necessary.

**Comment by tmo1** [comment]
> ` caddy.header: /`

In case anyone comes across this as I did, note that [for Caddy v2, the quoted line needs to be modified as follows](https://caddy.community/t/security-headers-not-working-with-reverse-proxy/7580):

`caddy.header: /*`
