### ISSUE TITLE
Proxy /.well-known/<PATH>?

### ISSUE THREAD

**Issue by pwFoo** [lucaslorentz/caddy-docker-proxy#116]
Hi,

it looks like nextcloud and specially nextcloud social plugin needs access to `/.well-known/<DIR>`. Is it possible to proxy that to a backend container?
```
/.well-known/webfinger
/.well-known/carddav
/.well-known/caldav
```

Tried to add something like `<DOMAIN>/.well-known/webfingert`, but can't check if a request received (caddy proxy logs?) and backend not receive the special path.

**Comment by lucaslorentz** [comment]
I don't think you need anything special, proxy <domain> to your container and requests to /.well-known should be forwarded as well.

**Comment by pwFoo** [comment]
Ok, so it's not redirected because of let's encrypt certificate management / verification?
I don't know how it's done.
