### ISSUE TITLE
can't install docker.

### ISSUE THREAD

**Issue by tobyzhen117** [lucaslorentz/caddy-docker-proxy#125]
it shows 500 error when i tried to get caddy with docker, currently running ubuntu 19.04.

root@storage1: curl https://getcaddy.com | bash -s personal docker
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7380  100  7380    0     0   122k      0 --:--:-- --:--:-- --:--:--  124k
Downloading Caddy for linux/amd64 (personal license)...
curl: (22) The requested URL returned error: 500
Aborted, error 22 in command: curl -fsSL "$caddy_url" -u "$CADDY_ACCOUNT_ID:$CADDY_API_KEY" -o "$dl"
root@storage1:~#

**Comment by wsw70** [comment]
What were you trying to do? The image in this repo is intended to be ran on docker (`docker run ...` or `docker-compose`)

**Comment by lucaslorentz** [comment]
Problems seem to be fixed now.
I ran the same command to get caddy with docker plugin without problems,

**Comment by lucaslorentz** [comment]
But when using this plugin with caddy, caddy must be running inside docker.
