### ISSUE TITLE
Change default ports and run as non-root

### ISSUE THREAD

**Issue by anLizard** [lucaslorentz/caddy-docker-proxy#136]
I'd like to run the container as a non-root user and expose ports 8080 and 4443 for security reasons.
I would then map them to 80:8080 and 443:4443 on the host through docker-compose while running the container as non-root.

Is there any way to do this right now?

**Comment by lucaslorentz** [comment]
I think you can do that via command-line options. When you start caddy container.
https://caddyserver.com/v1/docs/cli
-http-port
-https-port

Add it to this line: https://github.com/lucaslorentz/caddy-docker-proxy/blob/master/examples/service-proxy.yaml#L16

**Comment by anLizard** [comment]
After adding user: 1000:1000 to the config and chowing existing files from the container, this worked flawlessly, thanks!
