### ISSUE TITLE
Migrate Logs to use zap

### ISSUE THREAD

**Issue by lucaslorentz** [lucaslorentz/caddy-docker-proxy#139]
In v2 you can use `zap` for logging. Here's a note from the docs: https://caddyserver.com/docs/extending-caddy#logs

_Originally posted by @francislavoie in https://github.com/lucaslorentz/caddy-docker-proxy/pull/137_

**Comment by SvenDowideit** [comment]
@lucaslorentz https://github.com/lucaslorentz/caddy-docker-proxy/pull/190/commits/17eedfbe1180e7d21eade15c18462704fefa11a1

Its not complete, as caddy-docker-proxy isn't a Module, and doesn't get started so the Provider interface is used - but that commit should make it much faster to convert

**Comment by SvenDowideit** [comment]
but - it does make the caddyfile and json printout horrible - as it escapes all the tabs, newlines, and quotes :(

**Comment by SvenDowideit** [comment]
ok, by using caddy.Log(), and not caching the logger (as per the notes in the docs), what we log changes when the user sets `debug true` while caddy is running - see https://github.com/lucaslorentz/caddy-docker-proxy/pull/190/commits/433d8258e31fee7cd7953eb7a07ca32870b6f971

**Comment by lucaslorentz** [comment]
Done, it will be included in next release.
