### ISSUE TITLE
Switch build to use xcaddy

### ISSUE THREAD

**Issue by lucaslorentz** [lucaslorentz/caddy-docker-proxy#141]
I think you could point people to use https://github.com/caddyserver/xcaddy instead. There's some docs on the site for it:

https://caddyserver.com/docs/build#xcaddy

Could do the building that way in your Docker image possibly as well (multi-stage, first stage is Go plus xcaddy, then 2nd stage you just copy the binary)

_Originally posted by @francislavoie in https://github.com/_render_node/MDE3OlB1bGxSZXF1ZXN0UmV2aWV3NDEzMTYwMDk4/pull_request_reviews/more_threads_

**Comment by mholt** [comment]
Feel free to ping me if you run into any issues with xcaddy.

**Comment by lucaslorentz** [comment]
```
xcaddy build --with github.com/lucaslorentz/caddy-docker-proxy/plugin/v2
```
Works well!

While changing build to use xcaddy we can probably go back to a single package, removing main.
https://github.com/lucaslorentz/caddy-docker-proxy/blob/master/go.mod
https://github.com/lucaslorentz/caddy-docker-proxy/blob/master/go.mod

**Comment by lucaslorentz** [comment]
@mholt @francislavoie  
I just started working on this and faced a minor issue.
I would like to use XCaddy to cross-compile for ARM while being on AMD64. Or compile for windows while being on Linux.
There is a check after compilation that I need to disable because the output is not executable in the build architecture/OS.
https://github.com/caddyserver/xcaddy/blob/master/cmd/xcaddy/main.go#L131
I will open an issue on XCaddy for now.

**Comment by mholt** [comment]
@lucaslorentz Should be fixed now.
