### ISSUE TITLE
Merge global options from Caddyfile and Docker labels?

### ISSUE THREAD

**Issue by mdbraber** [lucaslorentz/caddy-docker-proxy#145]
When I have a block defined in a separate Caddyfile and global options via Docker the complete contents of the Caddyfile always get written first in the output and therefore the global variables end up after a block, thus generating an error. 

Would it be posssible to parse the Caddyfile, get all the global variables and then merge them and  write them together with the global variables from the Docker config (we'll have to think which takes precedence, I'd think it would be the variables set in the Docker labels?)

**Comment by mdbraber** [comment]
I've taken a quick look at the code - would it be possible rather than read (and then write) the bytes of the Caddyfile, parse the contents and merge it? There are some functions in this code and the caddyfile code, but it seems ServerBlocks != Blocks. Any ideas on possible solution pathways? I would be willing to help out with a PR if we can agree on a path for solving this.

**Comment by lucaslorentz** [comment]
We need to implement, ServerBlocks is just a high level parser it doesn't represent all tokens and structure inside server blocks.

That's why I created Block and Directive models.

I've implemented that yesterday, I will push into a PR and you can test and take a look.

**Comment by lucaslorentz** [comment]
@mdbraber
It is in this branch: https://github.com/lucaslorentz/caddy-docker-proxy/tree/parse-caddyfile-and-configs.

[v] - Implement ServerBlocks parser
[v] - Parse default Caddyfile and merge in final Caddyfile
[v] - Parase Caddyfile from Docker Configs and merge it in final Caddyfile
[ ] - Tests and reviews and so on

By doing the parsing as you suggested, and levering the merge mechanism. If you define in your Caddyfile:
```
localhost {
  reverse_proxy /a target-a
}
```
And in your services labels something like this:
```
caddy = localhost
caddy.reverse_proxy = /b target-b
```

The final result will be a merge of that:
```
localhost {
  reverse_proxy /a target-a
  reverse_proxy /b target-b
}
```
Which I think is ideal. What do you think?

Feel free to continue working on that if you're available.

**Comment by mdbraber** [comment]
That sounds exactly what I was looking for @lucaslorentz - I'll give it  a shot!
