### ISSUE TITLE
Load balancing directly to Docker task IPs (bypassing Docker Swarm's LB)

### ISSUE THREAD

**Issue by banjerluke** [lucaslorentz/caddy-docker-proxy#146]
I have a Docker Swarm service with multiple containers/tasks, and I want to use Caddy to load balance traffic to them. I don't want to use Docker Swarm's load balancing since they only support round-robin and I need session affinity.

I see two conflicting sentences about this in the README:

Line 198:
> For services, that would be the service DNS name when **proxy-service-tasks** is **false**, or _all running tasks IPs_ when **proxy-service-tasks** is **true**.

Line 300:
> Currently multiple containers/replicas are not supported under the same website.

Is this a mistake, or am I missing something?

**Comment by lucaslorentz** [comment]
The second sentence is old. I will remove it from readme.

You can enable **proxy-service-tasks**, so it will load balance to all service tasks.

And you can even have multiple services with same website. Each service with several replicas.

**Comment by lucaslorentz** [comment]
Done. Please, let us know if you need any further information or examples.
