### ISSUE TITLE
Snippets created in Caddyfile aren't accessible in Docker Labels

### ISSUE THREAD

**Issue by SureDroid** [lucaslorentz/caddy-docker-proxy#159]
Whenever you create a snippet in a caddyfile and try to import it with a docker label, the application segfaults and exits.
I'm not sure if this is intended or unintended behavior. 

## Reproduce:
- Caddyfile has a snippet, and container is set with CADDY_DOCKER_CADDYFILE_PATH.
- You use the snippet in another docker-compose label `caddy.import: "<snippet>"`.

On startup, the program throws a invalid memory address error and a segfault. 

## Workaround:
- Caddyfile doesn't have snippet, instead you write the snippet in a docker-compose caddy label.
- You use the Snippet in another docker-compose label.

Snippet gets properly imported on startup.

## Stacktrace:
```caddy    | panic: runtime error: invalid memory address or nil pointer dereference
caddy    | [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x13289f6]
caddy    | 
caddy    | goroutine 62 [running]:
caddy    | github.com/lucaslorentz/caddy-docker-proxy/plugin/v2/caddyfile.Process(0xc000423880, 0x342, 0x342, 0x657, 0x342, 0x0, 0x0, 0x0, 0x0)
caddy    |      github.com/lucaslorentz/caddy-docker-proxy/plugin/v2@v2.0.0-20200616192750-9ce6e7859b70/caddyfile/processor.go:21 +0xa6
caddy    | github.com/lucaslorentz/caddy-docker-proxy/plugin/v2/generator.(*CaddyfileGenerator).GenerateCaddyfile(0xc000181e00, 0x6fc23ac00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
caddy    |      github.com/lucaslorentz/caddy-docker-proxy/plugin/v2@v2.0.0-20200616192750-9ce6e7859b70/generator/generator.go:192 +0xa40
caddy    | github.com/lucaslorentz/caddy-docker-proxy/plugin/v2.(*DockerLoader).update(0xc0002d7680, 0x0)
caddy    |      github.com/lucaslorentz/caddy-docker-proxy/plugin/v2@v2.0.0-20200616192750-9ce6e7859b70/loader.go:134 +0x6c
caddy    | github.com/lucaslorentz/caddy-docker-proxy/plugin/v2.(*DockerLoader).Start.func1()
caddy    |      github.com/lucaslorentz/caddy-docker-proxy/plugin/v2@v2.0.0-20200616192750-9ce6e7859b70/loader.go:81 +0x2a
caddy    | created by time.goFunc
caddy    |      time/sleep.go:168 +0x44
```

**Comment by lucaslorentz** [comment]
@SureDroid 
This has been fixed.
Could you please test again using CI images?
lucaslorentz/caddy-docker-proxy:ci-alpine
lucaslorentz/caddy-docker-proxy:ci

I will make a new release soon including this fix.

**Comment by SureDroid** [comment]
Tested and working, thank you!
