### ISSUE TITLE
Default virtual host

### ISSUE THREAD

**Issue by rakshazi** [lucaslorentz/caddy-docker-proxy#161]
Hello,
I'm trying to setup caddy docker proxy as on-vm reverse proxy that will handle connections by domain name (woami.site.com -> whoami container, www.site.com -> web container, etc) and I have a problem with external load balancer. It can perform healthchecks only on ip:port, without any host header set.

Could you explain me, how to tell caddy to redirect request to specific container if host not set (or not found).

Thank you!

**Comment by francislavoie** [comment]
You can have site labels like `http://` or `:8080` https://caddyserver.com/docs/caddyfile/concepts#addresses

**Comment by rakshazi** [comment]
@francislavoie thank you, but i can't understand how to solve main problem - caddy should return specific container if no host provided (eg, curl `http://10.0.14.5`) AND that container must be accessible by normal domain address (whoami.site.com)

**Comment by francislavoie** [comment]
You can have more than one site label space separated for a single container.

**Comment by lucaslorentz** [comment]
@rakshazi 
It's a bit like this:
```
      labels:
        caddy: whoami0.example.com http://
        caddy.reverse_proxy: "{{upstreams 8000}}"
```
That way, you're configuring your container to receive requests to:
http://whoami0.example.com
https://whoami0.example.com
http://*

Usually health checks goes with http only, because you don't have the dns name to issue certificates.

**Comment by francislavoie** [comment]
Thanks for elaborating @lucaslorentz I'm just on my phone for the time being 😁

**Comment by lucaslorentz** [comment]
Addresses' values must be whitespace-separated.
The Caddy documentation @francislavoie pointed to explains all possible values you can use for addresses.

This is a fully working example, using docker CLI:
```
docker run --name caddy -d -p 80:80 -p 443:443 -v /var/run/docker.sock:/var/run/docker.sock lucaslorentz/caddy-docker-proxy:ci-alpine

docker run --name whoami0 -d -l "caddy=http:// whoami0.example.com" -l "caddy.reverse_proxy={{upstreams 8000}}" -l caddy.tls=internal jwilder/whoami

docker run --name whoami1 -d -l caddy=whoami1.example.com -l "caddy.reverse_proxy={{upstreams 8000}}" -l caddy.tls=internal jwilder/whoami

curl -k http://127.0.0.1
curl -k --resolve whoami0.example.com:443:127.0.0.1 https://whoami0.example.com
curl -k --resolve whoami1.example.com:443:127.0.0.1 https://whoami1.example.com

docker rm -f caddy whoami0 whoami1
```

2 containers are created under different addresses. But whoami0 also responds to IP only requests.

**Comment by lucaslorentz** [comment]
Another option is instead of pointing to a specific container.
Do a caddy only health check endpoint.
You can do that by adding an extra Caddyfile using [Docker configs](https://github.com/lucaslorentz/caddy-docker-proxy#docker-configs) or CADDY_DOCKER_CADDYFILE_PATH:
```
http://* https://* {
  respond /yourhealthpath 200
  tls internal
}
```
Or:
```
http://* {
  respond /yourhealthpath 200
}
```

**Comment by rakshazi** [comment]
Ideas above are some kind of catch-alls, which will catch literally all. Solution - set list of all allowed connections:
```yml
  health:
    image: project/health
    restart: unless-stopped
    labels:
      caddy: http://health.project.com http://localhost http://124.125.12.15 http://10.1.0.4
      caddy.reverse_proxy: "{{upstreams 8080}}"
```

In that case when you send a request from load balancer (by ip), from server itself (localhost) or from web (domain) it will go to that container and it will not affect other containers.
