### ISSUE TITLE
GetCaddy v1 fails when selecting `docker` plugin

### ISSUE THREAD

**Issue by deluan** [lucaslorentz/caddy-docker-proxy#167]
I know I should be using Caddy v2 by now, but my server was running for months with a custom Docker image, based on the binary generated by:
```
CADDY_TELEMETRY=on curl https://getcaddy.com | bash -s personal docker,http.cache,http.cgi,http.jwt,http.login,http.realip,tls.dns.cloudflare
```

I had an issue with the server today, and when trying to rebuild the Caddy image, I'm getting this error:
```
wget: server returned error: HTTP/1.1 500 Internal Server Error
```

When trying to build the image manually from the https://caddyserver.com/v1/download UI, I see that it still tries to download version 0.3.6 of this plugin. If I disable `docker` in the UI the build passes. 

I'll migrate to v2 over the weekend, but is there a way to generate this build now, so I can put my server back online while I don't finish the migration? I have a very customized server setup/config, so it may take a while to make it work with Caddy v2...

Thanks for you great work!

**Comment by lucaslorentz** [comment]
I created a branch with the plugins you need:
https://github.com/lucaslorentz/caddy-docker-proxy/blob/temp-deluan/main.go#L12

Try building it with:
```
docker run -it --rm -v c:/artifacts:/root/artifacts golang bash -c "cd ~ && git clone https://github.com/lucaslorentz/caddy-docker-proxy.git && cd caddy-docker-proxy && git checkout temp-deluan && ARTIFACTS=/root/artifacts ./build.sh"
```

Then check folder artifacts you mounted as volume.

There are probably other ways to build it, but this is the quickest I could do.
I think because we bumped into version 2, builders that don't use go modules don't work.

**Comment by lucaslorentz** [comment]
You can also find more information on how to build v1 here:
https://github.com/lucaslorentz/caddy-docker-proxy/tree/v0#building-it

**Comment by deluan** [comment]
It worked, awesome! Thanks! Will keep using this binary while I don't finish the migration to v2!

Keep up the great work!
