### ISSUE TITLE
Add a import file directive

### ISSUE THREAD

**Issue by torwag** [lucaslorentz/caddy-docker-proxy#169]
Not sure if this works already
Having a few rather complicated set-ups, I was wondering if I could trigger from within docker-compose to swallow a caddy part config file for this particular container.
E.g. 
```
caddy.import=./nextcloud_config
```
That would greatly declutter my docker-compose file and still keep a trace from where the config file is coming.
Important would be if it does not need to be a complete caddy config file, it simply sets what is in the file plain to the place it was called. Thus, even just a few lines of config without boilerplate could be placed and mixed with the dynamic compilation done with docker-proxy. Thus, that the following example would work:

```
caddy: mydomain
caddy.reverse_proxy: "{{upstream}}" 
caddy.import: ./nextcloud_config_headers
caddy.import: ./nextcloud_config_rewrites
caddy.tls: "internal"
```

**Comment by francislavoie** [comment]
I'm not sure exactly how this would work. Where is `nextcloud_config` defined? Is it a file in the Caddy container? If so, it should just work as-is with https://caddyserver.com/docs/caddyfile/directives/import

**Comment by torwag** [comment]
Yep it is inside the container... or at least make it accessible inside the container. 
I give the import a try, didn't find it. I just was curious how this works together with the dynamic generation of the Caddyfile based on the docker compose labels.

**Comment by francislavoie** [comment]
The labels are assembled to make a Caddyfile, then they're pushed to the Caddy instance to run. At that point, Caddy will parse the Caddyfile and do the imports.

The import paths are relative to the CWD, which inside the container is /srv I believe. So I recommend using absolute paths instead.

**Comment by francislavoie** [comment]
Inactive, closing.
