### ISSUE TITLE
Add example for logging output

### ISSUE THREAD

**Issue by aduzsardi** [lucaslorentz/caddy-docker-proxy#171]
Hi,
 
Can you please add an example for logging output for http requests coming from clients in the README ?
I'm not sure how to configure logging options/format/output with docker labels

Thank you!

**Comment by francislavoie** [comment]
All you need is this:

```
caddy.log: ""
```

This will enable access logs to stdout along with the rest of the app logs.

To configure subdirectives, you go one level deeper:

```
caddy.log: ""
caddy.log.output: file /var/log/access.log
```

Follow the docs for the rest: https://caddyserver.com/docs/caddyfile/directives/log

**Comment by aduzsardi** [comment]
Thank you
