### ISSUE TITLE
Ubuntu 20.04 crash with mlock limit

### ISSUE THREAD

**Issue by aduzsardi** [lucaslorentz/caddy-docker-proxy#174]
On ubuntu 20.04 the latest version keeps crashing with

> runtime: mlock of signal stack failed: 12
> runtime: increase the mlock limit (ulimit -l) or
> runtime: update your kernel to 5.3.15+, 5.4.2+, or 5.5+
> fatal error: mlock failed
>

**Comment by lucaslorentz** [comment]
It seems to be an issue with ubuntu, as mentioned here:
https://github.com/golang/go/issues/37436

They mention it is fixed in version 1.14.1.

Are you using our official docker images? I will update golang version we use to build and publish a new version.

**Comment by aduzsardi** [comment]
yes , i'm using the ci-apline version
thank you

**Comment by lucaslorentz** [comment]
@aduzsardi 
Could you please try again with latest ci-alpine?
You might need to do something to force docker to pull the new image. Maybe `docker image rm lucaslorentz/caddy-docker-proxy:ci-alpine`, or some something like that.

https://hub.docker.com/layers/lucaslorentz/caddy-docker-proxy/ci-alpine/images/sha256-7bcbd5ad494f2b3e8eaf4555f65a70f66fdef6a435a0411ca52bbe3198de4d09?context=repo

**Comment by aduzsardi** [comment]
Hi @lucaslorentz , it seems that it works now 
I also did an `apt dist-upgrade` yesterday , not sure if that helped or not.

Thank you!

**Comment by lucaslorentz** [comment]
apt dist-upgrade might have helped as well, as it is a problem with a specific kernel version.
Thanks for checking.
The fix on our side will be included in our next release.
I recommend not using CI images on production, as they might be unstable.
Use a specific version like 2.3.0.
Cheers

**Comment by aduzsardi** [comment]
thanks for the heads up, i changed it to use the exact/specific `2.3.0 ` tag
