### ISSUE TITLE
What do you think about adding a Prometheus exporter plugin to this image?

### ISSUE THREAD

**Issue by flaviostutz** [lucaslorentz/caddy-docker-proxy#175]
I could work on that.

**Comment by lucaslorentz** [comment]
I'm not sure.
Each user has different needs regarding plugins, I don't see how to decide which plugins we should have by default.
Maybe we should focus on simplifying how to build a custom docker image with the plugins you need.

If there is a simple way to build your own image with the plugins you want, do you think that would be enough?

**Comment by lucaslorentz** [comment]
@flaviostutz 
Could you please take a look on https://github.com/lucaslorentz/caddy-docker-proxy/pull/176 ?

**Comment by flaviostutz** [comment]
The design of #176 is great. I will discuss more there. Thanks for the fast reply!
