### ISSUE TITLE
Add pre-caddyfile macro expansion mechanism

### ISSUE THREAD

**Issue by SvenDowideit** [lucaslorentz/caddy-docker-proxy#181]
I'd like to give my users something simpler than: 

```
Common:
    labels:
      caddy.email: you@loc.alho.st
      caddy.admin: "0.0.0.0:2019"

      caddy_1: "(dns.loc.alho.st)"
      caddy_1.tls.dns: "gandi {env.GANDIV5_API_KEY}"

somecontainer:
    labels:
      caddy: "*.loc.alho.st loc.alho.st"
      caddy.@sub.host: "sub.loc.alho.st"
      caddy.route: "@sub"
      caddy.route.reverse_proxy: "{{upstreams 8000}}"
      caddy.import: dns.loc.alho.st
      caddy.import_1: admin
othercontainer:
    labels:
      caddy: "*.loc.alho.st loc.alho.st"
      caddy.@match.host: "sub.loc.alho.st"
      caddy.@match.path: "/test /test/*"
      caddy.route: "@match"
      caddy.route.reverse_proxy: "{{upstreams 8080}}"
      caddy.import: dns.loc.alho.st
```

I think this is the bare minimum to use an acme wildcard cert to serve https://sub.loc.alho.st/ from somecontainer's port 8000

What I'd like to do in each container, is something more like

```
somecontainer:
    labels:
      newprefix.virtual.host: sub.loc.alho.st
      newprefix.virtual.port: 8000
      newprefix.auth.role: admin
othercontainer:
    labels:
      newprefix.virtual.host: sub.loc.alho.st
      newprefix.virtual.path: /test/*
      newprefix.virtual.port: 9999
```

(and tbh, I'd like to set an `virtual.port` label in the image, and not need that either...)

So I'm wondering if it would make sense to add a marco / template LabelPrefix (`newprefix` in the above eg), which then uses tmpl processing

I'm kinda guessing I could add the processing step in labelsToCaddyfile() to just add new labels.

so `virtual.tmpl` could contain something like:
```
      caddy: "*.loc.alho.st loc.alho.st"
      caddy.@{{.id}}.host: "{{.Host}}"
      caddy.@{{.id}}.path: "/{{.Path}} /{{.Path}}/*"
      caddy.route: "@{{.id}}"
      caddy.route.reverse_proxy: "{{upstreams {{.Port}}}}"
      caddy.import: dns.loc.alho.st
```

and `auth.tmpl` would let me switch authorisation backends without users needing to redo their compose files.

and if there isn't a named, tmpl we punt - that way deployment specific labels are ignored..

Yes, this is all because I can't add just those labels to a running container, then have a daemon that sees them and adds new labels for caddy-docker-proxy to use

it seems that caddy imports have the go tmpl vars evaluated at load time, so using `{{.Spec.Name}}` in an import results in the name of the service its defined in, not the (different) service i'm importing it in - but perhaps another way to solve this is to be defer the tmpl eval until the import, and then (maybe) I could use label values in that import?

(I also had issues setting the site address `*.loc.alho.st loc.alho.st` in an import, but that may just be something i was doing wrong)

**Comment by SvenDowideit** [comment]
and yes, mildly inspired by https://github.com/wemake-services/caddy-gen/ :)

**Comment by lucaslorentz** [comment]
Interesting.

I think we could let users define those custom templates, as an alternative to the traditional label to caddyfile conversion.

One small suggestion I have is that I think it's better to write those templates without using labels. Something like:
```
{{ if index Labels "virtual.host" }}
  *.loc.alho.st loc.alho.st {
    reverse_proxy {{upstreams ((index Labels "virtual.port") | int) }}
  }
{{ end }}
```

I was thinking about the following specs:

- Templates would be stored in docker configs marked with label `caddy_template_for=<entities>`. Example: `caddy_template_for=container` or `caddy_template_for=service` or `caddy_template_for=container,service`.
- For each container/service found in swarm cluster, all templates will be invoked with that docker object as input data.
- If a template output is a non empty/whitespace string, the output is converted to caddyfile and merged into the final generated caddyfile, along with other contents generated by the traditional label to caddyfile conversion.
- It's template responsibility to decide if it should render or not a caddyfile for that docker object
- Templates would have the following functions available:
  - [sprig](https://github.com/Masterminds/sprig): we had that before, I think I accidentally dropped it
  - upstreams: to easily generate upstreams addresses
  - labels: a uniform way of retrieving all labels of current docker object (container or service)
  - entityType: a way to identify the type of docker object the template is running against (container or service). This might be required in order to write templates compatible with both.

This way, it would also be possible to generate caddyfiles without any labels, purely based on conventions.

@SvenDowideit What do you think? Would that work well for you?

Do you see anything we could drop to simplify the initial implementation?

**Comment by francislavoie** [comment]
FYI Caddyfile snippets can accept arguments like `{args.*}` where `*` is the number of the positional argument passed to the `import` call. This might be good enough for simple cases here, if you weren't already aware. https://caddyserver.com/docs/caddyfile/directives/import

**Comment by lucaslorentz** [comment]
@francislavoie 
Didn't know snippets supported args.
I guess that should be enough.

**Comment by francislavoie** [comment]
Yep! It's a feature I implemented for Caddy v2.1 😄

**Comment by SvenDowideit** [comment]
first up - oer @francislavoie I'll take a poke (yes I wasn't aware) - that might be enough - and might change the idea

@lucaslorentz yup - that looks good - I'm mildly concerned that by thinking in terms of full tmpl processing, the user needs to grok the order of things more - the need to realise that `*.loc.alho.st loc.alho.st {...` requires groups, sub-hosts to be nested inside that section etc, was all hidden and neatly dealt with - but I think i need to play with the idea, and with snippets args a little first.

**Comment by SvenDowideit** [comment]
the simplification that converting labels into other labels, is that order, and nesting is neatly hidden from the user - so `caddy: "*.loc.alho.st loc.alho.st"` can be repeated many times in the labels (but not forgotten?), but results in the caddyfile being correct

oh :/ and there the snippet idea crashes down a little - I moved the `caddy: "*.loc.alho.st loc.alho.st"` into the snippet - but that can't work, as that's evaluated after the caddyfile is rendered without the necessary nesting to enable wildcard cert use.

ok, so yes, _I think_ I do want some form of `caddy-docker-proxy` label import / templating, preferably that is done before the label map is converted into Caddyfile

bear with me while i poke things to figure out what the mvp is

**Comment by SvenDowideit** [comment]
ah, and yes, mixing boundries is bad - 
`      caddy.route.2_reverse_proxy: "{{upstreams {args.0}}}"` in a snippet gives us (a not entirely surprising stack dump :)

```
caddy_1    | panic: runtime error: index out of range [2] with length 2
caddy_1    | 
caddy_1    | goroutine 50 [running]:
caddy_1    | github.com/lucaslorentz/caddy-docker-proxy/plugin/v2/caddyfile.compareBlocks(0xc000a8f200, 0xc000a8e900, 0x1)
caddy_1    | 	github.com/lucaslorentz/caddy-docker-proxy/plugin/v2@v2.0.0-20200812195042-fd0f8cb605bf/caddyfile/marshal.go:107 +0x5ce
caddy_1    | github.com/lucaslorentz/caddy-docker-proxy/plugin/v2/caddyfile.(*Container).sort.func1(0x2, 0x1, 0x0)
caddy_1    | 	github.com/lucaslorentz/caddy-docker-proxy/plugin/v2@v2.0.0-20200812195042-fd0f8cb605bf/caddyfile/marshal.go:79 +0x4f
caddy_1    | sort.insertionSort_func(0xc000451778, 0xc00081fe00, 0x0, 0x9)
caddy_1    | 	sort/zfuncversion.go:12 +0xb1
caddy_1    | sort.stable_func(0xc000451778, 0xc00081fe00, 0x9)
caddy_1    | 	sort/zfuncversion.go:171 +0x86
caddy_1    | sort.SliceStable(0x15caa60, 0xc00081fde0, 0xc000451778)
caddy_1    | 	sort/slice.go:27 +0xcb
caddy_1    | github.com/lucaslorentz/caddy-docker-proxy/plugin/v2/caddyfile.(*Container).sort(0xc00081e6c0)
caddy_1    | 	github.com/lucaslorentz/caddy-docker-proxy/plugin/v2@v2.0.0-20200812195042-fd0f8cb605bf/caddyfile/marshal.go:78 +0xfb
caddy_1    | github.com/lucaslorentz/caddy-docker-proxy/plugin/v2/caddyfile.(*Container).sort(0xc000451a70)
caddy_1    | 	github.com/lucaslorentz/caddy-docker-proxy/plugin/v2@v2.0.0-20200812195042-fd0f8cb605bf/caddyfile/marshal.go:74 +0x53
caddy_1    | github.com/lucaslorentz/caddy-docker-proxy/plugin/v2/caddyfile.(*Container).Marshal(0xc000451a70, 0x0, 0x0, 0x0)
caddy_1    | 	github.com/lucaslorentz/caddy-docker-proxy/plugin/v2@v2.0.0-20200812195042-fd0f8cb605bf/caddyfile/marshal.go:14 +0x2f
caddy_1    | github.com/lucaslorentz/caddy-docker-proxy/plugin/v2/generator.(*CaddyfileGenerator).GenerateCaddyfile(0xc00009c2a0, 0x6fc23ac00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
caddy_1    | 	github.com/lucaslorentz/caddy-docker-proxy/plugin/v2@v2.0.0-20200812195042-fd0f8cb605bf/generator/generator.go:184 +0x750
caddy_1    | github.com/lucaslorentz/caddy-docker-proxy/plugin/v2.(*DockerLoader).update(0xc000660500, 0x0)
caddy_1    | 	github.com/lucaslorentz/caddy-docker-proxy/plugin/v2@v2.0.0-20200812195042-fd0f8cb605bf/loader.go:134 +0x6c
caddy_1    | github.com/lucaslorentz/caddy-docker-proxy/plugin/v2.(*DockerLoader).Start.func1()
caddy_1    | 	github.com/lucaslorentz/caddy-docker-proxy/plugin/v2@v2.0.0-20200812195042-fd0f8cb605bf/loader.go:81 +0x2a
caddy_1    | created by time.goFunc
caddy_1    | 	time/sleep.go:168 +0x44
```

**Comment by SvenDowideit** [comment]
(ignore the specific use of `header` - its just a way for me to see the result of my trial - in reality, i want to use the same syntactical sugar for ports, host, image name, and other things)

one thing i want to take advantage of, is that I can have 2 unrelated containers using labels to mutate a global config

for example, one compose service has

```
      caddy_3: "(admin)"
      caddy_3.header: 'Image-Name "{args.0}"'
```

and another has 

```
      caddy_1: "(admin)"
      caddy_1.header_1: 'Echo-Loaded "true"'
```

and that results in 

```caddy_1    | (admin) {
caddy_1    | 	header Image-Name {args.0}
caddy_1    | 	header Echo-Loaded true
caddy_1    | }
```

but I don't want the users to think in terms of caddy syntax - they should just be annotating their images / containers / services with facts

so `cdp.import: image-name {{.Image}}` (where `cdp.import` is the proposed caddy-docker-proxy import) would result in 2 virtual labels - though I'm not sure how we safely ensure that its a new `caddy_x.` value :/ - as in other places, the import should be in the same `caddy_x.`

Oh the struggles of language definitions of early and late binding!

**Comment by SvenDowideit** [comment]
a possibly simpler proposal than my original, inspired by snippet args.*

## Caddy-Docker-Proxy macro proposal

> NOTE: I'm calling them `macros` so the documentation doesn't become hard to differentiate from caddy import snippets that look similar, but are evaluated at a different phase.

`cdp` adds a new LabelPrefx (I'm going to use `cdp.` for brevity) that is loaded and processed into its own map in a similar fashion to `caddy.` labels

These labels are defined in a similar way to snippet definition

```
# yes, the loc.alho.st needs abstraction too - I think these macros need to be nestable

cdp: virtual.host
cdp.caddy: "*.loc.alho.st loc.alho.st"
cdp.caddy.@sub.host: "{args.0}.loc.alho.st"

cdp: virtual.port
cdp.caddy: "*.loc.alho.st loc.alho.st"
cdp.caddy.reverse_proxy: "{{upstreams {args.0}}}"

```

and are used either as (choose one, or perhaps there's a better syntax :) )

> NOTE: I'm prepending `cdp.` here for label parsing simplicity, i'd much rather not need a prefix and use the macro

```
cdp.virtual.port: 8080
```

or

```
cdp.virtual.host: sub.loc.alho.st
cdp.virtual.port: 8080
```



and are processed just before labelsToCaddyFile so the users don't need to deal with the nesting order needed in Caddyfiles

To be able to mix macros and `caddy_3.` labels, I _think_ matching `cdp_3` to then add `_3` to the defined macro output works?

somewhat contrived example

```
      caddy: "(admin)"
      caddy.header_1: 'Echo-Loaded "true"'
      caddy_1: "(admin)"
      # this needs to be converted to caddy {args.0} for late binding
      caddy_1.header_1: 'Image-Name "{{.Image}}"'
      caddy_2 ....
      cdp_3.virtual.host: sub.loc.alho.st
      cdp_3.virtual.port: 8080
```

**Comment by SvenDowideit** [comment]
OH - and frustratingly, it seems I have to use @labels - as that's needed to nest the routes inside the syntax needed to use wildcard certs :/

**Comment by francislavoie** [comment]
I'm confused. What do you mean by @labels? Do you mean named matchers?

**Comment by SvenDowideit** [comment]
erg, yup, sorry, dealing with too many different syntaxes this week :/

**Comment by SvenDowideit** [comment]
I finally got back to this, and had a quick play with import snippet args (thanks to @lucaslorentz 's #187 

```
# caddy.import alho.st <hostname> <port>
(alho_st) {
        import dns_api_gandi
        @{args.0}_loc_alho_st {
                host {args.0}.loc.alho.st
        }
        route @{args.0}_loc_alho_st {
                #respond "{args.0} goes to port {args.1}"
		reverse_proxy {args.1}
        }
}
```

doesn't work - presumably due to `{args.0}` not being useable in the @matcher name (perfectly reasonable - its dangerous without filtering too)

and I've also not managed to get a snippet that adds `*.loc.alho.st {` section.

Hopefully I'll have enough quiet time tomorrow to implement a go template version like @lucaslorentz suggests - today i've had too many meetings :)

massive thanks for al the help - i'm still learning caddy's good bits

**Comment by francislavoie** [comment]
`{args.*}` definitely does work in named matchers. What error are you seeing?

**Comment by SvenDowideit** [comment]
yup, that works, but fails hard when you add a second  - I'm presuming because that's 2 same named matches

```
  arg:
    labels: 
     caddy: "*.loc.alho.st loc.alho.st"
      caddy.import: alho_st arg {{upstreams 8000}}
  sub:
    image: jwilder/whoami
    networks:
      - cirri_proxy
    labels:
      caddy: "*.loc.alho.st loc.alho.st"
      #caddy.import: alho_st sub {{upstreams 8000}}
```

**Comment by francislavoie** [comment]
I don't understand where it's failing. What's the error message?

**Comment by SvenDowideit** [comment]
```
[ERROR]  Removing invalid block: Caddyfile:48 - Error during parsing: File to import not found: alho_st
```

**Comment by francislavoie** [comment]
Okay, that's essentially saying the snippet doesn't exist at the point where the import is parsed. I don't have a clear picture of the whole setup so I'm not sure why that's happening.

**Comment by SvenDowideit** [comment]
yeah, sorry, my example was alot more complicated, and i was trying to cut it down to something useful - and it looks like I failed

I'll have to find more time later to make a clearer example - but some of it was trying to use overlapping routes for different containers.

**Comment by SvenDowideit** [comment]
@lucaslorentz I started to work out how to implement your proposal - initially for non-swarm containers

see https://github.com/SvenDowideit/caddy-docker-proxy/blob/cdp-macros-experimentation/plugin/generator/templates.go

annoyingly, compose-file config's are Swarm mode only - and one of my targets is hooking up `docker run`, so we need another way to mix in template definitions when not using Swarm.

I'm hoping to have it done before the end of September :)

**Comment by SvenDowideit** [comment]
I'm thinking of allowing containers to have an ENV var that contains a template definition 

`CADDY_DOCKER_PROXY_TEMPLATE=... multiline value ...` as a non-swarm counterpoint to mixing in templates

but - that then also adds an interesting issue - does that template only apply to that container :)

**Comment by lucaslorentz** [comment]
This was discussed in PR https://github.com/lucaslorentz/caddy-docker-proxy/pull/190
I think those changes go a lot in the same direction as caddy-gen.
Might be better to just use it instead of CDP.
A comparison is written in https://github.com/lucaslorentz/caddy-docker-proxy/issues/388#issuecomment-1207283624
