### ISSUE TITLE
import caddy json 

### ISSUE THREAD

**Issue by SvenDowideit** [lucaslorentz/caddy-docker-proxy#184]
so I'm still trying to learn enough to integrate the parts I need, and in https://github.com/greenpau/caddy-auth/issues/1  @greenpau notes that the caddy-auth can currently only be configured using json.

I'm prefering to let caddy-docker-proxy drive my caddy config, so I wonder if it can not only have a `-cadyfile-path`, but also other forms 

or, is there some other way to mix things (other than asking a new caddy user to learn how to use the API, build a module etc - i'm not there yet)

**Comment by francislavoie** [comment]
caddy-docker-proxy only works at the Caddyfile level currently. Merging json is not really in scope right now.

FYI I plan on helping @greenpau with implementing Caddyfile support for his plugin, but it's currently blocked on some issues in Caddy preventing third party plugins from correctly integrating into the Caddyfile adapter to provide global options (which to my understanding is necessary for that plugin).

This is the relevant issue for that bit: https://github.com/caddyserver/caddy/issues/3634

**Comment by SvenDowideit** [comment]
and then https://caddy.community/t/using-caddy-in-docker-to-reverse-proxy-to-localhost-apps/9493?s=03 arrives in my inbox - could that inject the json.... every time :(

**Comment by greenpau** [comment]
@SvenDowideit , you may close this issue, because both `portal` and `jwt` plugin now support `Caddyfile`.

**Comment by SvenDowideit** [comment]
awesome!
