### ISSUE TITLE
supplemental json config?

### ISSUE THREAD

**Issue by sk123** [lucaslorentz/caddy-docker-proxy#186]
Hey @lucaslorentz:  I'm absolutely loving your plugin! I'm trying to incorporate a Caddy 2 auth module (specifically greenpau/caddy-auth-jwt) that doesn't support Caddyfile.  How can I go about appending the json config generated by c-d-p to a static json that I provide?

Thanks again for your incredible work!

**Comment by greenpau** [comment]
@francislavoie , the Caddyfile config is available with `portal` and `jwt` plugins.

**Comment by greenpau** [comment]
@sk123, you may close this issue, because both `portal` and `jwt` plugin now support `Caddyfile`.
