### ISSUE TITLE
Docker file issue i have currently when trying to add this plugin 

### ISSUE THREAD

**Issue by JohanKruger230** [lucaslorentz/caddy-docker-proxy#188]
Hi,

When i try and build a docker image with this plugin i get the following failure 
go get: github.com/lucaslorentz/caddy-docker-proxy@v0.3.6 requires
        github.com/lucaslorentz/caddy-docker-proxy/plugin@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000

**Comment by lucaslorentz** [comment]
Are you using this module name:
github.com/lucaslorentz/caddy-docker-proxy/plugin/v2

What steps are you following to build the docker image?

**Comment by JohanKruger230** [comment]
Thank you with the URL you provided it fix the issue. 
github.com/lucaslorentz/caddy-docker-proxy i was using only this which was causing the issue.
