### ISSUE TITLE
Directive php_fastcgi not working well

### ISSUE THREAD

**Issue by andersondalmina** [lucaslorentz/caddy-docker-proxy#191]
When using the directive `php_fastcgi` with multiple upstreams, the generated Caddyfile is not able to work well with load balance. The Caddyfile is:
```
:80 {
    php_fastcgi 172.29.0.3:9000
    php_fastcgi 172.29.0.5:9000
}
```

With this Caddyfile is created two `reverse_proxy` configs on the json config file, each one to one of the upstreams. So the load balance always try to access the first upstream, and just redirect to the second if the first is not responding.

When working with the directive `reverse_proxy` the generated caddyfile is right:
```
:80 {
    reverse_proxy 172.29.0.5:9000 172.29.0.3:9000
}
```
Then are created just one `reverse_proxy` config on the json config file with both upstreams, and the load balance works well.

**Comment by lucaslorentz** [comment]
We don't combine php_fastcgi yet, we only do that for reverse_proxy.
Fixing it.

**Comment by lucaslorentz** [comment]
Fixed in release https://github.com/lucaslorentz/caddy-docker-proxy/releases/tag/v2.3.1
