### ISSUE TITLE
Adding multiple domains per container

### ISSUE THREAD

**Issue by OmgImAlexis** [lucaslorentz/caddy-docker-proxy#2]
I was hoping something like this would work. 

```
caddy.address=whoami1.caddy-proxy,whoami2.caddy-proxy
```

**Comment by OmgImAlexis** [comment]
Solved my own issue. Maybe this should be added to the docs?
To use multiple domains use a single quote around the domains like so. It'll create the config below.

```
docker service create --network caddy -l caddy.address='whoami2.caddy-proxy, whoami3.caddy-proxy' -l caddy.targetport=8000 -l caddy.tls=off --name whoami2_3 jwilder/whoami
```

```
whoami2.caddy-proxy,whoami3.caddy-proxy {
  gzip
  proxy / whoami2_3:8000 {
    transparent
  }
  tls off
}
```

**Comment by lucaslorentz** [comment]
Nice.

Whitespace there would be considered separate arguments, not a continuous label value.

I agree, I need to update docs.

**Comment by OmgImAlexis** [comment]
Since you use a single quote it's not an issue. I've already tired this out.

**Comment by lucaslorentz** [comment]
Ok, thanks!
