### ISSUE TITLE
Multi-instance common root ca for localhost services ?

### ISSUE THREAD

**Issue by rafntor** [lucaslorentz/caddy-docker-proxy#201]
Thanks for a super plugin/image 👍 

When using multiple instances of caddy-docker-proxy (on different servers) is it possible to make them do acme-lookup of localhost-servers from one central caddy-docker-proxy?

Caddy has this internal acme-server, but how can it be used from caddy-docker-proxy?
https://caddyserver.com/docs/caddyfile/directives/acme_server

My rationale is that if a single instance could generate the certs from the same root ca for localhost-services on multiple servers then it would be possible to install a single trusted cert in client-machines and have https access to all services on the lan.

Example - "Server1" (Main)
```bash
docker run -d --name caddy -p 80:80 -p 443:443 \
  -v ~/docker/caddy/data:/data \
  -v /var/run/docker.sock:/var/run/docker.sock \
  --restart unless-stopped lucaslorentz/caddy-docker-proxy

# service on localhost ; caddy makes it https
docker run -d --name some-service1 \
  -l caddy=address1.lan -l caddy.tls=internal \
  -l caddy.reverse_proxy="{{upstreams 80}}" \
  test/some-service
```

Example - "Server2" - using "Server1" for acme lookup of 'internal' services ??
```bash
docker run -d --name caddy -p 80:80 -p 443:443 \
  -v ~/docker/caddy/data:/data \
  -v /var/run/docker.sock:/var/run/docker.sock \
  --label caddy.local.tls.ca = https://server1.lan/acme/local/directory \     <<<<< ?????
  --restart unless-stopped lucaslorentz/caddy-docker-proxy

# service on localhost ; caddy makes it https with cert from "Server1" ???
docker run -d --name some-service2 \
  -l caddy=address2.lan -l caddy.tls=internal \
  -l caddy.reverse_proxy="{{upstreams 80}}" \
  test/some-service
```

Is something like this at all possible?

**Comment by francislavoie** [comment]
All you need to do is make sure they all share the same storage. Caddy supports clustering by using the storage for locking when doing important operations.

**Comment by rafntor** [comment]
Thanks, but is that possible with different servers (Windows / Linux / VMs) , so multiple docker hosts..? (No Kubernetes or Swarm .. just a bunch of freestanding docker installations)
I guess I could spin up 1st caddy-docker-proxy and grab the generated root.crt/key and copy to any other caddy-docker-proxies I spin up ; but it would be smoother if I could point them to the 'main' caddy and utilize the built-in acme-server (if at all possible)

**Comment by francislavoie** [comment]
Yes - just use something like glusterfs or ceph to synchronize the storage. Or you can use one of the various storage plugins if those work for you: https://caddyserver.com/docs/json/storage/

**Comment by rafntor** [comment]
OK so with clustering approach I would need to setup a storage-container somewhere and point all caddy's to it. I am not familiar with any of those and also notice only 'file_system' is standard in caddy so even if possible it looks a bit non-trivial.

If turning back to original approach ; utilizing build-in acme-server from the 'secondary' caddy's - is that a possible path too or is there something preventing it, do you know? Do you know what the syntax would look like when setting up the caddy-containers?

**Comment by francislavoie** [comment]
I think the ACME server approach will be more complex than configuring storage, frankly. It's quite easy to compile Caddy with plugins, especially with the official `builder` docker image variant which ships with `xcaddy`. But the ACME server approach is a viable option if all of your Caddy instances can communicate with the one that will act as the ACME server.

Basically, you'll be configuring your other instances with the `acme_ca` and `acme_ca_root` global options https://caddyserver.com/docs/caddyfile/options and as noted by the `acme_server` directive docs, the CA path will be `https://localhost/acme/local/directory` (replace `localhost` with whatever name your ACME server instance will be accessible from). You'll need to copy over the CA cert from that one and make it accessible to each instance when you run them (with a volume, or COPY it in at build time I guess).

**Comment by rafntor** [comment]
Thanks again, I must investigate my options some more then. I am primarily looking to use the caddy-docker-proxy as is with all it gives already and configure caddy indirectly through labels when launching the container, avoid self-building. The clustering-mode was interesting too, if I can find a simple way in that direction

**Comment by rafntor** [comment]
Clustering mode working fine, using https://github.com/vieux/docker-volume-sshfs for sharing storage

**Comment by francislavoie** [comment]
Neat - yeah that's a good solution for it.
