### ISSUE TITLE
Problems with Basicauth

### ISSUE THREAD

**Issue by Saboti** [lucaslorentz/caddy-docker-proxy#203]
Hi,

I want to activate the Basicauth so I added the following Label to my Container:
caddy.basicauth: "/ admin xxxxxxxxxxxxxxxxxxxx"
But He always gets me this Error after the start:
Removing invalid block: parsing caddyfile tokens for 'basicauth': Caddyfile:41 - Error during parsing: unrecognized hash algorithm: admin
Seems like its using the old v1 basicauth layout. V2 should look like this:
https://caddyserver.com/docs/caddyfile/directives/basicauth
basicauth /secret/* {
	Bob JDJhJDEwJEVCNmdaNEg2Ti5iejRMYkF3MFZhZ3VtV3E1SzBWZEZ5Q3VWc0tzOEJwZE9TaFlZdEVkZDhX
}

Regards Saboti

**Comment by francislavoie** [comment]
I think it needs to be more like this:

```
caddy.basicauth.admin: "<base64hash>"
caddy.basicauth.otheradmin: "<base64hash>"
```

**Comment by Saboti** [comment]
Perfect. Working now with caddy.basicauth.admin: "<base64hash>".
Thank you!
