### ISSUE TITLE
Exclude sub-path from basic auth

### ISSUE THREAD

**Issue by nikolas-digitalBabylon** [lucaslorentz/caddy-docker-proxy#213]
Hi,

Is there a way to exclude a sub-path from authentication?
For example:
abc.com/* <- basic auth enabled
abc.com/public <- basic auth disabled

If possible, how would the labels of a container look like for something like this?
Thanks.

**Comment by lucaslorentz** [comment]
Seems that you need to use request matchers and the basicauth directive:
https://caddyserver.com/docs/caddyfile/matchers
https://caddyserver.com/docs/caddyfile/directives/basicauth

Based on the docs, I think the caddyfile should look like:
```
@not_public not path /public /public/*
basicauth @not_public {
   userA hashedPasswordA
   userB hashedPasswordB
}
```

Which can be generated with labels:
```
caddy.@not_public: "not path /public /public/*"
caddy.basicauth: "@not_public"
caddy.basicauth.userA: "hashedPasswordA"
caddy.basicauth.userB: "hashedPasswordB"
```

I didn't test the config above, but I guess it is a good starting point for you.

**Comment by nikolas-digitalBabylon** [comment]
Hi,

thanks for the swift response! Your point makes sense, thanks a lot for the hint!
