### ISSUE TITLE
Docker image tag and arch mismatch

### ISSUE THREAD

**Issue by 0uep** [lucaslorentz/caddy-docker-proxy#218]
There is an inconsistency between the image tag and its OS/arch.

TAG | OS/ARCH | Docker image details
---|---|--
ci-arm32v6 | linux/amd64 | [hub.docker.com/layers/lucaslorentz/caddy-docker-proxy/ci-arm32v6](https://hub.docker.com/layers/lucaslorentz/caddy-docker-proxy/ci-arm32v6/images/sha256-49ce809fceb78a6d9a3dc2106d95d03a90361de449c9b853faf63a1ae7008696)
2.3-arm32v6 | linux/amd64 | [hub.docker.com/layers/lucaslorentz/caddy-docker-proxy/2.3-arm32v6](https://hub.docker.com/layers/lucaslorentz/caddy-docker-proxy/2.3-arm32v6/images/sha256-49ce809fceb78a6d9a3dc2106d95d03a90361de449c9b853faf63a1ae7008696)
2.3.4-arm32v6 | linux/amd64 | [hub.docker.com/layers/lucaslorentz/caddy-docker-proxy/2.3.4-arm32v6](https://hub.docker.com/layers/lucaslorentz/caddy-docker-proxy/2.3.4-arm32v6/images/sha256-49ce809fceb78a6d9a3dc2106d95d03a90361de449c9b853faf63a1ae7008696)

**Comment by lucaslorentz** [comment]
Hey @0uep 
Thanks for reporting this.
Can you please double check if I put the right platform ids in https://github.com/lucaslorentz/caddy-docker-proxy/pull/219 ?

**Comment by lucaslorentz** [comment]
I'm facing issues with the build pipeline while fixing that tag mismatch.

As a workaround, please use the alpine variants until this issue is solved:
- ci-alpine-arm32v6
- 2.3-alpine-arm32v6
- 2.3.4-alpine-arm32v6

**Comment by 0uep** [comment]
Hey @lucaslorentz
Your change seems OK, but not sure. Hope it will fix the issue. :crossed_fingers:
Thank you for your super work.
I have integrated it in my build (see my Dockerfile https://github.com/lucaslorentz/caddy-docker-proxy/pull/219#issuecomment-786070532).
However I have not yet migrated my Caddyfile to my docker-compose.yml…

**Comment by 0uep** [comment]
I have wrote my previous message at the same time as yours.
Hope you will fix it easily. :)
