### ISSUE TITLE
Second vhost not bind to port 80 

### ISSUE THREAD

**Issue by pwFoo** [lucaslorentz/caddy-docker-proxy#22]
Hello @lucaslorentz ,

I try to add backends to the revproxy, but it doesn't work... I don't know why.

Generated caddyfile looks good to me (domain replaced!)
```
2018/04/05 14:58:38 [INFO] New CaddyFile:
2018/04/05 14:58:38 sub1.example.com {
  proxy / 172.17.0.7:2015
  tls off
}
sub2.example.com {
  proxy / 172.17.0.4:2015
}

Activating privacy features... done.
http://sub2.example.com
2018/04/05 14:58:38 http://sub2.example.com
http://sub1.example.com:2015
2018/04/05 14:58:38 http://sub1.example.com:2015
https://sub2.example.com
2018/04/05 14:58:38 https://sub2.example.com
2018/04/05 14:59:11 [INFO] sub1.example.com - No such site at :80 (Remote: <IP>, Referer: )
```

sub1 works fine, also with tls. sub2 doesn't work. Backend IP, Port and content is ok, but caddy proxy log says "No such site at :80"

Looks like sub2 isn't bind to port 80?! Diff is just "tls off". So it should bind to port 80 and 2015, right? Is it a plugin / caddy issue?

**Comment by pwFoo** [comment]
Workaround is to add the port to caddy.address=example.com:80, but that won't work with multiple domains? Added like that example `-l caddy.address=sub1.example.com:80,sub2.example.com:80` and caddyfile looks like that:
```
sub1.example.com:80,sub2.example.com:80 {
  proxy / 172.17.0.7:2015
  tls off
}
```

Reload fails.
```
2018/04/05 15:41:21 [ERROR] SIGUSR1: error inspecting server blocks: address sub1.example.com:80,sub2.example.com:80:: too many colons in address
```

Maybe a caddy bug? 
With tls enabled vhost is bind to 80+443. 
With tls off it just listen to 2015 and NOT port 80?

So what do I wrong if a vhost just should listen to the default http port 80 with multiple domains?

**Comment by pwFoo** [comment]
Searched some more information and it looks like "normal caddy behavior"? 
With tls 2015 and 80 redirected to 443, but with tls disabled it only listens to the default port (2015), with is NOT 80. 

How do you solve that problem? Do you add http:// to each domain in caddy.address?

**Comment by lucaslorentz** [comment]
I would go with `-port 80` option, that way you can keep your addresses clean like:
```
-l caddy.address=sub1.example.com sub2.example.com
```

**Comment by lucaslorentz** [comment]
@pwFoo 
Did you get it working?

**Comment by pwFoo** [comment]
Hi @lucaslorentz ,

thanks for support me here! Multiple domains are working fine space separated instead of comma.
I'll test the `-port 80` cli option to see if it will solve my problem with `caddy.tls=off`.

Your plugin is awesome and much better than my caddy + docker-gen solution I used before! Much more flexible with additional caddy options! 👍
