### ISSUE TITLE
Clarify/document how to use in docker swarm with (additional) usage of caddy api

### ISSUE THREAD

**Issue by suchwerk** [lucaslorentz/caddy-docker-proxy#220]
Disclaimer: I have no deeper knowledge of caddy/go.

As far as i can see from the sources there is no possibily to do additional configuration via the caddy api  as the config is always replaced via /load on each server. Or do i miss somthing?

Would be great if  using the caddy api with this plugin in docker swarm context would be possible.

**Comment by francislavoie** [comment]
That's correct. This probably isn't the right tool for you if you also need to use the JSON API. It's not really a good idea to try to mix Caddyfile tooling with JSON tooling, since Caddyfile to JSON is a one-way conversion.

**Comment by lucaslorentz** [comment]
We don't have such feature yet
Discussion will continue on https://github.com/lucaslorentz/caddy-docker-proxy/issues/221
