### ISSUE TITLE
Multiple rewrites / uri directives?

### ISSUE THREAD

**Issue by pwFoo** [lucaslorentz/caddy-docker-proxy#222]
Hi,

I need multiple rewrite / uri replace. Get it done wit both combined:
```
      caddy.rewrite: "/.well-known/carddav /remote.php/dav"
      caddy.uri: "replace /.well-known/caldav /remote.php/dav"
      caddy.reverse_proxy: "{{upstreams 80}}"
```

But how to use more than one rewrite if needed?

Added to rewrite the first one is lost. Maybe it's related to caddy v2, but maybe you have a short hint about that?

**Comment by francislavoie** [comment]
If you need multiple of the same directive, use a `_#` suffix for the label. It's explained in the README

```
caddy.rewrite_0: "/.well-known/carddav /remote.php/dav"
caddy.rewrite_1: "/.well-known/caldav /remote.php/dav"
```

**Comment by pwFoo** [comment]
Don't know that works for rewrite and other directives too! Thanks!
