### ISSUE TITLE
env front_controller_active

### ISSUE THREAD

**Issue by zilexa** [lucaslorentz/caddy-docker-proxy#225]
I am a bit embarassed to knock on your door again, but I can't relate 1 line to any documentation. Your documentation does mention controllers, but I don't think thats the same thing. 

I am trying to get Nextcloud-fpm (21), redis, postgresql to work without using any nginx containers. There are not much examples online, definitely not with caddy-docker-proxy. 

just 1 question: `env front_controller_active true` how can I add that to my labels? What I already have: 
```
      caddy: next.$DOMAIN
      caddy.tls: $EMAIL
      caddy.php_fastcgi: "{{upstreams 9000}}"
      caddy.php_fastcgi.root: "* /var/www/nextcloud"
      caddy.file_server: "" 
      caddy.encode: gzip
      caddy.rewrite_0: "/.well-known/carddav /remote.php/dav"
      caddy.rewrite_1: "/.well-known/caldav /remote.php/dav"
```

The way it is used with caddyfile:
```
nextcloud {
   root * /var/www/nextcloud
   encode gzip zstd
   file_server
   php_fastcgi 127.0.0.1:9000 {
      env front_controller_active true
```

**Comment by francislavoie** [comment]
`caddy.php_fastcgi.env: "front_controller_active true"`

Also, you want `caddy.root: "* /var/www/nextcloud"` instead of putting root inside `php_fastcgi`.

**Comment by zilexa** [comment]
Thanks, that makes sense, so easy. 
Unfortunately I just get a blank page, no error, no nextcloud logs. I will have a better look tomorrow. The issue might not be caddy. When I change the port "{{upstreams 80}}" (but for php_fastcgi it is suppose to be 9000) the behavior is exactly the same. Will look into Nextcloud doc.

**Comment by francislavoie** [comment]
Ah - the tricky part about having php-fpm is that both the Caddy container _and_ the fpm container need access to the files, so you need to have them share the volume.
