### ISSUE TITLE
Caddy demo expose ports

### ISSUE THREAD

**Issue by do-web** [lucaslorentz/caddy-docker-proxy#228]
I have tried the demo with docker swarm:

`docker stack deploy -c examples/standalone.yaml caddy-docker-demo`

But the caddy ports are not exposed:

`lucaslorentz/caddy-docker-proxy:ci-alpine   "/bin/caddy docker-p…"   80/tcp, 443/tcp, 2019/tcp   caddy_caddy.1.5wkj12uzfkz1pn926njei98nw`

How to expose the ports and access the service hosts? (I have changed the hostnames to my domain)
Without swarm all works fine, but I would like to run it with docker swarm. 

Edit:

ok under serivces the port is exposes:

fx7a9h34wgj0   caddy_caddy   replicated   1/1        lucaslorentz/caddy-docker-proxy:ci-alpine                       *:80->80/tcp, *:443->443/tcp

But iam not able to connect to the hostname i have set. In caddy log says error ""msg":"no upstreams available""

**Comment by lucaslorentz** [comment]
Can you please detail all steps you're doing?

I just did `docker stack deploy -c examples/standalone.yaml caddy-docker-demo`
Then `curl -k --resolve whoami0.example.com:443:127.0.0.1 https://whoami0.example.com` and it worked for me.

I'm on Mac OS with docker.

**Comment by do-web** [comment]
In caddy log the upstream is not set:

mydomian.com {
	reverse_proxy
	tls internal
}

2021/03/28 19:10:12 [INFO] Skipping default Caddyfile because no path is set
[WARNING] Service m84lry3pmkusv8dn6sdmrz0ei and caddy are not in same network

I tested it with my project:

`
version: "3.7"
services:

  my_service:
    build: .
    image: my_image
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/public
    networks:
      - caddy

    deploy:
      labels:
        caddy: mydomain.com
        caddy.reverse_proxy: "{{upstreams 80}}"
        caddy.tls: "internal"

networks:
  caddy:
    driver: overlay
`

**Comment by lucaslorentz** [comment]
It is not working for you because caddy and my_service don't have a network in common.

This happens because each compose file deployed creates a new network.

You can use this option to get it working when using multiple compose files: https://docs.docker.com/compose/networking/#use-a-pre-existing-network

**Comment by do-web** [comment]
Ah ok, thank you!!
