### ISSUE TITLE
Use port 80 within LAN for local service 

### ISSUE THREAD

**Issue by zilexa** [lucaslorentz/caddy-docker-proxy#229]
Caddy logically requires port 80 and 443 to be forwarded to your server and via Compose, port 80 and 443 on the host are mapped to Caddy's container. 

Within my LAN, I would like to be able to go to just go the LAN IP of my server (http://192.168.8.2) to access a management website that runs on my sever. I do not want to expose it to the web. 

Is there a way to make port 80 available within the LAN?

Besides that, it would be great if I could access (within LAN only) unexposed services (no Caddy labels) via http**s**://my.domain:portnumber, but I don't think is possible.

**Comment by francislavoie** [comment]
Yeah, just use a site address like `http://` or `:80`.

https://caddyserver.com/docs/caddyfile/concepts#addresses

**Comment by zilexa** [comment]
Thanks, I'll give it a try and will keep an eye on that feature.
