### ISSUE TITLE
Add custom config to Caddyfile?

### ISSUE THREAD

**Issue by OmgImAlexis** [lucaslorentz/caddy-docker-proxy#23]
~Is it possible for example to proxy to a service that isn't within the swarm?~

Renamed the issue as it's more fitting.

**Comment by lucaslorentz** [comment]
Currently we only support generating Caddyfile from service and containers labels.

If that external service is related to one of your swarm services, you can add it's config on that service, like:
```
caddy_0.address=service.example.com
caddy_0.targetport=80
caddy_0.targetpath=/my-path
caddy_1=external.example.com
caddy_1.proxy="/ external-url"
```

If you don't need the proxy to swarm service, you can write only the external one:
```
caddy=external.example.com
caddy.proxy="/ external-url"
```

**Comment by lucaslorentz** [comment]
I think we can easily add support appending the content of a `docker config` to the Caddyfile.

**Comment by pwFoo** [comment]
Your example should also work to create redirects like examples below?
- domain.com -> www.domain.com
- domain1.com -> domain2.com
- domain1.com -> https://www.domain2.com
- ...
