### ISSUE TITLE
caddy.log error

### ISSUE THREAD

**Issue by zilexa** [lucaslorentz/caddy-docker-proxy#233]
I like to be able to access the log, as I cannot copy/paste it from Portainer and the only other option is to get it from non-persistent location within /var/lib/docker. 

Before I tried to save the log in /data/access.log (because /data is a bind mount), I tried this first: 

I added: 
```
      caddy.log: ""
      caddy.log.output: file /data/access.log
```

But I get this error even though it should be ok: 
```

[ERROR]  Removing invalid block: Caddyfile:3: unrecognized global option: log

{

	email my@email.com

	log {

		output file /var/log/access.log

	}

}

```

I do follow the documentation: 
https://caddyserver.com/docs/caddyfile/directives/log

**Comment by capps1994** [comment]
The log statement is not a global option, you need to add this to each individual virtual host you will create https://caddyserver.com/docs/quick-starts/caddyfile. However, you can create a snippet with your log config and use the import statement to reuse the log config [here](https://caddyserver.com/docs/caddyfile/concepts#snippets)

**Comment by francislavoie** [comment]
It's worth noting that since Caddy `v2.4.0-beta.2`, there is global logging config, but yep, access log config goes inside of each site.

Also I don't recommend writing logs to `/data`, there's no guarantee that Caddy won't overwrite whatever's in that path.

**Comment by francislavoie** [comment]
This has been answered.
