### ISSUE TITLE
unable to set 2x header_up directives

### ISSUE THREAD

**Issue by accesstechnology-mike** [lucaslorentz/caddy-docker-proxy#240]
I'm trying to create this Caddy directive: 

```
sub.domain.com {
    reverse_proxy container_ip:443 {
        header_up X-Forwarded-Proto {scheme}
        header_up X-Forwarded-Host {host}
    }
}
```
However, using this label format:

```
      caddy: domain.domain.com
      caddy.reverse_proxy: "{{upstreams 443}}"
      caddy.reverse_proxy.header_up: X-Forwarded-Proto {scheme}
      caddy.reverse_proxy.header_up: X-Forwarded-Host {host}
```

It seems the first header_up directive is superseded by the second and removed.

docker logs caddy shows the following:

```
sub.domain.com {
        reverse_proxy container_ip:443 {
                header_up X-Forwarded-Host {host}
        }
}
```

How can I create 2x header_up directives?

**Comment by francislavoie** [comment]
Well, you don't actually need that `X-Forwarded-Proto` line, cause Caddy passes it already: https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#headers

But you can do it by using `_0` and `_1` suffixes, as mentioned in the README.

```
      caddy.reverse_proxy.header_up_0: X-Forwarded-Proto {scheme}
      caddy.reverse_proxy.header_up_1: X-Forwarded-Host {host}
```
