### ISSUE TITLE
Request to add HTTP3 flag (optional)

### ISSUE THREAD

**Issue by tkreind** [lucaslorentz/caddy-docker-proxy#241]
With HTTP3 being supported on all browsers now and widely useful, it'd be nice to have an environment variable you can optionally pass to the container to add

{
    experimental_http3
}

to the Caddyfile and enable http3.

**Comment by francislavoie** [comment]
Just add global options as a label to your caddy-docker-proxy service. No need for anything extra.

**Comment by seonglae** [comment]
Is global option by labels still available? I added http3 label to caddy service but protocol is still h2!

I'm using  lucaslorentz/caddy-docker-proxy:2.4-alpine

**Comment by francislavoie** [comment]
Yes, see the README for how to configure global options.

Make sure you review the Global Options docs on the Caddy website for how to configure `experimental_http3`, it's nested a couple levels deeper.

**Comment by IndeedNotJames** [comment]
@seonglae 
> I added http3 label to caddy service but protocol is still h2!

The caddy-docker-proxy plugin leverages reloads, which seem to be broken with http/3 at the moment.
See https://github.com/caddyserver/caddy/issues/4348 and https://github.com/caddyserver/caddy/pull/4413 for more information :)
