### ISSUE TITLE
xcaddy build invalid version: unknown revision

### ISSUE THREAD

**Issue by ofsahin** [lucaslorentz/caddy-docker-proxy#242]
hello,

i try to build with two different addresses, fail at both.
1 --with github.com/lucaslorentz/caddy-docker-proxy/v2
2 --with github.com/lucaslorentz/caddy-docker-proxy
here is the logs:

```
go: github.com/lucaslorentz/caddy-docker-proxy/v2 upgrade => v2.0.0-20200519122212-41a81eab20dc
go get: github.com/lucaslorentz/caddy-docker-proxy/v2@v2.0.0-20200519122212-41a81eab20dc requires
        github.com/lucaslorentz/caddy-docker-proxy/plugin/v2@v2.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
2021/05/04 02:04:09 [FATAL] exit status 1
```

```
go: downloading github.com/lucaslorentz/caddy-docker-proxy v0.3.6
go: github.com/lucaslorentz/caddy-docker-proxy upgrade => v0.3.6
go get: github.com/lucaslorentz/caddy-docker-proxy@v0.3.6 requires
        github.com/lucaslorentz/caddy-docker-proxy/plugin@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
2021/05/04 02:08:12 [FATAL] exit status 1
```

**Comment by francislavoie** [comment]
As the error suggests, you should use `github.com/lucaslorentz/caddy-docker-proxy/plugin/v2`.

You can find the module name here: https://github.com/lucaslorentz/caddy-docker-proxy/blob/3bba3f44fc7335be8538522bb3e61d45bced3133/plugin/go.mod#L1

**Comment by ofsahin** [comment]
**Use module name github.com/lucaslorentz/caddy-docker-proxy/plugin/v2 to add this plugin to your build.**


thank you
