### ISSUE TITLE
Question:  route custom ordering

### ISSUE THREAD

**Issue by samcro1967** [lucaslorentz/caddy-docker-proxy#255]
Not quite sure how to specify the order for a route block.  Need to have the uri strip_prefix before the reverse_proxy statement.  I tried adding .1/2 and _1/2 after the routes, but get errors with the syntax.  Is it possible to order them?  I believe the order matters for caddy to process properly.

**Labels**
```
     - caddy_1.route= "/test*"
     - caddy_1.route.uri= strip_prefix /test
     - caddy_1.route.reverse_proxy= 127.0.0.1:8888
```

Caddyfile syntax generated by labels
```
        route /test* {
                reverse_proxy 127.0.0.1:8888
                uri strip_prefix /test
```
**Caddyfile syntax trying to achieve**
```
        route /test* {
                uri strip_prefix /test
                reverse_proxy 127.0.0.1:8888
```

**Comment by lucaslorentz** [comment]
Try
```
     - caddy_1.route = "/test*"
     - caddy_1.route.uri_1 = strip_prefix /test
     - caddy_1.route.reverse_proxy_2 = 127.0.0.1:8888
```

**Comment by samcro1967** [comment]
It didn't throw an error on the syntax, but it didn't change the order either.

**Comment by kevinfilipe** [comment]
I think you could try this way:

```
- caddy_1.route = "/test*"
- caddy_1.route.0_uri = strip_prefix /test
- caddy_1.route.1_reverse_proxy = 127.0.0.1:8888
```

**Comment by samcro1967** [comment]
That gives me:
```
        route /test* {
                0 {
                        uri strip_prefix /test
                }
                1 {
                        reverse_proxy 127.0.0.1:8097
                }
```

**Comment by lucaslorentz** [comment]
@kevinfilipe 
That's perfect! I can't rely on my memory 😄 .

@samcro1967 More info at: [Ordering and Isolation](https://github.com/lucaslorentz/caddy-docker-proxy#ordering-and-isolation)
