### ISSUE TITLE
block path, allow everything else

### ISSUE THREAD

**Issue by praul** [lucaslorentz/caddy-docker-proxy#257]
Hi there and sorry for this newbie question.
I want to block a certain path, namly /login/* and proxy everything else.
This way I can forbid backend access from outside my homenet.

Quick caddy label anyone?
Thank you so much!

**Comment by francislavoie** [comment]
You're probably looking for the `remote_ip` matcher https://caddyserver.com/docs/caddyfile/matchers#remote-ip, plus the `respond` directive https://caddyserver.com/docs/caddyfile/directives/respond

See the example about named matchers here: https://github.com/lucaslorentz/caddy-docker-proxy#sites-snippets-and-global-options

**Comment by praul** [comment]
Took some time, translating this to appropriate labels, but I got it.
 
caddy: "domain.example.com"
caddy.@notblacklisted.not.path: "/login* /login /blacklisted*"
caddy.reverse_proxy: "@notblacklisted {{upstreams 8080 http}}"

Could be added to examples
