### ISSUE TITLE
Separate config generation and serving

### ISSUE THREAD

**Issue by ict** [lucaslorentz/caddy-docker-proxy#258]
Hello and thanks for your great project!

I'm coming from jwilder/nginx-proxy and their companion containers. A nice thing that was possible with that setup was having one container that has access to the docker socket (which from a security standpoint is equal to having `root` on the host system) and generates the nginx configuration while another container, without access to the docker socket, actually uses that config to serve content.

Is this something that can be done here as well? Having one container that serves requests from the internet while also having access to the docker socket is a bit suboptimal.

**Comment by francislavoie** [comment]
That's covered in the README: https://github.com/lucaslorentz/caddy-docker-proxy#execution-modes
