### ISSUE TITLE
Question → Can in run your arm32 Container on arm64 pi4 8GB

### ISSUE THREAD

**Issue by ChristianHaake** [lucaslorentz/caddy-docker-proxy#260]
Hi, 

sorry for asking a stupid question like that.… But can I run your arm32 container on a arm64 ubuntu system? Master and drones are running on ubuntu 64 and the newest docker version. 

Thanks in Advance and have a good day!
Christian

**Comment by francislavoie** [comment]
Probably not.

But you can build your own Docker image with a Dockerfile like this:

https://github.com/lucaslorentz/caddy-docker-proxy#custom-images
