### ISSUE TITLE
Unrecognized Global Option

### ISSUE THREAD

**Issue by samcro1967** [lucaslorentz/caddy-docker-proxy#262]
I upgraded caddy to 2.4.1 today with xcaddy.  I think it pulled a new version of docker-proxy also.  I now see this in the container log.

My CaddyFile is now also formatted in the container logs with \n's and \t's instead of json format.  Not sure if that is 2.4.1 or something else.

**Caddyfile Global Options**
```
{
	https_port	443
	http_port	80
	debug
	email user@mydomain.net
}
```

**Container Logs**
```
{"level":"info","ts":1622568053.5517042,"logger":"docker-proxy","msg":"Process Caddyfile","logs":"[ERROR]  Removing invalid block: Caddyfile:6: unrecognized global option: tls\n{\n\thttps_port 443\n\thttp_port 80\n\tdebug\n\temail user@mydomain.net\n\ttls internal\n}\n\n"}
```

**Caddy Dockerfile**
```
ARG CADDY_VERSION=2.4.1
FROM caddy:${CADDY_VERSION}-builder AS builder
RUN xcaddy build \
    --with github.com/lucaslorentz/caddy-docker-proxy/plugin/v2 \
    --with github.com/greenpau/caddy-auth-portal \
    --with github.com/greenpau/caddy-auth-jwt \
    --with github.com/greenpau/caddy-trace \
    --with github.com/porech/caddy-maxmind-geolocation
FROM caddy:${CADDY_VERSION}-alpine
COPY --from=builder /usr/bin/caddy /usr/bin/caddy
CMD ["caddy", "docker-proxy"]
```

**Caddy Docker-Compose**
```
version: '3.8'
services:
  caddy:
    image: xcaddy:latest
    container_name: caddy
    ports:
      - 80:80
      - 443:443
    networks:
      - wg-pia
    environment:
      - TZ=America/Chicago
      - PUID=1000
      - PGID=1000
      - CADDY_DOCKER_CADDYFILE_PATH=/data/CaddyFile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "${docker}/caddy2/data:/data"
      - "${docker}/caddy2/config:/config"

```

**Comment by francislavoie** [comment]
What are the labels on your other services?

It's clear that CDP is trying to merge anything it thinks are global options from your other services into the global options from the base Caddyfile you provided.

**Comment by samcro1967** [comment]
Thank you!  I checked the container labels in docker-compose yesterday and did not see anything, but I just went back and found one label that was incorrect.  Error is now gone.

The Caddyfile in the container logs is still not in json format.  Pretty hard to read now.  Logs are below.   Any ideas?  Everything seems to be working fine.

[Logs](https://pastebin.com/8Tb5tfNM)

**Comment by francislavoie** [comment]
The logging changes come from https://github.com/lucaslorentz/caddy-docker-proxy/pull/254

@lucaslorentz might have some suggestions.

**Comment by lucaslorentz** [comment]
@samcro1967 
We're aligning CDP logging with Caddy logging defaults and recommendations.
I think by default caddy logs as JSON, that's why now we have the same.
Indeed, JSON is bad to read without additional tooling.

You can add this label to your caddy service to revert it back to a friendly format:
```
caddy.log.format: console
```

Another thing it is preferable to specify a CPD version when building with xcaddy:
```
xcaddy build \
    --with github.com/lucaslorentz/caddy-docker-proxy/plugin/v2@v2.3.5
```
Currently, you're exposed to unreleased changes that are on master branch. This is good for us because those changes get tested, but might not be that great for you :-)

@francislavoie Do you think we should adopt different logging defaults from Caddy?

**Comment by lucaslorentz** [comment]
@samcro1967 
Or instead of the label, you can add this to your base caddyfile
```
{
  log {
    format console
  }
}
```

**Comment by lucaslorentz** [comment]
The next release will be something like: v2.4.0. Bumping minor instead of patch.
As this logging change has a slightly higher impact.

**Comment by samcro1967** [comment]
I added "caddy.log.format=console" as a label in docker-compose to my caddy service and it did not change the output.  I changed it from a ":" to an "=" as it throws an error in the logs with a ":".

Thanks for the tip on versioning.  I usually don't mind trying new versions and help testing.

**Comment by lucaslorentz** [comment]
It should be @v2.3.4 not @v.2.3.4

**Comment by samcro1967** [comment]
Might be time to get my eyes checked and prescription updated.  Updated the Dockerfile.  Logs say module found, but no package available.  I get the same for 2.3.4, 2.3.3, and 2.3.2.

**Caddy Dockerfile**
```
ARG CADDY_VERSION=2.4.0
FROM caddy:${CADDY_VERSION}-builder AS builder

RUN xcaddy build \
    --with github.com/lucaslorentz/caddy-docker-proxy/plugin/v2@v2.3.4 \
    --with github.com/greenpau/caddy-auth-portal \
    --with github.com/greenpau/caddy-auth-jwt \
    --with github.com/greenpau/caddy-trace \
	--with github.com/porech/caddy-maxmind-geolocation

FROM caddy:${CADDY_VERSION}-alpine

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

CMD ["caddy", "docker-proxy"]
```

**Docker Build Logs**
```
go get: added github.com/caddyserver/caddy/v2 v2.4.0
2021/06/02 10:08:15 [INFO] exec (timeout=0s): /usr/local/go/bin/go get -d -v github.com/lucaslorentz/caddy-docker-proxy/plugin/v2@v2.3.4
go: downloading github.com/lucaslorentz/caddy-docker-proxy v0.3.6
go: downloading github.com/lucaslorentz/caddy-docker-proxy v2.3.4+incompatible
go get: module github.com/lucaslorentz/caddy-docker-proxy@v2.3.4 found (v2.3.4+incompatible), but does not contain package github.com/lucaslorentz/caddy-docker-proxy/plugin/v2
2021/06/02 10:08:20 [FATAL] exit status 1
The command '/bin/sh -c xcaddy build     --with github.com/lucaslorentz/caddy-docker-proxy/plugin/v2@v2.3.4     --with github.com/greenpau/caddy-auth-portal     --with github.com/greenpau/caddy-auth-jwt     --with github.com/greenpau/caddy-trace   --with github.com/porech/caddy-maxmind-geolocation' returned a non-zero code: 1
```

**Comment by samcro1967** [comment]
@lucaslorentz Any other suggestions on how to get the logs back to friendly format or revert back to an earlier version?

**Comment by samcro1967** [comment]
For anyone else who stumbles across this, here is the workaround I have found until something better comes along.  Not as nice as reading Caddyfile format, but much easier for me at least to debug than json format.

docker exec into the caddy container
install curl and jq
the run "curl "http://localhost:2019/config/" | jq"

**Comment by francislavoie** [comment]
Setting the log format to `console` should make the Caddyfile render correctly in the logs, does it not?

**Comment by lucaslorentz** [comment]
@samcro1967 
I opened this issue: https://github.com/lucaslorentz/caddy-docker-proxy/issues/265

Setting log format to console worked well on my tests.
Can you please share how you tried it?

**Comment by samcro1967** [comment]
Here is a link to what I see.  No errors and everything is working as expected.

[Logs](https://pastebin.com/CGfbsKbD)

**Comment by lucaslorentz** [comment]
Thanks @samcro1967.
It indeed starts as json and then switches to console logs. But then it is too late.
I will track that in another issue.

**Comment by samcro1967** [comment]
The other thing I noticed after upgrading to the newest version is the log now gets the 2 message below continually.  Not really an issue, but not adding any value either.  I already know I am not running a swarm.  Not sure if there is way to turn that off in the newest version that I just missed in the docs.

1.6227437188209238e+09  info    docker-proxy    Skipping swarm config caddyfiles because swarm is not available
1.6227437188367414e+09  info    docker-proxy    Skipping swarm services because swarm is not available

Appreciate all of your effort!  Very convenient to have all of my config now in docker-compose when I spin up a new service.

**Comment by masterkain** [comment]
I'm trying to hide these messages

```
{"level":"info","ts":1630687314.413251,"logger":"docker-proxy","msg":"Skipping default Caddyfile because no path is set"}

{"level":"info","ts":1630687314.4133,"logger":"docker-proxy","msg":"Skipping swarm config caddyfiles because swarm is not available"}

{"level":"info","ts":1630687314.426478,"logger":"docker-proxy","msg":"Skipping swarm services because swarm is not available"}
```

and log normal http requests.

in docker-compose I have this:

```yaml
  caddy:
    labels:
      caddy.log: "{}"
      caddy.log.level: WARN
      caddy.log.include: docker-proxy
```

but it's not doing neither things, any hints?
