### ISSUE TITLE
How to add another machine on local network to auto-Caddyfile

### ISSUE THREAD

**Issue by dezerving** [lucaslorentz/caddy-docker-proxy#267]
Hi! I love this plugin, makes things a lot easier when quickly deploying new containers for testing, etc.

However, I was having trouble trying to figure out how to add a local machine on another IP in my home network (NOT the docker host) to the Caddyfile. I honestly didn't know how to begin since I can't find where to add it in since its not a docker image.

This is for a Raspberry Pi running Home Assistant on 192.x.x.3 while my docker host is 192.x.x.2. Thank you for your help!

**Comment by francislavoie** [comment]
Either use the `-caddyfile-path` argument to provide a base Caddyfile to use (see https://github.com/lucaslorentz/caddy-docker-proxy#caddy-cli) or add labels to the `caddy-docker-proxy` container itself for the sites you need to proxy to your other machine.

**Comment by dezerving** [comment]
> 
> 
> Either use the `-caddyfile-path` argument to provide a base Caddyfile to use (see https://github.com/lucaslorentz/caddy-docker-proxy#caddy-cli) or add labels to the `caddy-docker-proxy` container itself for the sites you need to proxy to your other machine.

Ah, I missed that. I see now. How would you do the file path with docker-compose? Mount it as a volume?

**Comment by francislavoie** [comment]
That's one way, yeah.

**Comment by dezerving** [comment]
Weird. Doesn't want to work for me. Am I doing something wrong?

`version: '3.7'

configs:
 caddy-basic-content:
  file: /etc/caddy/Caddyfile

services:

 caddy:
  image: lucaslorentz/caddy-docker-proxy:ci-alpine
  container_name: caddy-auto
  hostname: caddy-auto
  restart: unless-stopped
  ports:
   - '80:80'
   - '443:443'
  environment:
   - MY_DOMAIN
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock
   - ./Caddyfile:/etc/caddy/Caddyfile:rw
   - ./data:/data:rw
   - ./config:/config:rw
   
networks:
 default:
  external:
   name: $DOCKER_MY_NETWORK`

**Comment by francislavoie** [comment]
`configs` only works in docker swarm mode. If you're not running with swarm mode, it won't do anything.

**Comment by dezerving** [comment]
Oh shoot. What would be the way to do it for docker-compose then?

**Comment by francislavoie** [comment]
Like I said, either use the `-caddyfile-path` argument (you need to override the command used to run the container), or, put labels right on the CDP container.

**Comment by dezerving** [comment]
> 
> 
> Like I said, either use the `-caddyfile-path` argument (you need to override the command used to run the container), or, put labels right on the CDP container.

Sorry I just didn't understand how that would be used - like where would I use that argument. Right now I just use `docker-compose up -d` to run the container, would I just modify it to add `-caddyfile-path` at the end?

**Comment by dezerving** [comment]
Just saw that there is an environment variable that can be used. 'CADDY_DOCKER_CADDYFILE_PATH=' would that work with docker-compose? I tried 'CADDY_DOCKER_CADDYFILE_PATH=/home/user/containers/caddy-auto/Caddyfile' but it doesn't seem to want to work.
