### ISSUE TITLE
Accessing original host IP

### ISSUE THREAD

**Issue by Maracko** [lucaslorentz/caddy-docker-proxy#270]
How can I access the original IP address of the remote host that tried to access a domain that is managed by caddy-docker proxy?

**Comment by francislavoie** [comment]
Caddy adds the `X-Forwarded-For` header to requests to the proxy upstream https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#headers

But, if you're running in swarm mode, you may run into this issue: https://github.com/moby/moby/issues/25526. Gist of it is that swarm's TCP ingress will cause the remote IP to be rewritten, so the original client's IP would be lost. There's some workarounds listed in that thread that you may want to try.

**Comment by Maracko** [comment]
![image](https://user-images.githubusercontent.com/56165587/124194794-7d46b680-dac9-11eb-9427-3c1f74587df8.png)
On my Go server I have CORS headers set up but the caddy doesn't send `X-Forwarded-For`  header, do I have to turn it on somewhere?

**Comment by francislavoie** [comment]
Those are _response_ headers. The `X-Forwarded-For` header is passed in the upstream _request_.
