### ISSUE TITLE
Caddy cannot connect over swarm to other node/service-container

### ISSUE THREAD

**Issue by Yamakasi** [lucaslorentz/caddy-docker-proxy#272]
I'm facing the issue that Caddy is not capable of connecting from node1 to a container on node2 following it's logs and end up in timeouts in my browser.

When I exec into the caddy container I can curl to that container and get the nginx headers so connection is fine.

I see the following errors when it happens:

`{"level":"error","ts":1625137947.7337053,"logger":"http.handlers.reverse_proxy","msg":"reading from backend","error":"read tcp 10.1.65.3:49276->10.1.65.6:80: read: connection reset by peer"}`

and these a lot as well:

`{"level":"error","ts":1625138171.8006687,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"context canceled"}`

```
Caddy command: 
# curl http://10.1.65.6 -H "Accept: application/html" -H "Host: domain.tld"
Nginx reponse:
10.1.65.3 - - [01/Jul/2021:18:45:00 +0000] "GET / HTTP/1.1" 200 2629 "-" "curl/7.67.0" "-"
Caddy response after long waithing:
curl: (56) Recv failure: Connection reset by peer
```

As info:

I run my Caddy as a replicated service using shared volumes like below. I assume this is just possible and would not conflict any.

```
- /var/run/docker.sock:/var/run/docker.sock
- /mnt/shared/caddy/Caddyfile:/etc/caddy/Caddyfile
- /mnt/shared/caddy/data:/data
- /mnt/shared/caddy/config:/config
- /mnt/shared/letsencrypt/certs/staging:/data/caddy/certificates/acme-staging-v02.api.letsencrypt.org-directory
- /mnt/shared/letsencrypt/certs/live:/data/caddy/certificates/acme-v02.api.letsencrypt.org-directory
```

I hope I'm doing something wrong actually

**Comment by Yamakasi** [comment]
Solved, not a caddy thing

**Comment by lucaslorentz** [comment]
Thank you @Yamakasi, I couldn't think of any reason for the communication error.

If it was a docker-related issue, like networking, ports, miss-configuration, then it would be nice to share your solution as it might happen to others as well.

**Comment by Yamakasi** [comment]
@lucaslorentz It was an MTU issue on my network. Can happen to others but is not likely or people don't have the specs of their network available.
