### ISSUE TITLE
RSA 2048 certificates generation

### ISSUE THREAD

**Issue by nikolas-digitalBabylon** [lucaslorentz/caddy-docker-proxy#273]
Hi,

I need to generate rsa 2048 keys for an application that does not support ec crypto. I only need to have the certs generated by caddy and then import them on the relevant application, no actual proxying. I would like to have the routine of certificate generation and renewal handled by caddy since it is already running on the same system. How can I achieve that? Example labels I could use?

Thank you!

**Comment by francislavoie** [comment]
You're looking for the `key_type` global option: https://caddyserver.com/docs/caddyfile/options

**Comment by nikolas-digitalBabylon** [comment]
Hi and thanks for the quick response! 

The issue is I need to use an RSA key only for one of the services. I assume I need to pass some labels to the relevant container that caddy will catch and generate the certificates. Is my assumption correct? If yes, how should these labels be?

Thanks!

**Comment by francislavoie** [comment]
If you only need to change the key type for one site, then you can do so via the `tls` directive: https://caddyserver.com/docs/caddyfile/directives/tls

Unfortunately the docs for that was incorrect, it was documented as being under `issuer` but it's actually right under `tls` -- I've already fixed the docs but it hasn't been pushed up yet.

So you probably want like `caddy.tls.key_type: rsa2048`

**Comment by nikolas-digitalBabylon** [comment]
Thanks, job done!
