### ISSUE TITLE
Old lucaslorentz/caddy-docker-proxy:0.3.0 documentation?

### ISSUE THREAD

**Issue by pwFoo** [lucaslorentz/caddy-docker-proxy#274]
Hi,
I found an old setup with lucaslorentz/caddy-docker-proxy:0.3.0 (caddy v1) and haven't the time to change the compose files / caddy labels to be compatible to newer images / proxy with caddy v2...

Is the old documentation still available?
Need to add a simple redirect domains -> other domain with 301.

Is there a way to add additional vhosts **domains -> redir domain 301** with the old version? caddy_1.* crashed the reverse proxy container. I don't know if that was a caddy v2 feature of your reverse proxy image...

**Comment by pwFoo** [comment]
Fixed by workaround

**Comment by francislavoie** [comment]
Please explain your workaround in case someone else later finds this issue.

https://m.xkcd.com/979/

**Comment by pwFoo** [comment]
I deployed a caddy v2 service backend.
Added domains by label to connect to the old revproxy. Simple caddyfile listen for :2015 with redir directive.
Same would be possible with apache (htaccess, config) or nginx as redirect service
