### ISSUE TITLE
DNS challenge? Build help? Tips?

### ISSUE THREAD

**Issue by NoLooseEnds** [lucaslorentz/caddy-docker-proxy#275]
Hi, 

I'm looking into replacing my old traefik setup with Caddy, and this project looks neat in that regard – keeping the settings inside of docker-compose files. 

Anyhow, I need to use the DNS challenge with Cloudflare. Is there a prebuilt image with the possibility of a DNS challenge?

If not, how would you suggest going about building one? (I'm having a bit of a hard time). I see you can grab [prebuilt binaries](https://caddyserver.com/download?package=github.com%2Fcaddy-dns%2Fcloudflare) from Caddy.

I did try to ad "wget", and pull the image directly to /bin/ and renaming the file to caddy, but while the build succeed – I can't start the image due to `ERROR: for caddy  Cannot start service caddy: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "/bin/caddy": stat /bin/caddy: no such file or directory: unknown`

This is my modified dockerfile.:
```
FROM alpine:3.11 as alpine
RUN apk add -U --no-cache ca-certificates wget
RUN wget "https://caddyserver.com/api/download?os=linux&arch=amd64&p=github.com%2Fcaddy-dns%2Fcloudflare" -O /bin/caddy && chmod +x /bin/caddy

# Image starts here
FROM scratch
LABEL maintainer "Lucas Lorentz <lucaslorentzlara@hotmail.com>"

EXPOSE 80 443 2019
ENV XDG_CONFIG_HOME /config
ENV XDG_DATA_HOME /data

WORKDIR /
COPY --from=alpine /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

#COPY artifacts/binaries/linux/amd64/caddy /bin/

ENTRYPOINT ["/bin/caddy"]

CMD ["docker-proxy"]
```

**Comment by francislavoie** [comment]
See in the README: https://github.com/lucaslorentz/caddy-docker-proxy#custom-images

**Comment by NoLooseEnds** [comment]
Thanks for the swift response! I did go looking in the documentation, but unfortunately missed it. Thanks again!
