### ISSUE TITLE
Show current caddyfile?

### ISSUE THREAD

**Issue by pwFoo** [lucaslorentz/caddy-docker-proxy#276]
Is it possible to output the current caddyfile to shell?
I know it's shown in the log, but would be great to just show the configuration by command.

**Comment by francislavoie** [comment]
@lucaslorentz I was thinking about this, I think the best solution would be to have CDP write the currently running Caddyfile to `caddy.AppConfigDir() + "Caddyfile.autosave"` or something like that, similar to how Caddy saves the currently running JSON config to `caddy.AppConfigDir() + "autosave.json"`.

**Comment by lucaslorentz** [comment]
That's a great option. And it's easy to implement.

**Comment by francislavoie** [comment]
Also, maybe save the last generated one if there's an error in loading it to `Caddyfile.lasterror`

**Comment by francislavoie** [comment]
@lucaslorentz do you have time to implement this one quickly?

**Comment by lucaslorentz** [comment]
@francislavoie I started working on it

**Comment by jnaskali** [comment]
In the mean time, here's a quick and dirty alias you can use to print out the last Caddyfile from docker log:

```
alias caddy-config='docker logs caddy 2>&1 | awk "/New Caddyfile:/,/New Config/" | head -n -1 | tac | awk "/New Caddyfile:/ {exit} 1" | tac'
```

**Comment by francislavoie** [comment]
@lucaslorentz, think you could get this one in soon? :sweat_smile:
