### ISSUE TITLE
Root directory moveds to sub directory

### ISSUE THREAD

**Issue by ahoeg** [lucaslorentz/caddy-docker-proxy#282]
Hi,

I try to change the document root of backend / php-fpm and hope someone could help me how to get it working. Done some tests with rewrite and root.
CMS need the public document root pointing to the /web (sub-)directory...

How to get that working for apache / php-fpm backend?
Tried to move document root to subdirectory with `caddy.root: "sub/directory"` label, but it doesn't work?

Generated vhost in caddyfile:
```
example.com {
        reverse_proxy 10.0.0.197:2015
        root sub/directory
}
```

also tried `root * /path/to/sub/directory`

php doc root should point to caddy "root" in default? https://example.com/file.php still not works, but https://example.com/sub/directory/file.php works fine. So how to move the document root to a sub directory at upstream?

**Comment by francislavoie** [comment]
`root` has no effect with `reverse_proxy`.

The `root` directive is meant to set the root location to look for files for the `file_server` directive, for the `fastcgi` transport, and for the `file` matcher, among a few other things.

If you want to rewrite the path, then you should use `rewrite`:

```
rewrite * /sub/directory{uri}
```

For next time, please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
