### ISSUE TITLE
Reverse proxy to self-signed https backend

### ISSUE THREAD

**Issue by nikolas-digitalBabylon** [lucaslorentz/caddy-docker-proxy#284]
Hi,

could you provide an example directive on how to proxy to back-ends with self-signed tls certificates? I think this might be a common case so having it documented in the examples of the landing page would be a good idea I guess...

Thanks for the support and congrats for the great work!

**Comment by francislavoie** [comment]
You're looking for the `tls_insecure_skip_verify` option of the http transport. https://caddyserver.com/docs/caddyfile/directives/reverse_proxy

```
caddy.reverse_proxy.transport: "http"
caddy.reverse_proxy.transport.tls_insecure_skip_verify:
```

**Comment by nikolas-digitalBabylon** [comment]
Thank you for the fast response!
Is the `caddy.reverse_proxy.transport: "http"` really correct? I am assuming since the backend is serving https with self-singed tls cert, the transport should be https. Am I correct?

**Comment by francislavoie** [comment]
Yes, see the docs. HTTP + TLS = HTTPS.

**Comment by nikolas-digitalBabylon** [comment]
Yes this is clear. I was refearing to your response above, where you have given in the example transport as http instead of https.

**Comment by francislavoie** [comment]
Yes, because the transport is HTTP. As the docs explain.
