### ISSUE TITLE
SSL error after reload or restart of another image

### ISSUE THREAD

**Issue by thechubbypanda** [lucaslorentz/caddy-docker-proxy#292]
Every time I restart or reload one of my containers (`docker restart` or `docker-compose up -d` or `docker-compose restart`), I get an `SSL_ERROR_INTERNAL_ERROR_ALERT`. The error remains until I either completely remove and remake the container using `docker-compose down && docker-compose up -d` or restart the `caddy-docker-proxy` image.

I should instead just see the website.

**Comment by francislavoie** [comment]
We'll need much more information than that to be able to help. What's your config, what's in the logs, what version are you using, etc.

**Comment by thechubbypanda** [comment]
Thanks for getting to this so quickly but I'm afraid it was a rather convoluted error on my end. Sorry about that!

**Comment by QuentinC** [comment]
Hello @thechubbypanda ,
I happen to have the same issue than yours.
Could you please share what was the problem at your side ?

Best regards !

**Comment by francislavoie** [comment]
@QuentinC please open a new issue, and provide _as much detail as possible_.

**Comment by thechubbypanda** [comment]
> Hello @thechubbypanda , I happen to have the same issue than yours. Could you please share what was the problem at your side ?
> 
> Best regards !

The issue started occurring again after I thought I solved it. For now I've switched to traefik but do link this issue in your new one if you solve it.

**Comment by go2tom42** [comment]
I have had this same issue, but not with all containers.  

Boiled down to any container that had a volume of `/etc/localtime:/etc/localtime:ro` in it would fail, only restarting caddy-docker-proxy would bring the site back up

**Comment by go2tom42** [comment]
I had this problem too but not with all containers

It boiled down to any container that had a volume of `/etc/localtime:/etc/localtime:ro` in it would fail to load after a restart unless I also restarted caddy-docker-proxy
