### ISSUE TITLE
Add Cache-Control expiry header to assets file

### ISSUE THREAD

**Issue by flayks** [lucaslorentz/caddy-docker-proxy#295]
I've seen this snippet that would suit well for adding the Cache-Control/expiring header on static assets:

```
(static) {
	@static {
		file
		path *.ico *.css *.js *.gif *.jpg *.jpeg *.png *.svg *.woff *.woff2 *.json
	}
	header @static Cache-Control max-age=5184000
}
```

Although I'm not exactly sure how to convert that rule to the `docker-compose` format from caddy-docker-proxy?

```yaml
caddy_0.@images.path: "*.png *.jpg *.jpeg *.gif *.webm *.ico *.svg"
caddy_0.@images.header.Cache-Control: '"max-age=31622400"'
```

I get this error: 
```
"logs":"[ERROR]  Removing invalid block: Caddyfile:29 - Error during parsing: malformed header matcher:
```

How to match the `file` directive inside of the @static in the example? And ultimately how to make this work haha

**Comment by francislavoie** [comment]
What's the whole error message? It looks truncated.

What's the Caddyfile it attempted to generate?

Make sure to be careful with double quotes, because they have a very specific meaning in the Caddyfile. https://caddyserver.com/docs/caddyfile/concepts#tokens-and-quotes

As for how that snippet would map to labels, it would probably be something closer to this:

```
caddy_0.@static.file: ""
caddy_0.@static.path: *.ico *.css *.js *.gif *.jpg *.jpeg *.png *.svg *.woff *.woff2 *.json
caddy_0.header: @static Cache-Control max-age=5184000
```

**Comment by flayks** [comment]
@francislavoie thanks for your help! It turned out to be a slightly different config:

```yaml
caddy_0.@static.file: ""
caddy_0.@static.path: "*.js *.css *.png *.jpg *.jpeg *.gif *.ico *.html *.woff *.woff2 *.svg"
caddy_0.header.@static.Cache-Control: "max-age=31536000"
```

Mainly `caddy.header.@static.Cache-Control` over `caddy.header: "@static Cache-Control xxx"`
