### ISSUE TITLE
Intermittent 404 errors

### ISSUE THREAD

**Issue by RKVodde** [lucaslorentz/caddy-docker-proxy#299]
Almost every other request (kind of 2 requests success and next 3 requests fail) is giving 404 error, not sure why. Help appreciated.

**Comment by RKVodde** [comment]
Found the problem

**Comment by francislavoie** [comment]
What was the problem, in case someone else finds this same thread?

https://m.xkcd.com/979/

**Comment by RKVodde** [comment]
In 2 different containers my matcher names were same and thought that was creating the conflict and I was right.

**Comment by francislavoie** [comment]
Thanks for following up! That makes sense :+1:
