### ISSUE TITLE
Multiple docker sockets listening

### ISSUE THREAD

**Issue by amaelFr** [lucaslorentz/caddy-docker-proxy#301]
Is it possible to your plugin with multiple docker sockets?
Thank you for your response and your time

**Comment by amaelFr** [comment]
Hello,
I work with several dockerd running as a non-root user, and I would like to have an upstream reverse proxy (I was using traefik but support for some features requires the enterprise version), that's why I chose caddy.
And especially your plugin, so I added support for using multiple sockets (in a similar way to traefik).

In terms of implementation, I took your management of docker client by putting them in slices, with my zero experience in golang, it seemed interesting to use this vision.


(sorry for my english ....)
Have a nice day

**Comment by lucaslorentz** [comment]
PR was merged. Changes will be included in the next release.
Meanwhile you can build your own docker image following readme instructions.
