### ISSUE TITLE
Security fix in Caddy v2.4.6

### ISSUE THREAD

**Issue by heapdavid** [lucaslorentz/caddy-docker-proxy#313]
Hi,

There's a fix for a path matching security issue in the latest version of Caddy

https://github.com/caddyserver/caddy/releases/tag/v2.4.6

https://github.com/caddyserver/caddy/pull/4407

Would it be possible to incorporate this?

**Comment by francislavoie** [comment]
You can build the image yourself with the latest version of Caddy. Follow the instructions in the README: https://github.com/lucaslorentz/caddy-docker-proxy#custom-images
