### ISSUE TITLE
Impossible to renew certificates

### ISSUE THREAD

**Issue by flayks** [lucaslorentz/caddy-docker-proxy#318]
Most of my certificates are coming to expiring in a few days (dec 2nd) and I keep seeing these errors in the logs:

```
caddy    | {"level":"warn","ts":1637575208.0768826,"logger":"tls.issuance.acme.acme_client","msg":"HTTP request failed; retrying","url":"https://acme-v02.api.letsencrypt.org/directory","error":"performing request: Get \"https://acme-v02.api.letsencrypt.org/directory\": dial tcp: lookup acme-v02.api.letsencrypt.org on 127.0.0.11:53: read udp 127.0.0.1:41951->127.0.0.11:53: i/o timeout"}

caddy    | {"level":"error","ts":1637575288.8642898,"logger":"tls.renew","msg":"could not get certificate from issuer","identifier":"sub.domain.com","issuer":"acme.zerossl.com-v2-DV90","error":"[sub.domain.com] creating new order: provisioning client: performing request: Get \"https://acme.zerossl.com/v2/DV90\": dial tcp: lookup acme.zerossl.com on 127.0.0.11:53: read udp 127.0.0.1:38579->127.0.0.11:53: i/o timeout (ca=https://acme.zerossl.com/v2/DV90)"}

caddy    | {"level":"warn","ts":1637575268.603046,"logger":"tls.issuance.acme.acme_client","msg":"HTTP request failed; retrying","url":"https://acme.zerossl.com/v2/DV90","error":"performing request: Get \"https://acme.zerossl.com/v2/DV90\": dial tcp: lookup acme.zerossl.com on 127.0.0.11:53: read udp 127.0.0.1:47114->127.0.0.11:53: i/o timeout"}
```

I'm not exactly sure how and why this is happening but this definitely doesn't look like a normal behaviour. I use a little VPS on Scaleway for hosting. Most of my sites uses Cloudflare for DNS-only (not proxying) - although I'm a bit confused about all of this and the `.well-known` certificate issuing thing.

**Comment by francislavoie** [comment]
Looks like your Docker stack or your host machine isn't resolving DNS lookups properly. Something must be misconfigured on your system.

You can try to override this by setting `tls` directive's `resolvers` option to something like `1.1.1.1` or `8.8.8.8` (Cloudflare or Google's DNS servers) https://caddyserver.com/docs/caddyfile/directives/tls

**Comment by flayks** [comment]
Hm that is weird indeed. Running simple nslookup does give me the expected results?

```
$ nslookup 1.1.1.1
1.1.1.1.in-addr.arpa	name = one.one.one.one.

$ nslookup google.com
Server:		10.194.3.3
Address:	10.194.3.3#53
...
```

**Comment by francislavoie** [comment]
Then it's an issue with the Docker stack.

**Comment by flayks** [comment]
Thanks for the clarifications Francis. Although I get it in the concept, technically I don't really know where this could come from, my sysadmin skills are a bit limited 😅 

What could I try to test things if this is really the case?

**Comment by flayks** [comment]
Okay, definitely the server or some Docker issues here, tried to figure out things for 3 or 4 hours and it is now working.
I upgraded Debian in the process from 10 to 11, so it might have helped as well. Also added the `caddy` docker container to the bridge network, figured that the port 53 was used ans opened the Inbound port on Scaleway, changed the `resolv.conf` DNS to use Cloudflare… Whatever worked is now fixing the issue 😂 

Servers sometimes… 🤷
