### ISSUE TITLE
No reading Caddyfile

### ISSUE THREAD

**Issue by travisjroark** [lucaslorentz/caddy-docker-proxy#320]
It's not reading the Caddyfile env and it's getting new certs when starting even though the data directory is mapped with the existing certs. 

version: "3.7"
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy_proxy
      - CADDY_DOCKER_CADDYFILE_PATH=/etc/caddy/Caddyfile
      - CADDY_DOCKER_MODE=standalone
    networks:
      - caddy_proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/docker/caddy/caddy_data:/data
    deploy:
      labels: # Global options
        caddy.email: omitted
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        reservations:
          cpus: "0.1"
          memory: 200M

networks:
  caddy_proxy:
    external: true

volumes:
  caddy_data: {}

zgbg7  {"level":"info","ts":1638592012.576219,"logger":"tls.issuance.acme.acme_client","msg":"validations succeeded; finalizing order","order":"https://acme.zerossl.com/v2/DV90/order/ffWXMggggBvidzVGR7LjZw"}
zgbg7  {"level":"error","ts":1638592037.9796464,"logger":"docker-proxy","msg":"Failed to read Caddyfile","path":"/etc/caddy/Caddyfile","error":"open /etc/caddy/Caddyfile: no such file or directory"}

**Comment by francislavoie** [comment]
Please use code blocks when posting configs and logs. All formatting is lost unless you do so, which makes it much harder to read your post and help you.

I don't think you actually mounted the Caddyfile, I don't see any paths in your `volume` config that would make a Caddyfile exist in the container at `/etc/caddy/Caddyfile`.

**Comment by francislavoie** [comment]
Closing as inactive
