### ISSUE TITLE
Consider release with plugins built-in?

### ISSUE THREAD

**Issue by zilexa** [lucaslorentz/caddy-docker-proxy#324]
Would you consider building in popular plugins such as Cloudflare? And caddy-auth-jwt, caddy-auth-portal? Especially Cloudflare, is there a reason why you would not want to include this plugin by default?

**Comment by francislavoie** [comment]
It's trivial to write your own Caddyfile with the plugins you need. It's not worth the effort to "make guesses" at a set of plugins everyone would use.

See the README, there's instructions on how to write your own Dockerfile using xcaddy to make a build with the plugins you need.

**Comment by zilexa** [comment]
That's based on the assumption people know about dockerfiles at all. I only use Docker Compose. Lots of home users that are not developers (for whom you are absolutely right) and just run a basic compose file to protect a few selfhosted solutions such as a file server and password manager.

**Comment by francislavoie** [comment]
If you're using CDP, there's a certain expectation of understanding how Docker works. I would definitely not call this a tool for beginners.

It's trivial to build from a Dockerfile when using docker-compose. Even easier than if you were just using Docker commands directly.
