### ISSUE TITLE
whitelist ip

### ISSUE THREAD

**Issue by mihsergeev** [lucaslorentz/caddy-docker-proxy#325]
Please, give example (labels) to deny all requests from all ip and allow only from mine

**Comment by francislavoie** [comment]
You'll need to define a named matcher which contains a `remote_ip` matcher: https://caddyserver.com/docs/caddyfile/matchers

Then use that matcher with either the `respond` or `abort` directive to deny access: https://caddyserver.com/docs/caddyfile/directives/abort

Check the README of this plugin to understand how to define the labels for this.

**Comment by mihsergeev** [comment]
tried different ways, but doesn't work
help me create a label that blocks all addresses 0.0.0.0/0 and allows only 192.168.0.5 and 192.168.0.10

**Comment by hycday** [comment]
wouldn't it be something like ?


> remote_ip 192.168.0.5 192.168.0.10
@denied not remote_ip private_ranges
abort @denied

which for this plugin would convert to the below : (to be confirmed)

> labels: 
    caddy.@remote_ip: "192.168.0.5 192.168.0.10"
    caddy.@denied.not: remote_ip private_ranges
    caddy.abort: @denied

**Comment by francislavoie** [comment]
You'll have to use the https://github.com/porech/caddy-maxmind-geolocation plugin to use the GeoIP databases. See the README for details on how to build to additional plugins.

I'll close this issue, I'm not seeing anything left to answer.

**Comment by mihsergeev** [comment]
> > labels:
> > caddy.@remote_ip: "remote_ip 192.168.0.5 192.168.0.10"
> > [caddy.@denied.not](mailto:caddy.@denied.not): remote_ip private_ranges
> > caddy.abort: @denied

not working

yaml: line 16: found character that cannot start any token

if use :
`caddy.abort: "@denied"
`
got error:

caddy-proxy-caddy-1  | {"level":"info","ts":1656865901.0069337,"logger":"docker-proxy","msg":"Process Caddyfile","logs":"[ERROR]  Removing invalid block: Caddyfile:2: unrecognized global option: @denied\n{\n\t@denied {\n\t\tnot remote_ip private_ranges\n\t}\n\t@remote_ip remote_ip 192.168.0.5 192.168.0.10\n\tabort @denied\n}\n\n"}

**Comment by francislavoie** [comment]
You must define a site block with a domain name before any matchers or directives.

Please see the Caddyfile Concepts page in the official docs.

**Comment by RenatoXSR** [comment]
Actually, beginning a token with @ is [reserved in YAML specs](https://yaml.org/spec/1.2.2/#rule-c-directive), so we may need to find an alternate character and alter it during isMatcher check in  [caddyfile/merge.go`](https://github.com/lucaslorentz/caddy-docker-proxy/blob/master/caddyfile/merge.go#L40)

Is there any suggestions? % is also reserved. Maybe x40?

Reserved characters: `-`, `?`, `:`, `,`, `[`, `]`, `{`, `}`, `#`, `&`, `*`, `!`, `|`, `>`, `'`, `"`, `%`, `@` and `.

**Comment by mihsergeev** [comment]
This solution works fine for the whole site, but what should I add here to close only a certain url for example, 
for example
 - / - for all
 - /admin - from whithlist ip


```
caddy.@denied.not: "remote_ip 192.168.0.5 192.168.0.10"
caddy.abort: "@denied"
caddy: domain.com
caddy.reverse_proxy: "{{upstreams http 9000}}"

```

?

**Comment by hycday** [comment]
how about `$` ? 
also, still unsure about how final "code" for caddy-docker-proxy would look like
