### ISSUE TITLE
Hard to read Caddyfile generated in CDP v2.4.0

### ISSUE THREAD

**Issue by kidcuauh** [lucaslorentz/caddy-docker-proxy#327]
In version 2.3.5 Caddyfile generated was easier to read but in 2.4.0 output is ignoring \n \t
I activated format console logs but isn't helping on the Caddyfile generated log block. Is there any way to fix the output and make it readable?
Thank you in advance.

**Comment by francislavoie** [comment]
Duplicate of https://github.com/lucaslorentz/caddy-docker-proxy/issues/276
