### ISSUE TITLE
tls-insecure-skip-verify

### ISSUE THREAD

**Issue by arminliensberger** [lucaslorentz/caddy-docker-proxy#329]
Hi,
I want to enable unifi via Caddy proxy with the standard URL https://<ip>:8443
Unfortunately, the certificate is not signed and therefore throws a warning.
Caddy seems to check the certificate and denies access when not signed.

Solution would be to add the tls-insecure-skip-verify option.. how can I do that in docker-compose?
Something similar to https://caddy.community/t/the-equivalent-tls-insecure-skip-verify-in-reverse-proxy/7456 but was not able to create the configuration in docker compose....

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
