### ISSUE TITLE
Caddy version ends up in generated Caddyfile

### ISSUE THREAD

**Issue by dhaavi** [lucaslorentz/caddy-docker-proxy#33]
I am having a pretty weird issue: The caddy version ends up in the generated config and breaks it.

This only happens when reloaded, not with the Caddyfile generated on startup.
Also, the version ends up either in the beginning or between the container and service section (one line before `service-1.example.com`).
This also happens when only the services are loaded.

I have been using the docker container provided by this repo in the past but have switched to building the image with this command: `docker build --build-arg plugins=docker,cloudflare github.com/abiosoft/caddy-docker.git`.

The issue arised with the newly built container, but as this plugin prints the version within the config file, I would guess that something is wrong here. I checked the source code but could not find any clues to why this is happending.

It did work one time in between, but after lots of restarting containers and services, I was unable to reach that state again. This is really weird.

Here is the log:

```
2018/05/07 10:42:40 [INFO] New CaddyFile:
container.example.com {
  import /caddy/Caddy_common_headers
  log / /caddylogs/container.example.com {combined}
  proxy / 172.17.0.1:8080
  tls {
    clients /caddy/clientCA.crt
  }
}
*.container.example.com {
  import /caddy/Caddy_common_headers
  log / /caddylogs/sub_container.example.com {combined}
  proxy / 172.17.0.1:8080
  tls {
    clients /caddy/clientCA.crt
    dns cloudflare
  }
}
service-1.example.com {
  import /caddy/Caddy_common_tlsclientauth
  log / /caddylogs/service-1.example.com {combined}
  proxy / service-1:8080
}
service-2.example.com {
  import /caddy/Caddy_common_tlsclientauth
  log / /caddylogs/service-2.example.com {combined}
  proxy / service-2:8080
}
service-3.example.com {
  import /caddy/Caddy_common_tlsclientauth
  log / /caddylogs/service-3.example.com {combined}
  proxy / service-3:8080
}
Activating privacy features... done.
https://container.example.com
2018/05/07 10:42:40 https://container.example.com
https://*.container.example.com
2018/05/07 10:42:40 https://*.container.example.com
https://service-1.example.com
2018/05/07 10:42:40 https://service-1.example.com
https://service-2.example.com
2018/05/07 10:42:40 https://service-2.example.com
https://service-3.example.com
2018/05/07 10:42:40 https://service-3.example.com
http://container.example.com
2018/05/07 10:42:40 http://container.example.com
http://*.container.example.com
2018/05/07 10:42:40 http://*.container.example.com
http://service-1.example.com
2018/05/07 10:42:40 http://service-1.example.com
http://service-2.example.com
2018/05/07 10:42:40 http://service-2.example.com
http://service-3.example.com
2018/05/07 10:42:40 http://service-3.example.com
2018/05/07 10:42:40 [INFO] New CaddyFile:
0.10.14
container.example.com {
  import /caddy/Caddy_common_headers
  log / /caddylogs/container.example.com {combined}
  proxy / 172.17.0.1:8080
  tls {
    clients /caddy/clientCA.crt
  }
}
*.container.example.com {
  import /caddy/Caddy_common_headers
  log / /caddylogs/sub_container.example.com {combined}
  proxy / 172.17.0.1:8080
  tls {
    clients /caddy/clientCA.crt
    dns cloudflare
  }
}
service-1.example.com {
  import /caddy/Caddy_common_tlsclientauth
  log / /caddylogs/service-1.example.com {combined}
  proxy / service-1:8080
}
service-2.example.com {
  import /caddy/Caddy_common_tlsclientauth
  log / /caddylogs/service-2.example.com {combined}
  proxy / service-2:8080
}
service-3.example.com {
  import /caddy/Caddy_common_tlsclientauth
  log / /caddylogs/service-3.example.com {combined}
  proxy / service-3:8080
}
2018/05/07 10:42:40 [INFO] SIGUSR1: Reloading
2018/05/07 10:42:40 [INFO] Reloading
2018/05/07 10:42:40 [ERROR] SIGUSR1: :2 - Error during parsing: Unknown directive 'container.example.com'
```

**Comment by lucaslorentz** [comment]
That's very unexpected. I don't know where that version is coming from.
Maybe it was just logged concurrently with the caddyfile, but it is not inside the generated caddyfile.

**Comment by dhaavi** [comment]
Hey @lucaslorentz,

The [Dockerfile](https://github.com/abiosoft/caddy-docker) used to build the image has defined a label:
```
ARG version="0.11.0"
LABEL caddy_version="$version"
```
Would that end up in the generated Caddyfile?
The Readme only mentions `_#` with the example of `caddy_0.address = ...`.

Dockerfile: https://github.com/abiosoft/caddy-docker/blob/bf96368d6217435424d42283fe940880e9ecd575/Dockerfile#L21

**Comment by lucaslorentz** [comment]
I was expecting some labels on container or service, not on docker image.
I don't think image labels goes to container label, I will check that later.

**Comment by lucaslorentz** [comment]
@dhaavi 
Can you please try building your image again?
I tried and the fix above seems good.
