### ISSUE TITLE
Proxy doesn't work in a LAN setup

### ISSUE THREAD

**Issue by vahidreza** [lucaslorentz/caddy-docker-proxy#331]
hi.
I have a corporate internal lan setup for our systems on docker and im trying to setup caddy to act as a reverse proxy for our other container services but it seems not working. the ssl doesn't work and im stuck. i appreciate any help that you can provide.

im trying to reach out to data.local and be able to load server-ip:8088 in exchange.
my local dns is set to point data.local to the server's ip address.

below is the docker-compose files im using:

to setup caddy proxy server:

```version: "3.7"
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped

networks:
  caddy:
    external: true

volumes:
  caddy_data: {}
```

and  my directus installation:

```version: "3"

services:
  directus:
    image: directus/directus:9.4.3
    ports:
      - "8088:8055"
    container_name: directus
    environment:
      KEY: "key"
      SECRET: "secret"
      ADMIN_EMAIL: "test@example.com"
      ADMIN_PASSWORD: "password!@#$%^1"
    volumes:
      - /home/appilux/directus-volume/directus-uploads:/directus/uploads 
      - /home/appilux/directus-volume/directus-extensions:/directus/extensions    
    networks:
      - caddy
    labels:
      caddy: data.local
      caddy.reverse_proxy: "{{upstreams 8088}}"
  
networks:
  caddy:
    external: true`
```

trying to load the url i get below error inside of caddy container logs:

`
{"level":"error","ts":1641818583.5727282,"logger":"http.log.error","msg":"dial tcp 172.21.0.3:8088: connect: connection refused","request":{"remote_addr":"192.168.114.76:57243","proto":"HTTP/2.0","method":"GET","host":"data.local","uri":"/","headers":{"Accept-Encoding":["gzip, deflate, br"],"Accept-Language":["en-US,en;q=0.9"],"Cache-Control":["max-age=0"],"Sec-Ch-Ua":["\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"96\", \"Google Chrome\";v=\"96\""],"Sec-Ch-Ua-Mobile":["?0"],"Sec-Fetch-Site":["cross-site"],"Sec-Fetch-Mode":["navigate"],"Sec-Fetch-User":["?1"],"Sec-Ch-Ua-Platform":["\"macOS\""],"Upgrade-Insecure-Requests":["1"],"User-Agent":["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36"],"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"],"Sec-Fetch-Dest":["document"]},"tls":{"resumed":false,"version":772,"cipher_suite":4865,"proto":"h2","proto_mutual":true,"server_name":"data.local"}},"duration":0.000861498,"status":502,"err_id":"wj33y9h6p","err_trace":"reverseproxy.statusError (reverseproxy.go:886)"}
`

and upon having the container up and running for the first time ive got some other logs stating some problems including below:

`
{"level":"warn","ts":1641817917.8870997,"logger":"tls","msg":"stapling OCSP","error":"no OCSP stapling for [data.local]: no OCSP server specified in certificate"}`

**Comment by francislavoie** [comment]
You have to proxy to the port internal to the Docker network, not the port you bound to the host. Use `8055` instead for the proxy.

**Comment by vahidreza** [comment]
tnx for the update. yeah it works now.a quick question though.
how is it possible to setup the proxy for already running containers?
also in production there might be cases where we have to promptly switch from one instance to another due to maintenance and it should be done somewhere inside of the caddy conf files.

**Comment by francislavoie** [comment]
I don't think that's possible, you have to restart the containers for label changes to take effect.

**Comment by vahidreza** [comment]
there is no issue restarting the container. the problem is passing the config labels.
lets say i have a wordpress container with lots of manual setups inside of it and i cannot simply have it up and running again using docker compose. 
is there anyway i can bind it to caddy proxy? first step is to join it to caddy network which i did. im confused about the rest.

**Comment by francislavoie** [comment]
There's no way to add labels to a running container, which is necessary for CDP to pick it up and auto-configure.

What you should do is write a Dockerfile with all those manual steps you ran inside the container, so it's automated and can be redone automatically. It's an anti-pattern to manually run commands inside of a container other than just debugging and such.

Your only other option is to provide a Caddyfile path env var to CDP with static config that it would use as a base (and merge config from labels into).
