### ISSUE TITLE
Update packaged containerd

### ISSUE THREAD

**Issue by liberianbarcode** [lucaslorentz/caddy-docker-proxy#332]
Packaged containerd is v1.5.7, should be updated to 1.5.9 - See CVE: [GHSA-mvff-h3cj-wj9c](https://github.com/containerd/containerd/security/advisories/GHSA-mvff-h3cj-wj9c)

**Comment by lucaslorentz** [comment]
Fixed by https://github.com/lucaslorentz/caddy-docker-proxy/pull/219
