### ISSUE TITLE
disable TLS in docker-compose

### ISSUE THREAD

**Issue by vahidreza** [lucaslorentz/caddy-docker-proxy#339]
is there any way that instead of internal for self signed certificated in a LAN setup i totally disable it so when fetching the internal LAN url (e.g. app.local) it doesn't redirect to https:// and i can fetch it normally using http:// ?

currently in my docker-compose.yml i have `caddy.tls:"internal"`

**Comment by francislavoie** [comment]
Use the `http://` prefix for your site address

https://caddyserver.com/docs/caddyfile/concepts#addresses

**Comment by vahidreza** [comment]
this is part of my docker-compose file and i dont have a valid url here, can you elaborate a little bit?

`scanner:
    container_name: scanner_app
    image: flutter_scanner_app_build
    restart: always
    depends_on:
      - middleware
    networks:
      - caddy
    ports:
      - 8082:5070
    labels:
        caddy: scanner.web
        caddy.reverse_proxy: "{{upstreams 5070}}"
        caddy.tls: "internal"
        caddy.auto_https: "off"`

**Comment by francislavoie** [comment]
Instead of `caddy: scanner.web`, do `caddy: http://scanner.web`

**Comment by vahidreza** [comment]
@francislavoie  awesome, it did the job. tnx
