### ISSUE TITLE
Support of delete header

### ISSUE THREAD

**Issue by StelFux** [lucaslorentz/caddy-docker-proxy#340]
I have been looking for a solution to write the equivalent configuration of caddyfile with label, but I can't find it.
```
header / {
    -Server
}
```
Is there a solution for this or could you add it?

**Comment by IndeedNotJames** [comment]
I believe this falls under the following example from the [README.md#tokens-and-arguments](https://github.com/lucaslorentz/caddy-docker-proxy/blob/master/README.md#tokens-and-arguments) ([permalink](https://github.com/lucaslorentz/caddy-docker-proxy/blob/4905e9cee02673b6ba7b4a12fc8f53758d8810a5/README.md#tokens-and-arguments)):

```Caddyfile
caddy.directive.subdirA: valueA
↓
{
	directive {
		subdirA valueA
	}
}
```

Thus, your labels would need to look somewhat similar to:
```yaml
labels:
  # [...]
  caddy.header: /
  caddy.header.-Server: ""
```
Which results in:
```Caddyfile
header / {
	-Server
}

```

**Comment by francislavoie** [comment]
Worth mentioning, you probably don't want the `/` matcher here, because that will _only_ match `/` and nothing else.

You can probably simplify it to either of these:

```
caddy.header.-Server: ""
```

or

```
caddy.header: "-Server"
```
