### ISSUE TITLE
Label support for Layer 4

### ISSUE THREAD

**Issue by DevPGSV** [lucaslorentz/caddy-docker-proxy#342]
I'd like to request a label syntax to allow other apps (besides `http`) to be configured.

As far as I know, right now it is not possible to use labels to setup configuration in caddy apps like `layer4`.

Layer 4 module repository:
https://github.com/mholt/caddy-l4

**Comment by francislavoie** [comment]
CDP is designed to generate Caddyfile config. Caddy-l4 doesn't support Caddyfile yet. See https://github.com/mholt/caddy-l4/issues/16.

There are no plans to make CDP generate JSON config directly from labels. It would essentially be a completely separate project at that point.

**Comment by KiARC** [comment]
Caddy-l4 now supports Caddyfile!
