### ISSUE TITLE
question: running containers reverse proxy configs are lost upon caddy reload 

### ISSUE THREAD

**Issue by teodorescuserban** [lucaslorentz/caddy-docker-proxy#344]
I am trying to use cadd-docker-proxy as container. If caddy gets reloaded (`caddy reload`), the configuration related to the docker containers running already does not get into caddy config again unless I am restarting those containers or the caddy container. 

Did I missed anything? I did looked at `polling-interval`. Probably this feature is missing as there is no actual need for a `caddy reload` since the `Caddyfile` is polling periodically?

Thank you.

**Comment by teodorescuserban** [comment]
It looks like while the `Caddyfile` does get refreshed when changed, any included files are not. Which means that any change you make in a file used in the main caddy config file will need to be applied by either restarting the containers using whatever is in that file or restart the main caddy container.

**Comment by lucaslorentz** [comment]
Can you please describe a bit your setup?
So you have 1 caddy controller, and many caddy servers?
And are you saying that when one caddy-server is restarted, the controller is not pushing caddy configuration to it again?
Not even after the 30s configured for polling?

If that's the case, I think this is the culprit: https://github.com/lucaslorentz/caddy-docker-proxy/blob/master/plugin/loader.go#L277
The controller doesn't send the config again to the restarted node because it thinks it already has the latest version of Caddyfile.

**Comment by teodorescuserban** [comment]
@lucaslorentz, I am sorry for not being more specific.
I am using a single caddy container in a standalone mode (the default).
And if I do a `docker exec -it caddy caddy reload`, the config coming from docker-proxy plugin is gone and is not being generated again unless i restart the whole caddy container.

**Comment by francislavoie** [comment]
The `caddy reload` command isn't managed by docker-proxy, and I don't think there's any way to make that work.

What exactly are you trying to do by reloading?

I think `docker-proxy` would have to provide a `docker-proxy-reload` command or something to do what you want.

**Comment by teodorescuserban** [comment]
Unfortunately there is no `docker-proxy-reload` command.
But yeah, I guess I just went through the motion simply following the usual caddy mo. Waiting for polling is not good enough, as it appears to not pickup the changes in the imported files in caddy. However, restarting one of the containers with labels seem to work.
No need to use `caddy reload` when I can easily use `docker-compose restart caddy` in my simple, single standalone instance. It takes almost no time and it does force the whole config to get updated. Works for me well enough, so probably not worth implementing the `docker-proxy-reload` thing. :)
I think this issue can be closed.
Thank you for inputs!
