### ISSUE TITLE
This site cannot provide a secure connection

### ISSUE THREAD

**Issue by dbelyaeff** [lucaslorentz/caddy-docker-proxy#349]
Hi!

I'm using standart configuration. But when I'm reloading related containers on docker-compose, caddy stops to serve them, given in browser response "This site cannot provide a secure connection" with code ERR_SSL_PROTOCOL_ERROR.

It's needed to docker compose restart caddy-proxy to make it works again.

**Comment by francislavoie** [comment]
That's not enough information to help. You'll need to give way more details.
