### ISSUE TITLE
New version release

### ISSUE THREAD

**Issue by jonatasbaldin** [lucaslorentz/caddy-docker-proxy#353]
Hi there, when is it expected to get a new version release?

Thanks!

**Comment by lucaslorentz** [comment]
Hey @jonatasbaldin
I'm updating all packages and switching to multi-arch docker images here:
https://github.com/lucaslorentz/caddy-docker-proxy/pull/219
I will release another version after I finish that.

**Comment by jonatasbaldin** [comment]
Thanks!

**Comment by lucaslorentz** [comment]
Check out https://github.com/lucaslorentz/caddy-docker-proxy/releases/tag/v2.5.0
