### ISSUE TITLE
HTTP ERROR 502 - CDP hangs and did not update the ip of the container/service deployed

### ISSUE THREAD

**Issue by kidcuauh** [lucaslorentz/caddy-docker-proxy#355]
CDP v2.5.0

I've been living with this issue since I update to CDP with Caddy v1 -> v2.
To fix this issue I have to restart CDP, but updating constantly that way leaves my mobile, webapp users who consume the API without service a couple of seconds. Also, new standalone containers/services deployed on a CDP hanged fail to update the ip.

When I say that caddy hangs I refer to when CDP shows the Caddyfile config and JSON config but fails to show the following output after a container/service update:

```
{"level":"info","ts":1650908569.1053853,"logger":"docker-proxy","msg":"Sending configuration to","server":"localhost"}
{"level":"info","ts":1650908569.1068215,"logger":"admin.api","msg":"received request","method":"POST","host":"localhost:2019","uri":"/load","remote_addr":"127.0.0.1:55602","headers":{"Accept-Encoding":["gzip"],"Content-Length":["22946"],"Content-Type":["application/json"],"User-Agent":["Go-http-client/1.1"]}}
{"level":"info","ts":1650908569.1158822,"logger":"admin","msg":"admin endpoint started","address":"tcp/localhost:2019","enforce_origin":false,"origins":["[::1]:2019","127.0.0.1:2019","localhost:2019"]}
{"level":"info","ts":1650908569.116735,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc0003fc620"}
{"level":"info","ts":1650908569.1171227,"logger":"http","msg":"server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS","server_name":"srv0","https_port":443}
{"level":"info","ts":1650908569.11731,"logger":"http","msg":"enabling automatic HTTP->HTTPS redirects","server_name":"srv0"}
{"level":"info","ts":1650908569.1174448,"logger":"http","msg":"server is listening only on the HTTP port, so no automatic HTTPS will be applied to this server","server_name":"srv1","http_port":80}
{"level":"warn","ts":1650908570.6248488,"logger":"tls","msg":"YOUR SERVER MAY BE VULNERABLE TO ABUSE: on-demand TLS is enabled, but no protections are in place","docs":"https://caddyserver.com/docs/automatic-https#on-demand-tls"}
{"level":"info","ts":1650908570.6249166,"logger":"http","msg":"enabling automatic TLS certificate management","domains":["www.exampledomain.com","example.domain.com","domain.com"]}
{"level":"error","ts":1650908579.1171393,"logger":"admin","msg":"stopping current admin endpoint","error":"shutting down admin server: context deadline exceeded"}
```

When CDP is hanged, the log throws the following error when I test the container/service deployed:

```
{"level":"error","ts":1650909603.8743248,"logger":"http.log.error","msg":"dial tcp 10.0.3.252:3000: connect: no route to host","request":{"remote_addr":"10.0.0.2:9551","proto":"HTTP/1.1","method":"GET","host":"exampleofadomain.com","uri":"/","headers":{"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"],"Accept-Encoding":["gzip, deflate"],"Cookie":["_fbp=fb.1.1650329085053.857068612; utms=null; _ga=GA1.2.435451920.1650329086; _ga_K88KGRHNYK=GS1.1.1650462733.3.0.1650462735.0"],"Accept-Language":["es-ES,es;q=0.9,en;q=0.8"],"Connection":["keep-alive"],"Pragma":["no-cache"],"Cache-Control":["no-cache"],"Upgrade-Insecure-Requests":["1"],"User-Agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"],"Sec-Gpc":["1"]}},"duration":3.078424945,"status":502,"err_id":"btvzhc4h0","err_trace":"reverseproxy.statusError (reverseproxy.go:886)"}
```

I reviewed all my caddy labels configured many times and also been monitoring this issue to understand what could break my CDP updating ip container/service but I haven't found the answer yet. Please let me know if you have lived/heard about this issue or if I can help you to test anything.

**Comment by francislavoie** [comment]
Are any of your apps using websockets? If so, you might need to configure the `grace_period` global option to force Caddy to close all connections after a certain amount of time https://caddyserver.com/docs/caddyfile/options#grace-period. Caddy isn't able to gracefully close websocket connections currently (it's kinda unclear how that would work).

**Comment by kidcuauh** [comment]
Hi @francislavoie thanks for your kind reply. I am not using websockets at the moment. It is a nodejs/express API with 3 replicas, however the error could be randomly triggered by updating a container with a simple landing page made with Nuxt SSR (Server Side Rendering), Vue 2 web app or even a pure html/css webpage container packaged with a Caddy. Worth to mention is that after some random time (it could be 10mins o 3 hours, however I have never wait longer especially when a productive API is deployed for obvious reasons) CDP responds to the update and end up correctly configured.

**Comment by kidcuauh** [comment]
I have been testing `grace_period` on Caddyfile but the problem is still showing up, however, I don't know if it is helping to prevent CDP hang and now it is showing all the output normally but still failing to update the ip. The time to automatically get fixed is random. Today one Standalone container took around 10 minutes to update the ip and the log did not show any hint about this issue.
I looked for how to implement the health check but I did not understand it.

Below you can find my whole configurations:

**CDP Caddyfile:**

```
{
	email	email@mydomain.com
	grace_period	15s
}
```

Standalone Container labels:

```
LABEL caddy_0="miurl.com, sub.miurl.com"
LABEL caddy_0.reverse_proxy="{{upstreams 3000}}"
LABEL caddy_0.tls="email@mydomain.com"
LABEL caddy_0.tls.on_demand=
LABEL caddy_0.header.Strict-Transport-Security="max-age=31536000"
LABEL caddy_0.header.Cache-Control="public, max-age=604800"
LABEL caddy_0.header.X-XSS-Protection="1; mode=block"
LABEL caddy_0.header.X-Content-Type-Options="nosniff"
LABEL caddy_0.header.X-Frame-Options="DENY"
LABEL caddy_1="www.miurl.com" caddy_1.redir="https://miurl.com"
LABEL caddy_1.tls="email@mydomain.com"
LABEL caddy_1.tls.on_demand=
```

or basic http for develop sites:

```
LABEL caddy_0="http://miurl, http://sub.miurl"
LABEL caddy_0.reverse_proxy="{{upstreams portdev}}"
```

Standalone Container deploy script:

```
#!/bin/sh
docker pull registry.gitlab.com/org/app-123:main
docker container stop app-123 || true
sleep 5s
docker container rm app-123 || true
sleep 5s

docker run -d \
  --restart always \
  --name app-123 \
  --net nuxt-sites \
  registry.gitlab.com/org/app-123:main
```

Service labels:

```
deploy:
      labels:
        caddy_0: api.mydomain.com
        caddy_0.handle_path: "/v2/*"
        caddy_0.handle_path.0_reverse_proxy: "{{upstreams 8090}}"
        caddy_0.handle_path.0_reverse_proxy.0_header_up: "API-Version v2"
        caddy_0.handle_path.0_reverse_proxy.1_header_up: "environment production"
        caddy_0.tls: "email@mydomain.com"
        caddy_0.tls.on_demand:
```

Service deploy script:

```
#!/bin/sh
docker pull registry.gitlab.com/org/api-express:v2-master && docker stack deploy --with-registry-auth -c api-express-v2-master.yaml api-express-v2-master
```

**Comment by kidcuauh** [comment]
It is very strange that this issue is not actively being commented on by someone else in a big and important project like Caddy. Also, I don't think I am handling a crazy config. In the beginning, I thought the problem was with my labels I have inspected my containers multiple times on the label section in order to see that everything is in place correctly. I have carried this problem for months, and today I looked at the Caddy marketing core being promoted as `Automatic HTTPS` probably no one really cares to go back to HTTP. If my gut is not wrong, the problem is being triggered when Caddy switches between HTTP and HTTPS and something happens in the middle...

**Comment by francislavoie** [comment]
It's been a week. We have lives and dayjobs. This is an open source project that you're using for free. That kind of attitude is not welcome. It makes me less willing to actually spend the time to help you.

Also, this project is not an official Caddy tool, it's something graciously maintained by @lucaslorentz.

**Comment by francislavoie** [comment]
Apology accepted @kidcuauh, thanks for understanding.

I'll circle back to this when I can spend a bit more time thinking about it, but I think @lucaslorentz might be able to figure it out quicker when he himself has time to look. It's not immediately obvious to me what's going wrong.

You can try querying the config API (by default listening on `localhost:2019` inside the caddy container, see https://caddyserver.com/docs/api) while the config is reloading to check what the current config is.

As an aside, I spotted this: `LABEL caddy_0.tls.on_demand=` definitely remove that. You should only use `on_demand` in a few particular situations, i.e. when you _don't_ know the domains ahead of time. If you _do_ know the domains and configured them, then it makes no sense to use `on_demand`. https://caddyserver.com/docs/automatic-https#on-demand-tls

**Comment by lucaslorentz** [comment]
@kidcuauh 
To be honest it is not obvious to me as well what is going wrong.

If possible, try to prepare some steps to reproduce the issue:
- docker-compose file to create the containers
- instructions on which container to restart and commands to run

I agree with what @francislavoie said about on_demand.

But from the error messages `dial tcp 10.0.3.252:3000: connect: no route to host` and `reverseproxy.statusError (reverseproxy.go:886)`, I believe the error is happening after the TLS connection is handled. 

I've faced network and unreachable container issues before in Docker swarm.
I've solved it by running multiple replicas of the container and configuring the health check as I mentioned above.
That way any network instability is compensated by another good container.

The health check can be configured as instructed at https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#active-health-checks

Labels for health check would be:
```
LABEL caddy_0.reverse_proxy. health_uri="/your_application_health_check_endpoint"
```
Your_application_health_check_endpoint is any endpoint in your container that is very lightweight and returns a successful HTTP status code.

**Comment by lucaslorentz** [comment]
@kidcuauh 
I also wonder if caddy had the most recent IP of your container. From your logs, it tried to reach 10.0.3.252, but maybe the container had a different IP address.
If you're able to consistently reproduce the issue, it would be nice to check that.

**Comment by francislavoie** [comment]
You could also play with `lb_try_duration` to have Caddy retry connecting to upstreams if you have more than one
