### ISSUE TITLE
Version Determination

### ISSUE THREAD

**Issue by samcro1967** [lucaslorentz/caddy-docker-proxy#365]
Looking for a way to determine the current version of caddy-docker-proxy in the running image.  It is not listed in `docker exec -it caddy /bin/sh -c "caddy list-modules -versions`.  I also looked for it in the logs, but not seeing it anywhere either.

Anyone know of a way to do this?

**Comment by francislavoie** [comment]
I think `caddy build-info` will show it

**Comment by samcro1967** [comment]
That works.  Thank you!
