### ISSUE TITLE
Xcaddy not pulling 2.6.0

### ISSUE THREAD

**Issue by samcro1967** [lucaslorentz/caddy-docker-proxy#366]
Currently not able to build a new caddy image and pull down v2.6.0.  Image alwasy ends up with 2.0.0.

`docker exec -it caddy /bin/sh -c 'caddy build-info | grep proxy'`
```
github.com/lucaslorentz/caddy-docker-proxy/plugin/v2 v2.0.0-20211030110928-6ec85e1d3732 h1:w28Q1e39fnrDBi+68t5WOUaX/bUL9Kv6kBa4l0xKY0U=
```

**Dockerfile**
```
ARG CADDY_VERSION=2.5.1

FROM caddy:${CADDY_VERSION}-builder AS builder
#FROM caddy:builder AS builder

RUN xcaddy build \
    --with github.com/lucaslorentz/caddy-docker-proxy/plugin/v2 \
    --with github.com/greenpau/caddy-security \
    --with github.com/greenpau/caddy-trace \
    --with github.com/porech/caddy-maxmind-geolocation \
    --with github.com/caddy-dns/cloudflare \
    --with github.com/kirsch33/realip

FROM caddy:${CADDY_VERSION}-alpine
#FROM caddy:builder-alpine

RUN apk add --no-cache tzdata

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

CMD ["caddy", "docker-proxy"]
```

**Comment by francislavoie** [comment]
Please try reducing the plugins you're installing to the bare minimum. It's possible that one of the other plugins is causing some weirdness with the build.

**Comment by samcro1967** [comment]
I removed all plugins except caddy-docker-proxy and it still downloaded version 2.0.0.

**Comment by samcro1967** [comment]
Showing 2 different versions after remove the `/v2`, neither 2.6.0.

```
[0m[91mgo: downloading github.com/lucaslorentz/caddy-docker-proxy/plugin v0.0.0-20220509232726-e1d70e75bffd
[0m[91mgo: downloading github.com/lucaslorentz/caddy-docker-proxy v0.3.6
```

**Comment by lucaslorentz** [comment]
@samcro1967 I would expect the same to happen to all other plugins as well.
Even if the other plugins have a released version, you're probably getting a generated version number for them as well. 
Please, let me know if that's not the case, maybe there is something we're not doing in caddy-docker-proxy.

**Comment by samcro1967** [comment]
Adding `@v2.6.0` generated a different error message.

```
go: downloading github.com/lucaslorentz/caddy-docker-proxy v2.6.0+incompatible
go: module github.com/lucaslorentz/caddy-docker-proxy@v2.6.0 found (v2.6.0+incompatible), but does not contain package github.com/lucaslorentz/caddy-docker-proxy/plugin/v2
2022/05/18 22:52:22 [FATAL] exit status 1
The command '/bin/sh -c xcaddy build     --with github.com/lucaslorentz/caddy-docker-proxy/plugin@v2.6.0     --with github.com/greenpau/caddy-security     --with github.com/greenpau/caddy-trace     --with github.com/porech/caddy-maxmind-geolocation     --with github.com/caddy-dns/cloudflare     --with github.com/kirsch33/realip' returned a non-zero code: 1
exit status 1
[0m
```

I setup monitoring today for Caddy modules so I have visibility to the currently installed version and the latest version available.  `caddy-security` and `caddy-trace` both seem to work fine in Dockerfile with no version specified.  I always get the latest available when a new build occurs and the version number listed locally matches the version number on the repo.  I suspect once the realip repo is updated it will report correctly also.  Previous to version 2.x it reported locally the latest version matching its repo also.

**Comment by lucaslorentz** [comment]
I realized now that the version behavior depends on the state of master branch, if master branch head is still a commit that was tagged and released, you will see the released version number. Otherwise, go module will generate a new version number to represent that unreleased version/commit.

That means it can happen to any other plugin as well if they add more commits to master.

I'm investigating the error to build with v2.6.0.

**Comment by lucaslorentz** [comment]
Had to reorganize the modules.
This works now:
```
ARG CADDY_VERSION=2.5.1

FROM caddy:${CADDY_VERSION}-builder AS builder
#FROM caddy:builder AS builder

RUN xcaddy build \
    --with github.com/lucaslorentz/caddy-docker-proxy/v2@v2.7.0 \
    --with github.com/greenpau/caddy-security \
    --with github.com/greenpau/caddy-trace \
    --with github.com/porech/caddy-maxmind-geolocation \
    --with github.com/caddy-dns/cloudflare \
    --with github.com/kirsch33/realip

FROM caddy:${CADDY_VERSION}-alpine
#FROM caddy:builder-alpine

RUN apk add --no-cache tzdata

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

CMD ["caddy", "docker-proxy"]
```

**Comment by samcro1967** [comment]
@lucaslorentz Thanks for your help.  Working as expected with '--with github.com/lucaslorentz/caddy-docker-proxy/v2'.
