### ISSUE TITLE
How to inspect the generated caddy file inside a docker container

### ISSUE THREAD

**Issue by Cooke** [lucaslorentz/caddy-docker-proxy#37]
Hi,

I have succussfully setup the proxy towards whoami services, however when I add myown service running http on port 5000 everything fails, the proxy isn't even responding. 

How can I inspect the generated configuration inside the container? I have tried with docker logs without seeing anything useful. Thanks in advance.

**Comment by Cooke** [comment]
The ACME process for one of the domains was in a broken state. After I removed a lock-file everything started working, giving me output in the docker logs.

**Comment by lucaslorentz** [comment]
I would say you was missing `-log stdout`.

But that's not the reason. Glad that you found the issue.
