### ISSUE TITLE
curl missing in 2.7.0-alpine image

### ISSUE THREAD

**Issue by arminus** [lucaslorentz/caddy-docker-proxy#372]
We've used the ci-alpine images so far with a curl based healthcheck.

For stability, I wanted to switch to 2.7.0-alpine, but as it turns out that images doesn't have curl, although, if I understand https://github.com/lucaslorentz/caddy-docker-proxy#chosing-between-default-or-alpine-images well, it should have?

**Comment by arminus** [comment]
In this case the text I linked above is very misleading: "Our default images are very small and safe because they only contain Caddy executable ... they don't have shell or any other Linux utilities like curl or dig. ... The alpine images variant are based on the Linux Alpine image, a very small Linux distribution with shell and basic utilities tools" - so I assumed those basic utilities in alpine would include curl?!

So from that, I still don't get it, why does ci-alpine apparently have curl, bit 2.7.0-alpine doesn't have it and according to the text, the default doesn't have it either? (I know I can roll my own, but I'd like to avoid that)

**Comment by francislavoie** [comment]
Hmm yeah I guess curl was removed in https://github.com/lucaslorentz/caddy-docker-proxy/commit/637ceac82ff2912a007714669f3119c8a764c556

**Comment by lucaslorentz** [comment]
Will also release 2.7.1 with that minor change.
