### ISSUE TITLE
Build error when building with 2.7.1

### ISSUE THREAD

**Issue by SebDanielsson** [lucaslorentz/caddy-docker-proxy#374]
Here's my Dockerfile:

```Dockerfile
FROM caddy:2.5.1-builder-alpine AS builder

RUN xcaddy build \
    --with github.com/caddy-dns/cloudflare \
    --with github.com/lucaslorentz/caddy-docker-proxy/v2@2.7.1

FROM caddy:2.5.1-alpine

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

Building works with 2.7.0 but not 2.7.1.

**Comment by francislavoie** [comment]
What's the error?

**Comment by SebDanielsson** [comment]
I believe it's because the latest relase is tagged V2.7.1 instead of v2.7.1. If I change:
`--with github.com/lucaslorentz/caddy-docker-proxy/v2@2.7.1` to `--with github.com/lucaslorentz/caddy-docker-proxy/v2@V2.7.1` I get no build errors.

The error message is:

```
The command '/bin/sh -c xcaddy build     --with github.com/caddy-dns/cloudflare     --with github.com/lucaslorentz/caddy-docker-proxy/v2@v2.7.1' returned a non-zero code: 1
```

**Comment by lucaslorentz** [comment]
Ok, that makes sense. I was the first release I did from mobile phone. I probabbly did with uppercase V.
Will delete it and do it again.

**Comment by lucaslorentz** [comment]
Done, the new tag was created and old tag deleted.
Build is running and docker images will be pushed soon.

Thank you @SebDanielsson!
