### ISSUE TITLE
Maintenance Page

### ISSUE THREAD

**Issue by masterbater** [lucaslorentz/caddy-docker-proxy#377]
How to handle maintenance like adding .html page and also label that can make a service into maintenance mode?

**Comment by lucaslorentz** [comment]
There are many ways of doing that.
The simplest thing I can think about is to use the response caddy directive. The label would look like this:
```
caddy.0_respond = "Maintenance"
```

**Comment by sowinski** [comment]
@lucaslorentz Where would you put this?

To the caddy-docker-proxy container or to the container with the service?
