### ISSUE TITLE
Using as a reverse proxy and a file server

### ISSUE THREAD

**Issue by gw17252009** [lucaslorentz/caddy-docker-proxy#379]
How would I use this as a file server? I love that this works as my reverse proxy, works awesome. I have apps reverse proxied using subdomains could I also use it to serve a static webpage? If so how would I go about this?

**Comment by francislavoie** [comment]
You would need to mount your files in the CDP container. Then just use the `file_server` directive https://caddyserver.com/docs/caddyfile/directives/file_server
