### ISSUE TITLE
Can't have a static website on caddy file ?

### ISSUE THREAD

**Issue by hycday** [lucaslorentz/caddy-docker-proxy#380]
Hi,

I tried adding a label on the caddy/docker-compose.yml in order to be able to have a static website on the caddy server, it is not working (when pointing to the domain name I get a white page, SSL even if I have an index.html inside ./www) and if I look into the docker logs I get some details about 

>{"level":"info","ts":1656533938.7195706,"logger":"docker-proxy","msg":"Process Caddyfile","logs":"[ERROR]  Removing invalid block: Caddyfile:2: unrecognized directive: sub.domain1.com\nDid you mean to define a second site? If so, you must use curly braces around each site to separate their configurations.\nsub.domain1.com {\n\treverse_proxy IPADDRESS:8080\n}\n\n[ERROR]  Removing invalid block: Caddyfile:2: unrecognized directive: domain1.com\nDid you mean to define a second site? If so, you must use curly braces around each site to separate their configurations.\ndomain1.com {\n\treverse_proxy IPADDRESS:80\n}\n\n"}

> version: "3.7"
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    labels:
      caddy: domain2.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
      - ./www:/var/www/
    restart: unless-stopped
networks:
  caddy:
    external: true

volumes:
  caddy_data: {}

I have another docker with apache/php at domain1.com that works good but I would like to use the power of caddy for a static website at domain2.com ...

**Comment by francislavoie** [comment]
You only have a label for your domain. You _also_ need labels for Caddyfile directives like `root` and `file_server`.

**Comment by hycday** [comment]
would you please happen to have an example as to how to have them as labels ?
would it be something like :

>labels: 
caddy: domain2.com
root: * /home/user/public_html
file_server: .

?

**Comment by francislavoie** [comment]
Read the README: https://github.com/lucaslorentz/caddy-docker-proxy#labels-to-caddyfile-conversion

**Comment by hycday** [comment]
I was missing the volumes as well...

this solved it, thanks @francislavoie so much easier and faster now!

    labels:
      caddy.root: "* /example/path"
      caddy.file_server:
    volumes:
      - /var/www:/example/path
