### ISSUE TITLE
Publish armhf compatible image

### ISSUE THREAD

**Issue by breadcat** [lucaslorentz/caddy-docker-proxy#39]
I'm a big fan of the project and use it on my x86_64 server however I've recently invested in an armhf VPS which I'd like to use this software on. Is it possible you can publish an armhf compatible image alongside the existing x86_64 one on the docker registry?

If not, would it be possible to provide instructions for compiling under armhf?

**Comment by lucaslorentz** [comment]
Thanks @breadcat 

I don't know yet, I tried to setup a build on Travis CI but it fails because there are some commands we want to run inside the arm image.

**Comment by lucaslorentz** [comment]
@breadcat Can you please try the new images?
lucaslorentz/caddy-docker-proxy:ci-arm32v6
lucaslorentz/caddy-docker-proxy:ci-alpine-arm32v6

Next release will generate final images for arm32v6. Like `lucaslorentz/caddy-docker-proxy:v0.1.0-arm32v6`

**Comment by breadcat** [comment]
Thanks @lucaslorentz, fast turnaround!

I should have clarified earlier, when I'm referring to armhf I'm referring to arm32v7 instead of arm32v6. I understand Debian and Alpine refer to these differently. `uname -m` gives me `armv7l`

I can pull the images in fine however when I try to bring the stack up using docker-compose I'm getting an error which may be related to the above.

This is my docker-compose file:
```
version: '2'

networks:
  caddy:
    driver: overlay

services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-arm32v6
    container_name: caddy
    networks:
      - caddy
    ports:
      - 80:80
      - 443:443
      - 2015:2015
    volumes:
      - $CONFDIR/caddy:/root/.caddy
      - /var/run/docker.sock:/var/run/docker.sock
  transmission:
    image: lsioarmhf/transmission
    container_name: transmission
    networks:
      - caddy
    ports:
      - 51413:51413
      - 51413:51413/udp
    volumes:
      - $CONFDIR/transmission:/config
      - $DOWNDIR:/downloads
      - $WATCHDIR:/watch
    environment:
      - PGID=$GROUPID
      - PUID=$USERID
      - TZ=$TIMEZONE
    labels:
      caddy.address: transmission.$DOMAIN
      caddy.targetport: 9091
```

I've created the network manually via `docker network create caddy`.

This is the error I'm getting:
```
WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use the bundle feature of the Docker experimental build.

More info:
https://docs.docker.com/compose/bundles

Creating network "dockerfiles_caddy" with driver "overlay"
Creating caddy
Creating transmission

ERROR: for transmission  Cannot create container for service transmission: json: cannot unmarshal number into Go value of type string

ERROR: for caddy  Cannot start service caddy: Could not attach to network dockerfiles_caddy: rpc error: code = PermissionDenied desc = network dockerfiles_caddy not manually attachable
ERROR: Encountered errors while bringing up the project.
```
If I try to bring up the stack again, I'm getting this error:
```
ERROR: Network "dockerfiles_caddy" needs to be recreated - options have changed
```

Can you let me know if this is something simple I'm messing up here?

**Comment by breadcat** [comment]
I've also tried adding `attachable: true` to my network, which doesn't appear to be accepted by Debian's version of compose as it requires 3.2.

Then I tried manually creating the network separately with attachable via:
```docker network create --driver overlay --attachable caddy````

I'm getting similar errors after trying this.

**Comment by lucaslorentz** [comment]
That doesn't seem to be related to arm version, I read arm32v7 chips supports arm32v6.

Usually when I manually create a network, I have it like this on compose file:
```
networks:
  caddy:
    external: true
```

And driver doesn't matter anymore. Can you try that after creating network manually like you did?

**Comment by breadcat** [comment]
You're right about it not being related to the arm version, I seem to be able to run the binaries without any issue.
I've manually created the network and amended the compose file, This is now working exactly as expected.

Thanks again for your help and for creating this great project. Ticket closed.
