### ISSUE TITLE
How to proxy websockets on ECS

### ISSUE THREAD

**Issue by elibosley** [lucaslorentz/caddy-docker-proxy#390]
Hi! Love this tool but I can't figure out how to proxy websockets on ECS. ECS doesn't support the @ symbol inside of docker labels, so I can't do this:

```
        "dockerLabels": {
            "caddy": "https://${MAIN_DOMAIN}",
            "caddy.0_reverse_proxy": "@ws {{upstreams http 80}}",
            "caddy.@ws.0_header": "Connection *Upgrade*",
            "caddy.@ws.1_header": "Upgrade websocket"
        },
```
Here is the error: `ClientException: Docker label key caddy.@ws.0_header contains invalid characters, does not match pattern ^[_\-a-zA-Z0-9./]+$`
Do you have any suggestions on how to forward our websocket requests without a named matcher?

**Comment by francislavoie** [comment]
You don't need to do anything at all, proxying websockets is automatic. Remove the matchers, it'll _just work_.

**Comment by elibosley** [comment]
Thanks for the fast response! I'll try it out :)
