### ISSUE TITLE
Using this project to generate nginx config

### ISSUE THREAD

**Issue by josegonzalez** [lucaslorentz/caddy-docker-proxy#391]
Hi! I'm a big fan of your project and am using it in [Dokku for our Caddy Integration](https://dokku.com/docs/networking/proxies/caddy/) (let me know how you'd like to be acknowledged btw!).

I was wondering if you could provide some pointers as to how I might change some of the config generation such that we could generate nginx config files and serve apps that way instead of via caddy (to replace our existing nginx integration). In particular, I'd be curious about the following:

- Multiple top-level blocks with the same name: In nginx, we have multiple `server` blocks, with the specific config going _inside_ the config. I wonder if there is a way to do that without having caddy merge config from two unrelated sets of containers together.
- Upstream blocks: In nginx, we use an `upstream` block instead of `reverse_proxy`. It seems like we could definitely have a custom function that prints out the correct upstream name, but I'm less clear on how we might generate those upstreams automatically for groups of containers.
- Using semicolons to terminate statements: Nginx uses `;` to terminate a statement instead of a newline like Caddy. I don't know where I might go to edit this :D

I think with those changes, we could just about generate a proper config for nginx. I'm not asking for you to support nginx, just looking for pointers on where I might look in the codebase to do so. Thanks in advance!

**Comment by francislavoie** [comment]
I think you're probably looking for https://hub.docker.com/r/jwilder/nginx-proxy instead, which does this.

This project is pretty heavily geared towards Caddyfile support and makes a bunch of assumptions based on that. So I'm not sure how much you'll get from this 🤷‍♂️

If @lucaslorentz wants to give any suggestions he can, but I'll close this cause there's not really anything actionable for us 👍
