### ISSUE TITLE
Delay Caddyfile update when a docker object changes

### ISSUE THREAD

**Issue by occamssafetyrazor** [lucaslorentz/caddy-docker-proxy#399]
Is there a way to set a delay before updating the Caddyfile once a docker object changes?
My django service takes about 10 seconds before it's ready for HTTP requests (migrations, gunicorn workers starting, etc.)
When my script scales containers:
`docker-compose up -d --scale django=2 --no-recreate --build`
The Caddyfile adds the new container's IP as soon as the build finishes so there's a 10 second interval where 50% of HTTP requests error.
I've tried CADDY_DOCKER_POLLING_INTERVAL without luck.

**Comment by lucaslorentz** [comment]
It's good that caddy is aware of your new containers as soon as they are running.
Don't try introducing delays as it won't be a stable solution.

What you need is to let caddy know if your containers are ready to serve traffic or not, you can do that by configuring health checks: https://caddyserver.com/docs/caddyfile/directives/reverse_proxy

**Comment by occamssafetyrazor** [comment]
Thank you!
