### ISSUE TITLE
Multiple containers per domain possible?

### ISSUE THREAD

**Issue by OmgImAlexis** [lucaslorentz/caddy-docker-proxy#4]
How would I setup multiple containers making up a single domain?

For example all containers would use `example.com` but with different paths `/`, `/admin`, `/dashboard` for each. Currently if I add multiple containers with the same domain the generator just creates multiple entries for the domain.

**Comment by lucaslorentz** [comment]
You can add paths to address label. Caddy works with multiple config entries for same domain.

Just use:
`caddy.address=example.com`
`caddy.address=example.com/admin`
`caddy.address=example.com/dashboard`

Test:
```
docker service create --network caddy -l caddy.address=whoami.caddy-proxy -l caddy.targetport=8000 -l caddy.tls=off --name whoami0 jwilder/whoami
docker service create --network caddy -l caddy.address=whoami.caddy-proxy/path1 -l caddy.targetport=8000 -l caddy.tls=off --name whoami1 jwilder/whoami
docker service create --network caddy -l caddy.address=whoami.caddy-proxy/path2 -l caddy.targetport=8000 -l caddy.tls=off --name whoami2 jwilder/whoami
```
```
curl -H Host:whoami.caddy-proxy http://localhost:2015
curl -H Host:whoami.caddy-proxy http://localhost:2015/path1
curl -H Host:whoami.caddy-proxy http://localhost:2015/path2
```

**Comment by lucaslorentz** [comment]
Some info about addresses here:
https://caddyserver.com/docs/http-caddyfile

**Comment by lucaslorentz** [comment]
Feel free to ask more questions or reopen the issue.

**Comment by OmgImAlexis** [comment]
So more or less the `caddy.targetpath` isn't needed then? I know this is a work in progress but the readme is a tad confusing.

**Comment by lucaslorentz** [comment]
Actually it is still needed. because it is the path the proxy target will receive the requests.

You can combine both to achieve different results.

You could have:
```
//Redirects whole domain to whole container
address=whoami.caddy-proxy

//Redirects whole domain to container path
address=whoami.caddy-proxy
targetpath=/my-path

//Redirects domain path to whole container
address=whoami.caddy-proxy/path1

//Redirects domain path to container path
address=whoami.caddy-proxy/path1
targetpath=/path1
```
