### ISSUE TITLE
cpu issues on larger setups

### ISSUE THREAD

**Issue by teodorescuserban** [lucaslorentz/caddy-docker-proxy#400]
Please see https://caddy.community/t/looking-for-advice-on-keeping-the-cpu-consumption-low/17177?u=teodorescuserban for more details. 

In principle I have n a single dev server about 79 containers with a total of 87 domains. Everytime the config changes (either a container is changing state or I change something in the actual `Caddyfile`, the cpu goes to max (the equivalent of 2 CPUs limit for the docker container running caddy) for 1 to 3 minutes; during this time caddy is very slow (presumably die to the cpu limit) and it is basically unusable; also, because it is a dev server, the containers are being deployed / fiddle with all the time.

Error seen is `shutting down admin server: context deadline exceeded`.

This might not be specific to caddy-docker-proxy plugin, but I would really appreciate any idea about how to fix this.

**Comment by lucaslorentz** [comment]
I wonder if the cpu increases due to caddyfile generation or caddy server reload.
Could you split your setup into a caddy-docker-proxy controller and server and check which container has the cpu peak?

**Comment by lucaslorentz** [comment]
Just saw the logs from your forum thread. Looks like caddy file generation is fast.

Since the problem is on caddy reloads, Matt Holt would be the best one to advise. Did you try what he suggested about on-demand TLS?

**Comment by teodorescuserban** [comment]
> Just saw the logs from your forum thread. Looks like caddy file generation is fast.
> 
> Since the problem is on caddy reloads, Matt Holt would be the best one to advise. Did you try what he suggested about on-demand TLS?

I am going to try the on demand tls, indeed. Didn't tried it yet, have to figure out how it works :)

I am wondering though if the tls issue is not put in overdrive by the fact that the config coming from docker proxy is through [POST /load](https://caddyserver.com/docs/api#post-load) rather than adding / removing bits of config with [POST /config/[path]](https://caddyserver.com/docs/api#post-configpath), [PUT /config/[path]](https://caddyserver.com/docs/api#put-configpath), [PATCH /config/[path]](https://caddyserver.com/docs/api#patch-configpath) or [DELETE /config/[path]](https://caddyserver.com/docs/api#delete-configpath).

**Comment by lucaslorentz** [comment]
Maybe even changing small bits would trigger a full caddy reload because http and TCP listeners might be shared across all sites. I also think those config patch method are just a facade to a full reload mechanism, and this optimization would require changes in caddy itself. Need to check caddy code to confirm.

**Comment by francislavoie** [comment]
That's correct, any change to the config is a full reload.

It really depends what's in your config that might be causing this. Do you happen to use `basicauth`? If so... that's probably the culprit. But that should be fixed in v2.6.

**Comment by teodorescuserban** [comment]
> That's correct, any change to the config is a full reload. Using PATCH etc will not perform any better.
> 
> It really depends what's in your config that might be causing this. Do you happen to use `basicauth`? If so... that's probably the culprit. But that should be fixed in v2.6.

Yeah we do use basicauth.
Excellent idea, @francislavoie !

I replaced the 2.5.2 with 2.6.0-beta.3 and those 2 minutes got down to about 6 seconds!
Awesome, thank you!
