### ISSUE TITLE
Allow to specify Caddy config not related to any service

### ISSUE THREAD

**Issue by louisgavalda** [lucaslorentz/caddy-docker-proxy#420]
Hi,

When using Caddy, I often need to **reverse proxy** an application **running locally** (for instance, when developing an API served on localhost, or any quick hack). In this case I set the Caddy service network mode to `host`.

But sadly it seems that Caddy-Docker-Proxy -- which is a fantastic project nevertheless -- does not allow me to specify Caddy config not related to a service declared in the docker-compose file.

This _limitation_ is expected, as this project’s goal is only to "enables Caddy to be used as a reverse proxy for Docker containers via labels". Maybe it won’t feel  _right_ to specify config which has nothing to do with the services declared in the docker-compose file. Still, allowing to specify some extra raw Caddy config (injected in the Caddyfile) somewhere in the docker-compose file could be really convenient for a usecase similare to mine, as it would allow to consolidate all Caddy-related stuff in the docker-compose file.

What do you think?

Maybe there is actually a witty way to reverse proxy an application running locally (**not in a Docker container**) using Caddy-Docker-Proxy?

Thank you! :see_no_evil: 

Regards.

**Comment by francislavoie** [comment]
You absolutely can do that. See the readme. You can either set labels on the CDP container itself, or pass an initial Caddyfile to use via the container's startup command.
