### ISSUE TITLE
Is it possible to route all unmatched routes to a specific service?

### ISSUE THREAD

**Issue by cryptobench** [lucaslorentz/caddy-docker-proxy#421]
Hello. I'm having a bit of trouble creating this multitenant app with Traefik, so i'm exploring other solutions.

1) Is it possible to use this project to say route all subdomain requests to *.mydomain.com at service A? It could be example2.mydomain.com, example3.mydomain.com, example4.mydomain.com .... and so on.
2) Is it possible to route all unmatched root domain routes to a specific service named B? It could be example2.com, example3.com example4.com .... all into this specific container?

**Comment by IndeedNotJames** [comment]
This plugin just parses docker labels and converts that into a Caddyfile.
So I'd recommend skimming through the Caddyfile docs:
https://caddyserver.com/docs/caddyfile

Assuming I didn't misunderstand you or whatever, then your Caddyfile could look something like the following:
```Caddyfile
# proxy all subdomains to a single service
*.example.com {
	reverse_proxy localhost:8080 # if you are using labels, then you should use {{upstreams 8080}} instead, see README.md

	# Note: a wildcard tls certificate requires the use of a dns provide to use the dns acme challenge
	# https://caddyserver.com/docs/caddyfile/patterns#wildcard-certificates
	# https://caddyserver.com/docs/automatic-https#dns-challenge
}
```


Regarding
> 2. Is it possible to route all unmatched root domain routes to a specific service named B? It could be example2.com, example3.com example4.com .... all into this specific container?

Yes, that is also possible.
If you know all domains beforehand, then you could just put all of them into a label (single Caddyfile line):

```Caddyfile
example.com example1.com example2.com {
	reverse_proxy localhost:8081 # same as above
}
```

Or you could use Caddy's [On-Demand TLS](https://caddyserver.com/docs/automatic-https#on-demand-tls)

**Comment by cryptobench** [comment]
Thanks for the comment! I have now migrated to Caddy and it works just as I want to :-)
