### ISSUE TITLE
Support the `caddy run` flag `--envfile`

### ISSUE THREAD

**Issue by polarathene** [lucaslorentz/caddy-docker-proxy#423]
Presently using `--envfile` seems the best supported way to provide secrets like a DNS API token, without leaking into the container metadata (_which is visible from `docker inspect` on a host_), or to any other process within the container - both of which would happen with providing ENV to a container via `environment` and `envfile` in compose config.

Better would be the ability to source the secret file directly within the Caddyfile at runtime similar to `env` placeholder, but this is not a feature Caddy presently supports.

---

[Related issue raised at `caddy-dns/cloudflare`](https://github.com/caddy-dns/cloudflare/issues/46) (_requesting support to source a secret directly, instead of using it as an ENV_).

**Comment by lucaslorentz** [comment]
Feature included in https://github.com/lucaslorentz/caddy-docker-proxy/releases/tag/v2.8.10
