### ISSUE TITLE
¿Custom http/https ports for SSL challenge?

### ISSUE THREAD

**Issue by sergiocasero** [lucaslorentz/caddy-docker-proxy#425]
Hello, I have a problem with my router and caddy. The problem is that I'm unable to open ports 80 and 443 on my router, so it's not working, is there any way to configure these ports to be custom?

The problem is it's trying to do the challenge (to get the certs) to port 80 but as I said, port 80 couldn't be opened because of the router.

```
Timeout during connect (likely firewall problem)","instance":"","subproblems":[]}}
{"level":"error","ts":1669123858.7212262,"logger":"http.acme_client","msg":"validating authorization","identifier":"whoami.mydomain.com","problem":{"type":"urn:ietf:params:acme:error:connection","title":"","detail":"83.61.220.65: Fetching http://whoami.mydomain.com/.well-known/acme-challenge/P5KrJWBJNtxFXfx5oPgXs5YQ4CcSW9MYMAI6XulKl6Y: Timeout during connect (likely firewall problem)","instance":"","subproblems":[]},"order":"https://acme-staging-v02.api.letsencrypt.org/acme/order/77033304/5373746834","attempt":2,"max_attempts":3}
```

What I expect is to be able to do something like Fetching http://whoami.mydomain.com:**CUSTOM_PORT**/.well-known/a

Maybe it's not possible, just asking :)

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

It's not possible. ACME HTTP and TLS-ALPN challenges _require_ the use of ports 80 and 443.

Some alternate solutions:
- Use the ACME DNS challenge instead, which has no specific port requirement. See the docs: https://caddyserver.com/docs/automatic-https#acme-challenges
- Use something like Cloudflare tunnels to set up a tunnel between your server and Cloudflare, which would get around the problem (could also be done with your own VPS cloud server and an SSH tunnel)

For next time, please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
