### ISSUE TITLE
proxying to https backend

### ISSUE THREAD

**Issue by hijak** [lucaslorentz/caddy-docker-proxy#44]
hi

i need to proxy to a https backend on 443 

delcaring the port as 443 causes a 400 error due to caddy trying to communicate on http

how would i proxy to a https backend?

**Comment by lucaslorentz** [comment]
It's not possible right now. But definitely a must have.
I'm working on it.

**Comment by lucaslorentz** [comment]
@hijak 
Can you please test the new label: targetprotocol=https on latest ci-alpine or ci versions?
