### ISSUE TITLE
removing invalid block: unreckognized global option:{}

### ISSUE THREAD

**Issue by Neon-44** [lucaslorentz/caddy-docker-proxy#441]
hey. i have tried switching to a caddy-docker-proxy where i import configurations depending on whether the service this imported file configures is running.

i thought of this as a very nice solution to have the best of both worlds:
1. the flexibility / automation of only running a service when the docker container is running
2. the readability of a caddyfile

however i have had some problems with caddy-docker-proxy

when i try to "caddy.import", it just spouts out this Error message: 

> {"level":"info","ts":1671624082.4985662,"logger":"docker-proxy","msg":"Process Caddyfile","logs":"[ERROR]  Removing invalid block: /srv/caddyfiles/homeassistant.caddyfile:1: unrecognized global option: {}\n{\n\timport /srv/caddyfiles/homeassistant.caddyfile\n\timport caddyfiles/test.caddyfile\n}\n\n"}

i have tried everything:
adding a global option as 

> {}

as
>{
}

or none at all. it just always gives me this error.

when i try to not import it but just enter "caddy: test.local.domain.tld" it gives me a SSL cert error (SSL_INTERNAL_ERROR_ERROR_ALERT), which is probably because i use wildcard-DNS-Validation in my main caddy file for *.local.domain.tld and don't have a record pointing to my ip

i have searched other issues, especially #262, as it has a very similar name to mine, but i haven't been able to solve it

**Comment by IndeedNotJames** [comment]
Can you share the contents of `/srv/caddyfiles/homeassistant.caddyfile` please?

Also, if you want to keep using the DNS challenge with caddy-docker-proxy, have a look at https://github.com/lucaslorentz/caddy-docker-proxy/issues/304#issuecomment-944972646

**Comment by Neon-44** [comment]
yes, of course:
here's how it gets mapped:

```
Volumes:
  - ./caddyfiles:/srv/caddyfiles:rw
```
here's the homeassistant.caddyfile:
```
{
}

homass.local.gisler.one {
 respond "hello World"
# reverse_proxy 192.168.1.194:8123
}


```

i tried if i can get it to at respond with Hello World but nothing.

also to #304: 
do i also have to do this when importing the configs, and do i have to put this on every docker container?

**Comment by Neon-44** [comment]
yes, of course:
here's how it gets mapped in docker compose:
```
volumes:
      - ./caddyfiles:/srv/caddyfiles:rw
```

here's the config itself:
```
{
}

homass.local.[redacted domain].[redacted tld] {
 respond "hello World"
# reverse_proxy 192.168.1.194:8123
}

```

and here's how it is imported in the homeassistant docker-compose:
```
labels:
      caddy.import: /srv/caddyfiles/homeassistant.caddyfile
```

quick question to #304:
do i also have to do this when importing certificates or do they know that i already got a wildcard certificate in the main caddyfile?
and do i have to do this for every docker container or only for say the caddy docker container

thanks for your help btw, i really appreciate it :)

**Comment by Neon-44** [comment]
i "fixed" it (more like moved on to the next error code, but whatever)

i didn't have the "caddy:" label defined, since i wanted to define everything inside the caddyfile and then just import the caddyfile via the label.
if you don't specify the "caddy:" label it thinks you're trying to define something global.

fixing it was as easy as adding a ```caddy: "none" ``` label

**Comment by Neon-44** [comment]
forgot to close with comment
