### ISSUE TITLE
is it possible to just use this plugin to import already existing caddyfiles instead of defining everything inside the labels?

### ISSUE THREAD

**Issue by Neon-44** [lucaslorentz/caddy-docker-proxy#443]
essentially i already have a lot of services defined in caddyfiles i import, such as nextcloud.caddyfile, gitea.caddyfile etc etc.

i prefer this way of defining everything in the caddyfile, as i personally perceive it as a cleaner overview and easier to read, instead of a bunch of labels.

is it possible to have everything defined in the caddyfile and just ```caddy.import``` the file in question?

because when i tried to do that, it gave me a "unrecognised directive" Error, leading me to believe that the directive/domain needs to be declared in a label and not in a caddyfile that is being imported.

**Comment by IndeedNotJames** [comment]
Are you aware of the `CADDY_DOCKER_CADDYFILE_PATH` environment variable?

Your labels will merge with whatever Caddyfile you specify there.

You could also use snippets.
See https://caddyserver.com/docs/caddyfile/concepts#snippets for a brief introduction.

Just be aware that the special `upstreams` keyword, e.g. in `caddy.reverse_proxy: "{{ upstreams 8000 }}"`, will only work in labels and won't work if you use

```Caddyfile
example.com {
    reverse_proxy {{ upstreams 3000 }}
}
```

And honestly, if you don't really use the labels and prefer raw Caddyfiles anyway, then you could also just specify the container name and make use of docker's internal DNS instead:

```Caddyfile
example.com {
    reverse_proxy gitea:3000
}
```

To import that Caddyfile dynamically from a label, use
```yaml
labels:
  caddy: import /data/gitea.caddyfile
```
At which point, you could also just put `import /data/gitea.caddyfile` in that Caddyfile at `CADDY_DOCKER_CADDYFILE_PATH` instead

**Comment by Neon-44** [comment]
you solved my problem, i love you. i can finally access my services again.

i know i could just import it in the main Caddyfile, but at the Moment i only have a raspberry pi 4 to host everything (I'm planning on gifting myself a actual server for Christmas), so i don't have the luxury to let everything running all the time, so being able to turn on and off the domains when the respective service is (not) running instead of having to go and comment it out is a huge quality of life improvement

i also like to play around with my selfhosted-setup, so automating this part will make that easier as well :)

there is still a problem that i can't import snippets across the Caddyfiles, but i managed to do without that for now and i think that, for organisation reasons, this is better discussed in a new, dedicated issue :)

thank you so much for your help @IndeedNotJames 😃

**Comment by Neon-44** [comment]
btw i can write documentation on this issue to help other newbies bound to follow, if you want

pinging @lucaslorentz, as he's the owner of this repo and has to decide whether or not he wants documentation on this, or if the readme is already long enough
