### ISSUE TITLE
It is possible to alter vanilla JSON config anyhow?

### ISSUE THREAD

**Issue by gabrielmocan** [lucaslorentz/caddy-docker-proxy#444]
I'm trying to use caddy-docker-proxy with https://github.com/yroc92/postgres-storage but they don't seem to suport Caddyfile configuration yet. There's any way of config this storage "the old way" in the vanilla JSON?

**Comment by IndeedNotJames** [comment]
No, there is no way to specify a json config in `caddy-docker-proxy`.
See #184, #186, #221 for some context.

Your best bet is to follow https://github.com/yroc92/postgres-storage/issues/5 - which you seem to be already doing :)

**Comment by gabrielmocan** [comment]
Thanks, I also think that's the proper way.

**Comment by gabrielmocan** [comment]
We got this working now https://github.com/yroc92/postgres-storage/pull/9

To whoever needs it.
