### ISSUE TITLE
How do I set up authelia with this?

### ISSUE THREAD

**Issue by ixanza** [lucaslorentz/caddy-docker-proxy#446]
The official caddy and authelia docs mention using a forward auth which i'm not sure how to set up with this proxy. Is there an example out there that someone has that I can follow?

**Comment by francislavoie** [comment]
CDP just maps Caddyfile to docker labels. See the README. Take a look at the `forward_auth` directive documentation.

**Comment by Bernben** [comment]
> The official caddy and authelia docs mention using a forward auth which i'm not sure how to set up with this proxy. Is there an example out there that someone has that I can follow?

here is a working example

`        labels:
            caddy: devtools.sysdev.online, www.devtools.sysdev.online
            caddy.reverse_proxy: "{{upstreams 80}}"
            caddy.forward_auth: "auth:9091"
            caddy.forward_auth.0_uri: "/api/verify?rd=https://auth.domain.tld/"
            caddy.forward_auth.1_copy_headers: "Remote-User Remote-Groups Remote-Name Remote-Email"
            `

**Comment by eazylaykzy** [comment]
> > The official caddy and authelia docs mention using a forward auth which i'm not sure how to set up with this proxy. Is there an example out there that someone has that I can follow?
> 
> here is a working example
> 
> ```
>         labels:
>             caddy: container.domain.online
>             caddy.reverse_proxy: "{{upstreams 80}}"
>             caddy.forward_auth: "auth:9091"
>             caddy.forward_auth.0_uri: "/api/verify?rd=https://auth.domain.tld/"
>             caddy.forward_auth.1_copy_headers: "Remote-User Remote-Groups Remote-Name Remote-Email"
> ```

@Bernben @francislavoie 

This actually works and further the auth to Authelia, but it does not leave the request URL, and returns a 401 while still on the requested URL. Please do you have any idea why?

**Comment by francislavoie** [comment]
If the auth service returns anything other than a 200 status response, then it will be served to the client directly. So you need to figure out why Authelia didn't serve a successful response. That's out of scope here, best if you ask the Authelia team for help.

**Comment by eazylaykzy** [comment]
> If the auth service returns anything other than a 200 status response, then it will be served to the client directly. So you need to figure out why Authelia didn't serve a successful response. That's out of scope here, best if you ask the Authelia team for help.

Thank you @francislavoie , I appreciate your prompt response, I found out I wasn't serving my app over HTTPS was the reason Authelia wasn't working, it's fixed now, and I'm good. 🚀
