### ISSUE TITLE
When container is removed the generated caddy file still has the entry

### ISSUE THREAD

**Issue by woss** [lucaslorentz/caddy-docker-proxy#450]
I start the container after some time i remove it, then i inspect the logger that the cdp outputs and i see that the entries for that specific container are still here.

Any way to `clear the cache` and force recreating the new caddy file?

**Comment by francislavoie** [comment]
When you say "removed", how are you doing that?

Please be as specific as possible. Show your order of operations you took to get to that point. Show the logs you're seeing.

**Comment by woss** [comment]
Oh, i thought this clear.

start the container with `docker-compose up container-name`
stop it with `docker-compose stop container-name`
then remove it with `docker-compose rm container-name # then press y`

On this screenshot the selected virtual host is not up and it is removed. and the code i have pasted ( the yellow ) is the copy from the cdp docker output. 
<img width="638" alt="image" src="https://user-images.githubusercontent.com/80440/212677535-abd4a5b4-445f-4845-8e79-b6e0044263d7.png">

Running containers: 
<img width="341" alt="image" src="https://user-images.githubusercontent.com/80440/212677748-71ee2c90-ea7b-4ea7-9e0a-0bef48da9985.png">

And the one that doesn't run but still in the Caddyfile ( in memory inside the cdp  ) 
<img width="707" alt="image" src="https://user-images.githubusercontent.com/80440/212677843-a752e8e4-40b5-4b9c-bb19-9a36e7a3aeaf.png">

 I hope it's clearer now, if not let me know how can i make it more clearer :)
