### ISSUE TITLE
podman issues

### ISSUE THREAD

**Issue by MatYRicS** [lucaslorentz/caddy-docker-proxy#453]
I'm trying to build a custom image (https://github.com/lucaslorentz/caddy-docker-proxy#custom-images) of `caddy` with `cloudflare` and `caddy-docker-proxy` added and the changes from #415 and #427 should be included. But it seems like these commits are not used in version `2.8.1` that is the current release of `caddy-docker-proxy`.

This is my `Dockerfile`:
```
ARG CADDY_VERSION=2.6.2
FROM caddy:${CADDY_VERSION}-builder AS builder

RUN xcaddy build \
    --with github.com/lucaslorentz/caddy-docker-proxy/v2@v2.8.1 \
    --with github.com/caddy-dns/cloudflare

FROM caddy:${CADDY_VERSION}-alpine

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

CMD ["caddy", "docker-proxy"]
```

With this `Dockerfile` I still get the `Container is not in same network as caddy` error and the `EOF` error.

How can I build this image with the metioned commits so I can run it with `podman` instead of `Docker`?

**Comment by francislavoie** [comment]
You can use the latest commit hash 172f39f06f2972eec60c0d38514c5fd0b50af9ca instead of the tagged version after the `@` to build from that commit.

**Comment by lucaslorentz** [comment]
I didn't realize there was unreleased changes.
I will do a release now.

**Comment by lucaslorentz** [comment]
Maybe @master also works. But I'm not sure.

**Comment by lucaslorentz** [comment]
You can do v2.8.2 now.

**Comment by francislavoie** [comment]
Yeah `@master` would also work, but Docker would not realize that it changed when you rebuild because the text in the Dockerfile stayed the same while the commit at the end of the reference did change.

**Comment by MatYRicS** [comment]
Thanks guys. I will try it tomorrow with `podman`.

Also why is there a version `2.9.9` available here https://pkg.go.dev/github.com/lucaslorentz/caddy-docker-proxy/plugin/v2/config?

**Comment by lucaslorentz** [comment]
That was some old testing.
This is the right package https://pkg.go.dev/github.com/lucaslorentz/caddy-docker-proxy/v2
I will fix it in caddyserver download, forgot to change it when

**Comment by MatYRicS** [comment]
I can confirm that v `2.8.2` works with `podman`.
