### ISSUE TITLE
Slow config reload when using shutdown_delay

### ISSUE THREAD

**Issue by heapdavid** [lucaslorentz/caddy-docker-proxy#465]
We're currently using a `shutdown_delay` of 15 seconds to give our hardware load balancer warning of when caddy is about to go down for drains/maintenance etc as per https://caddyserver.com/docs/caddyfile/options#shutdown-delay - but this also seems to delay the config reload by the same amount. During the shutdown period our load balancer marks the caddy servers offline (as it should) so we lose ingress to the swarm services until they come back online and pass the healthcheck again.

Should/can a reload ignore this delay?

![image](https://user-images.githubusercontent.com/88432183/221179979-5a941af9-8d72-4648-aa2f-a8454fb5dc0d.png)

**Comment by francislavoie** [comment]
This belongs in github.com/caddyserver/caddy, not here.

**Comment by IndeedNotJames** [comment]
Moved to https://github.com/caddyserver/caddy/issues/5393
