### ISSUE TITLE
Allow top-level directives

### ISSUE THREAD

**Issue by Torbe** [lucaslorentz/caddy-docker-proxy#47]
Would be nice to be able to insert top-level caddy-directives trough labels. 

I try to insert a `import` directive to import additional caddy configuration files. I tried with caddy.import=/etc/caddy/Caddyfile*, but this results in 
` {
import /etc/caddy/Caddyfile*
}`

The `import` directive needs to be at the top-level. Any thoughts on that?

**Comment by lucaslorentz** [comment]
That's related to https://github.com/lucaslorentz/caddy-docker-proxy/issues/23

I'm planning to add `docker config` content to caddyfile.
Probably with some label inside `docker config`.
Like: `caddy`

**Comment by lucaslorentz** [comment]
@Torbe 
Would that be enough for you? Whatever content you add to a docker config, will be appended to caddyfile.

**Comment by Torbe** [comment]
@lucaslorentz Nice! That sounds good!
