### ISSUE TITLE
HELP please, setting up docker-compose and kong api gateway

### ISSUE THREAD

**Issue by gregpalaci** [lucaslorentz/caddy-docker-proxy#472]
I've been struggling for hours, a bit new to docker networking. 
The documentation is really great you provided thanks! But I cant seem to get it right.
If anyone had a sec how would I use the proxy for https://github.com/supabase/supabase/blob/master/docker/docker-compose.yml I want to map it to a the root of a subdomain abc.def.com 

Mostly its port 8000 (kong) and port 3000 ( dashboard studio) that need to be external

I got kinda close with vanilla caddy but no dice
```supabase.carflow.io {

  @supabase {
      path_regexp supabase ^/(auth|rest|realtime|storage|pg)/.*$
  }

  # reverse proxy requests to supabase paths to the supabase kong http endpoint
  reverse_proxy @supabase http://supabase.carflow.io:8000 

  # all other request should go to the sveltekit server
   # reverse_proxy localho.st:3333
  tls internal
}

# and also  tried

supabase.carflow.io {
    reverse_proxy /rest/v1/* localhost:8000
    reverse_proxy /auth/v1/* localhost:8000
    reverse_proxy /realtime/v1/* localhost:8000
    reverse_proxy /storage/v1/* localhost:8000
    reverse_proxy * localhost:3000
    reverse_proxy
}
```

**Comment by francislavoie** [comment]
In Docker, localhost means "this same container". To proxy to another container, use its container/service name instead.
