### ISSUE TITLE
Ports aren't being exposed even though docker reports them as open 

### ISSUE THREAD

**Issue by shagia** [lucaslorentz/caddy-docker-proxy#473]
I'm sharing a server with a friend who switched their web server to use Caddy with docker proxies as opposed to Nginx and it's been a learning experience. I'm using it to host a radio server software, Azuracast, and its self rotating station works fine with its http and https ports being exposed to the internet, but trying to connect to _any_ port that's required for say streaming to a station or connecting to its SFTP drive returns an 'unknown host' error. Docker shows these ports being exposed, for example the SFTP port and just for further documentation, a batch of other ports for 2 other stations:

> ping: cannot resolve 116.202.86.222:2022: Unknown host

> 0.0.0.0:2022->2022/tcp, :::2022->2022/tcp, 80/tcp, 0.0.0.0:8000->8000/tcp, :::8000->8000/tcp, 8001-8004/tcp, 0.0.0.0:8005-8006->8005-8006/tcp, :::8005-8006->8005-8006/tcp, 8007-8009/tcp, 0.0.0.0:8010->8010/tcp, :::8010->8010/tcp, 8011-8014/tcp, 0.0.0.0:8015-8016->8015-8016/tcp, :::8015-8016->8015-8016/tcp, 8017-8019/tcp, 0.0.0.0:8020->8020/tcp, :::8020->8020/tcp, 8021-8024/tcp, 8027-8999/tcp, 0.0.0.0:8025-8026->8025-8026/tcp, :::8025-8026->8025-8026/tcp

Caddy isn't installed directly and uses Docker to compile a Caddyfile directly to the memory but after that I can't really tell you what's going on here and I think that's where I'm mistakened. Here's the entire config file for context:
![image](https://user-images.githubusercontent.com/13505837/226136133-b3203f26-1458-4a0f-a343-c5f3a95cde82.png)
![image](https://user-images.githubusercontent.com/13505837/226136137-03390f0d-afcb-4676-aa86-d97d73c2d057.png)

**Comment by francislavoie** [comment]
None of this seems related to Caddy. I don't understand what you're asking.

Caddy is an HTTP server, it normally only listens to traffic on port 80/443 unless configured explicitly to handle traffic on other ports.
