### ISSUE TITLE
Global Matchers

### ISSUE THREAD

**Issue by ibrokemypie** [lucaslorentz/caddy-docker-proxy#478]
How would I go about creating a single named matcher definition that I can use across many services without having to redefine it for each one? Usecase being a matcher for external IP's so I can just do `caddy.abort: @external` on any service I only want accessible internally

Thanks!

**Comment by francislavoie** [comment]
You would define it in a snippet https://caddyserver.com/docs/caddyfile/concepts#snippets then import it in each site that needs it.

There's no mechanism for globally defined matchers. Matchers are scoped to a site block.
