### ISSUE TITLE
Mix remote_ip and remote_host labels

### ISSUE THREAD

**Issue by chrisbgp** [lucaslorentz/caddy-docker-proxy#481]
I am using caddy-docker-proxy with the **remote_host plugin** to allow dyndns hosts to access my containers. Now I also need to enable **private_ranges** to be able to access the containers from another wireguard vpn container. I want to block everything else. The code below does not work. Any help is appreciated!

`    

      caddy: rss.asdf.com
      caddy.@local.not: "remote_ip private_ranges"
      caddy.@remote.not: "remote_host x.dyndns.org"
      caddy.abort: "@local"
      caddy.abort: "@remote"
      caddy.reverse_proxy: "{{upstreams 7070}}"
      caddy.tls.ca: https://acme-v02.api.letsencrypt.org/directory
`

**Comment by francislavoie** [comment]
You'll need to say more than "does not work". Show an example request with `curl -v`, enable the `debug` global option, show your logs.

**Comment by chrisbgp** [comment]
Sorry, that was unclear. It seems that only the last caddy.abort statement works as expected. In this example I was able to connect from an external connected but not from **private_ranges**

When I switch them around, then I am able to connect internally but not from an external request anymore. Is there any way to make them work both at the same time?

**Comment by francislavoie** [comment]
So you want `remote_host x.dyndns.org` AND `remote_ip private_ranges` -> `abort`, right?

Currently your config does `remote_host x.dyndns.org` OR `remote_ip private_ranges` -> `abort`. 

To AND them, you can put both matchers inside of the same `not`. See the docs: https://caddyserver.com/docs/caddyfile/matchers#not

```
  caddy.@not_local_and_remote.not: "remote_ip private_ranges"
  caddy.@not_local_and_remote.not: "remote_host x.dyndns.org"
  caddy.abort: "@not_local_and_remote"
```

**Comment by chrisbgp** [comment]
Yes, indeed I wanted to AND them. I have just tried your snippet, unfortunately it is not working as expected for me. Only the last matcher gets executed. I also switched them to make sure. Could the problem be related to the 3rd party plugin (remote_host) ?

Thanks for your help.

**Comment by francislavoie** [comment]
Ah yeah, right 🤦‍♂️ thanks @IndeedNotJames 

I think you can do this to fix it:

```
  caddy.@not_local_and_remote.not_0: "remote_ip private_ranges"
  caddy.@not_local_and_remote.not_1: "remote_host x.dyndns.org"
  caddy.abort: "@not_local_and_remote"
```

**Comment by francislavoie** [comment]
Closing as inactive
