### ISSUE TITLE
Feature request: Configurable block merging

### ISSUE THREAD

**Issue by otaconix** [lucaslorentz/caddy-docker-proxy#487]
First of all: I'm really enjoying caddy-docker-proxy, thanks!

I was hoping I could use it together with [mholt/caddy-dynamicdns](https://github.com/mholt/caddy-dynamicdns) in such a way that I could get it to work by adding a label to every container that wants a DNS record.

## Example

Labels for Container A:
- `caddy_0.dynamic_dns.domains.example=container-a`
- `caddy_1=container-a.example`
- etc

Labels for Container B

- `caddy_0.dynamic_dns.domains.example=container-b`
- `caddy_1=container-b.example`
- etc

Resulting Caddyfile:

```
{
  dynamic_dns {
    domains {
      example container-a
      example container-b
    }
  }
}
```

Unfortunately, the `dynamic_dns.domains` stores its contents in a `map`, which currently results in only the last list of subdomains for a specific domain will be seen by dynamic_dns (in this case: the `container-b` one).

What I'd really like to achieve is this, without having to resort to having a single label on (for example) the caddy-docker-proxy container:

```
{
  dynamic_dns {
    domains {
      example container-a container-b
    }
  }
}
```

## The question

I've had a look at the code for caddy-docker-proxy, and I noticed that [two directives have been special-cased so they end up being merged (`reverse_proxy` and `php_fastcgi`)](https://github.com/lucaslorentz/caddy-docker-proxy/blob/46f78dafc461d5a73d172fdcaa5fc18851a5288d/caddyfile/merge.go#L6). Would it be possible to somehow make this merge strategy configurable to support the use-case I described in my example above? Or is there already a way to achieve what I want?

I totally understand if you consider this some weird edge case you don't care to support. Thanks for considering it!

**Comment by francislavoie** [comment]
Hmm this can probably be fixed more easily in dynamic-dns' Caddyfile parsing to append if the map already exists instead of clobbering.

**Comment by otaconix** [comment]
> Hmm this can probably be fixed more easily in dynamic-dns' Caddyfile parsing to append if the map already exists instead of clobbering.

You're probably right. I'll try my hand at a PR over there then :+1:

**Comment by otaconix** [comment]
Alright, I'll go ahead and close the issue. I personally have no need for the original requested feature anymore. Thanks!
