### ISSUE TITLE
Possible to default to ZeroSSL instead of LetsEncrypt

### ISSUE THREAD

**Issue by iamwoz** [lucaslorentz/caddy-docker-proxy#489]
I run media servers (Emby and Plex) behind Caddy. Some TV's (mostly LG) have issues with LetsEncrypt certs, but ZeroSSL works.

Is it possible to make caddy-docker-proxy default to ZeroSSL? Thanks!

**Comment by francislavoie** [comment]
Configure the `tls > issuers` https://caddyserver.com/docs/caddyfile/directives/tls
