### ISSUE TITLE
Caddy Security - Possible to add links to the dashboard?

### ISSUE THREAD

**Issue by samcro1967** [lucaslorentz/caddy-docker-proxy#492]
Curious if anyone is using Caddy Security and if you have tried to use docker labels to add links to the dashboard.  Below is an example of where links get added in CaddyFile

Thinking the docker compose labels might look something like this?
```
caddy.security.authentication.portal.myportal.ui.links='"Navidrome" "/navidrome" icon "las la-music" target_blank'
caddy.security.authentication.portal.myportal.transform.user='ui link "Adguard" "https://agh.mydomain.net" icon "las la-cog" target_blank'
```

**CaddyFile example**
```
{
	https_port	443
	email {$EMAIL}
	...
	security {
		...
		authentication portal myportal {
			ui {
				links {
					"My Identity" /whoami icon "las la-user"
					"Navidrome" "/navidrome" icon "las la-music" target_blank
				}
			}
			transform user {
				exact match sub {$USER}
				action add role authp/superadmin
				ui link "Portal Settings" settings icon "las la-cog"
				ui link "Adguard" "https://agh.mydomain.net" icon "las la-cog" target_blank
			}
		}
	}
}
```

**Comment by hialvaro** [comment]
Was about to open an issue with the same question. If anyone can help with this, would be awesome.

**Comment by francislavoie** [comment]
What's the problem exactly? Yes, you should set labels for your global options like that.

**Comment by samcro1967** [comment]
I have not been able to get the above example to work.  I have tried single and double quotes as well as no quotes around `"Navidrome" "/navidrome" icon "las la-music" target_blank`.  Wanted to make sure what I was trying to accomplish is even possible.

**Comment by samcro1967** [comment]
Spent some time working on this again recently.  Best as I can tell docker-caddy-proxy is not able to properly parse labels whose value contains quotes.  Can't seem to find any working combination of single quotes, double quotes, and escaping them with back slashes.  Closing this as it does not seem to be possible.
