### ISSUE TITLE
Log defaults are different from vanilla caddy's

### ISSUE THREAD

**Issue by yamac-kurtulus** [lucaslorentz/caddy-docker-proxy#494]
Hi,
I have realised that the logs are different from the default of a regular caddy proxy. I want to see all the request logs, but I can't. I am not sure if it has to do with logging level, or some other problem. Because I see ERROR, and some of the INFO level logs, but the requests are just not there. Am I missing something? Should I enable them explicitly?

**Comment by francislavoie** [comment]
Yes, access logs must be enabled: https://caddyserver.com/docs/caddyfile/directives/log
