### ISSUE TITLE
Set the reverse_proxy ip of services so that they are the same each compose up

### ISSUE THREAD

**Issue by MCKevmeister** [lucaslorentz/caddy-docker-proxy#497]
Is it possible for one or all of the services defined in the docker compose to be assigned a set reverse_proxy IP address on start up? For example 172.18.0.8? 

I would like to create an allow list of IP addresses that can access a specific service. I can add all the external IP addresses, and the services are accessible, however the reverse_proxy IP address of the docker network changes each startup. Is there a way to define/set the reverse_proxy IP of a service in the docker compose?

**Comment by francislavoie** [comment]
You can just trust the `172.16.0.0/12` IP range which is always private.

**Comment by MCKevmeister** [comment]
That will not work for my use case. I want to set the IP of the service in the docker compose

**Comment by emilylange** [comment]
Yes, you can do that. But it is very much out of scope of this issue tracker -- at least assuming I understand you correctly.
Take a look at `ipam` within `networks`
https://docs.docker.com/compose/compose-file/06-networks/#ipam
