### ISSUE TITLE
Accessing Caddy API

### ISSUE THREAD

**Issue by rgriffogoes** [lucaslorentz/caddy-docker-proxy#499]
I'm trying to make the Caddy API accessible from outside caddy container, and based on Caddy documentation, I conclude that I need to properly set the `listen` property of the `admin` config to allow non-localhost requests (or the `origins` + forward).

My setup is a single node, using docker compose with `lucaslorentz/caddy-docker-proxy:ci-alpine`

I tried:
1. Setting `caddy.admin` label
2. Using external caddy file (`CADDY_DOCKER_CADDYFILE_PATH` + mounted volume with file)
3. Setting `CADDY_ADMIN` (as written somewhere in  caddy doc)
4. Setting a reverse-proxy to localhost:2019 with something like `caddy.servername.local` as the hostname (fails as hostname is not in origins)

Nothing works, and checking on the logs I could see that the settings I changed (e.g.: admin listening on different port) was prepared to be uploaded/set to caddy config, but once the config was done, it would restart the admin server but with default/same config (`localhost:2019`).

Checking in the code, it looks like the admin property is always overwritten with "localhost:2019":

https://github.com/lucaslorentz/caddy-docker-proxy/blob/46f78dafc461d5a73d172fdcaa5fc18851a5288d/cmd.go#L103

https://github.com/lucaslorentz/caddy-docker-proxy/blob/46f78dafc461d5a73d172fdcaa5fc18851a5288d/loader.go#L298

**Is there a way to set the Admin API to listen on a desired interface:port and I am just missing it?**

If not, I would suggest some alternatives (not exclusive of each other):
1. For single host environment, don't overwrite existing admin config if it already exists (from caddy file or from generated config from labels). This should come with a warning that setting invalid listen property can break the setup (as caddy-docker-proxy won't be able to update config)
2. Create new ENV var to allow custom setting of the admin listen property (then existing overwrite methods could still be there)
3. Create new ENV var to customize `origins`, enabling proxying of the API

I never used `Go` or else I would probably have tried option 3 (seems less invasive/risky and with clearer impact).

**Comment by emilylange** [comment]
See https://github.com/lucaslorentz/caddy-docker-proxy/issues/246#issuecomment-1185375170 and #359

**Comment by rgriffogoes** [comment]
I feel stupid for missing those issues, but I was so sure that I was having issues on caddy itself that I searched for issues on Caddy.

While it is not possible to change the API config (listening interface + origins), its is possible to setup a reverse proxy settings. Based on the suggestions on the linked issues, this is what I have in my `caddy-docker-proxy` compose file:

    labels:
      caddy: "http://{{index .Labels \"com.docker.compose.service\"}}.mylocaldomain.home"
      caddy.reverse_proxy: "localhost:2019"
      caddy.reverse_proxy.header_up: Host localhost:2019 

Pretty sure there are good ways to properly restrict access (auth, remote ip), but I couldn't do it quickly. So I left it as a HTTP service that will only be reachable/resolvable internally.

Thanks for the quick reply!
