### ISSUE TITLE
Connect to a Docker daemon on TCP

### ISSUE THREAD

**Issue by ibnesayeed** [lucaslorentz/caddy-docker-proxy#5]
Currently, only the `/var/run/docker.sock` socket connection seems to be possible. This works fine if the Docker Swarm manager is on the same machine where Caddy is running or the the file system containing the socket file is mounted accordingly. It might be useful for some people if instead a TCP address is configurable while keeping the socket as the default.

**Comment by lucaslorentz** [comment]
Thanks for reviewing @ibnesayeed .

I used the function NewEnvClient from docker. It creates a docker client using Environment variables configuration falling back to default values.

I think you can configure how it should connect to the docker api by setting environment variables.

// Use DOCKER_HOST to set the url to the docker server.
// Use DOCKER_API_VERSION to set the version of the API to reach, leave empty for latest.
// Use DOCKER_CERT_PATH to load the tls certificates from.
// Use DOCKER_TLS_VERIFY to enable or disable TLS verification, off by default.

More info here: https://github.com/docker/engine-api/blob/master/client/client.go#L42

**Comment by ibnesayeed** [comment]
Yes, from my casual scan of your code, I did not see any place where you were opening the socket file yourself, so I knew it was offloaded to Docker packages. This means we get this functionality for free. We just need to test it and document accordingly.

**Comment by lucaslorentz** [comment]
Added that information to README file.

**Comment by ibnesayeed** [comment]
@lucaslorentz, I think where we are documenting the `DOCKER_HOST`, we need to explicitly mention that by default it will connect to `/var/run/docker.sock` socket file.

**Comment by lucaslorentz** [comment]
DOCKER_HOST default value varies per platform /var/run/docker.sock
Windows: "npipe:////./pipe/docker_engine"
Unix: "unix:///var/run/docker.sock"

I will add it to README.

**Comment by lucaslorentz** [comment]
Done
