### ISSUE TITLE
Labels for headers (help request)

### ISSUE THREAD

**Issue by MagicJF** [lucaslorentz/caddy-docker-proxy#503]
¿which labels should I have to add in order to achieve a "/config/caddy/autosave.json" that includes a headers like the ones highlighted in yellow?

Right is the desidered output, Left image is caddy-docker-proxy with the following labels: 
 ----caddy: localhost
-----caddy.reverse_proxy: "{{upstreams 8000}}"

![image](https://github.com/lucaslorentz/caddy-docker-proxy/assets/92638213/03aefde9-8726-4f08-9482-a4872e6c47bd)

**Comment by francislavoie** [comment]
See the docs: https://caddyserver.com/docs/caddyfile/directives/header

**Comment by MagicJF** [comment]
This is the conciliation labe, wich allows httpsl:
----caddy.reverse_proxy.header_down: "Strict-Transport-Security max-age=31536000;"
