### ISSUE TITLE
Basicauth example?

### ISSUE THREAD

**Issue by mykiwi** [lucaslorentz/caddy-docker-proxy#504]
Hi

I try to use the [basicauth directive](https://caddyserver.com/docs/caddyfile/directives/basicauth), but without success...
Can someone could show me a working example? Thanks

**Comment by emilylange** [comment]
See https://github.com/lucaslorentz/caddy-docker-proxy/issues/213#issuecomment-768226206, https://github.com/lucaslorentz/caddy-docker-proxy/issues/203#issuecomment-741941282 and the general guide on how the labels to Caddyfile conversion works:
https://github.com/lucaslorentz/caddy-docker-proxy#labels-to-caddyfile-conversion

**Comment by mykiwi** [comment]
Thank you!
