### ISSUE TITLE
Run as non-root

### ISSUE THREAD

**Issue by hialvaro** [lucaslorentz/caddy-docker-proxy#510]
I am trying to avoid running docker containers as root for security reasons.

Is it possible to run caddy-docker-proxy as a non-root user? How?  If I try to specify the user, it fails as it can't access the docker socket (permission denied)

**Comment by lucaslorentz** [comment]
I don't know if root is required to access docker socket.

But let's say you are able to remove root user from caddy container and still connect it to docker socket, the container would still be able to do a lot of damage via docker socket.

I think it might be a good idea to use: https://hub.docker.com/r/tecnativa/docker-socket-proxy

Configure it to only expose read operations and
connect caddy container to that proxy.

By doing that, you should be able to remove root from caddy container.

But maybe the socket proxy will still need root.

I think some people in our community uses tecnativa/docker-socket-proxy, search in the issues for it
