### ISSUE TITLE
whitlist url

### ISSUE THREAD

**Issue by mihsergeev** [lucaslorentz/caddy-docker-proxy#511]
This solution works fine for the whole site:

```caddy.@denied.not: "remote_ip 192.168.0.5 192.168.0.10"
caddy.abort: "@denied"
caddy: domain.com
caddy.reverse_proxy: "{{upstreams http 9000}}"
```

but what should I add here to whitlist only a certain url for example,
for example

/ - allow from all
/admin - from whithlist ip

hint how to do it with caddy-docker-proxy labels ?

**Comment by lucaslorentz** [comment]
Hey @mihsergeev
I would advise you to dig more into Caddy documentation to find out how to do that using Caddyfile: https://caddyserver.com/docs/ . Or ask in caddy forums.

Once you know exactly what you would like in your Caddyfile, it is easier to think of how to achieve that with docker labels.

Our project [readme](https://github.com/lucaslorentz/caddy-docker-proxy) has a bunch of information on how to write labels to generate Caddyfile, but if you still have issues after going through them feel free to open another issue.

Mentioning in the issue exactly which Caddyfile you would like to achieve usually leads to answers from caddy-docker-proxy community.
