### ISSUE TITLE
Container can't connect to Socket

### ISSUE THREAD

**Issue by ZeroIchiro** [lucaslorentz/caddy-docker-proxy#523]
Hey guys,

I try to get caddy running in portainer, using the official DockerHub image 
However, it seems that Caddy cannot connect to the socket of my docker.
This is the logfile from Portainer:

`INF ts=1692178862.892095 logger=docker-proxy msg=Running caddy proxy server

INF ts=1692178862.893354 logger=admin msg=admin endpoint started address=localhost:2019 enforce_origin=false origins=["//[::1]:2019","//127.0.0.1:2019","//localhost:2019"]

INF ts=1692178862.893659 msg=autosaved config (load with --resume flag) file=/config/caddy/autosave.json

INF ts=1692178862.8936727 logger=docker-proxy msg=Running caddy proxy controller

ERR ts=1692178862.893861 logger=docker-proxy msg=Docker ping failed error=Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

Error: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

other images I have are running smoothly, what do I do wrong?

Kind Regards

Zero

**Comment by francislavoie** [comment]
Did you set up a volume for the Docker socket?

**Comment by ZeroIchiro** [comment]
Shouldn't the docker socket be "outside"?
I mean everyone docker container for whatever reason needs to access the socket file, or am I wrong?

**Comment by francislavoie** [comment]
The whole point of CDP is that it directly connects to the Docker socket to pull information about running containers to auto-configure Caddy. So it needs the Docker socket mounted as a volume to do that.
