### ISSUE TITLE
Multiple of the same directive

### ISSUE THREAD

**Issue by twinsuns** [lucaslorentz/caddy-docker-proxy#530]
How do you define multiple directives with the same name?

For example, if my Caddyfile had these:
```
redir /.well-known/carddav /remote.php/carddav 301
redir /.well-known/caldav /remote.php/caldav 301
redir /.well-known/webfinger /index.php/.well-known/webfinger 301
redir /.well-known/nodeinfo /index.php/.well-known/nodeinfo 301
```
How do I translate that to the docker labels for the docker-compose file? If I do them all individually the docker-compose will fail stating that `caddy.redir` is already defined.

**Comment by francislavoie** [comment]
Use the ordering & isolation prefixes/suffixes. See the README

**Comment by twinsuns** [comment]
right, I figured it out with the prefixes. thanks!
