### ISSUE TITLE
Vaultwarden

### ISSUE THREAD

**Issue by gw17252009** [lucaslorentz/caddy-docker-proxy#538]
Love this project. I just can't figure out hiw to get vaultwarden up and running. I've googled and found 1 or 2 examples but no joy. Here is my labels for caddy:

caddy: vaultwarden.$DOMAIN
      caddy.tls: $EMAIL
      caddy.encode: gzip
      caddy.reverse_proxy_0: "{{upstreams 80}}"
      caddy.reverse_proxy_1: "/notifications/hub/negotiate {{upstreams 80}}"
      caddy.reverse_proxy_2: "/notifications/hub {{upstreams 3012}}"
      caddy.reverse_proxy_0.header_up: ""X-Real-IP" {remote_host}"
      caddy.header.X-XSS-Protection: '"1; mode=block;"'
      caddy.header.X-Frame-Options: "DENY"
      caddy.header.X-Content-Type-Options: "none"

**Comment by francislavoie** [comment]
In what way is it not working? What are the symptoms? What's in your logs?

This should be enough:

```
caddy: vaultwarden.$DOMAIN
caddy.tls: $EMAIL
caddy.encode: gzip
caddy.reverse_proxy_0: "{{upstreams 80}}"
caddy.reverse_proxy_1: "/notifications/hub {{upstreams 3012}}"
```

**Comment by emilylange** [comment]
Furthermore, vaultwarden started serving the `/notifications/hub` websocket on port `:80` as well, recently[^1].

Meaning

```
caddy.reverse_proxy: "{{upstreams 80}}"
```

instead of
```
caddy.reverse_proxy_0: "{{upstreams 80}}"
caddy.reverse_proxy_1: "/notifications/hub {{upstreams 3012}}"
```
should work just fine.

Arguably, the Caddy example in https://github.com/dani-garcia/vaultwarden/wiki/Proxy-examples needs some updating.
[^1]: https://github.com/dani-garcia/vaultwarden/releases/tag/1.29.0

**Comment by gw17252009** [comment]
Thanks all. I'll give this a shot later tonight.

**Comment by lucaslorentz** [comment]
Assuming this worked based on inactivity.
Feel free to re-open if you still have issues.
