### ISSUE TITLE
sticky sessions

### ISSUE THREAD

**Issue by devMls** [lucaslorentz/caddy-docker-proxy#546]
Hi

I have a app in docker swarm wirh asp razor mvc

I publish It behind Caddy proxy wirh this olugin

The app is published as service wirh global replica arrond 3 node swarm cluster

I want use signalr that requires sticky sessiions

Is posible use Caddy for ensure a client goes always yo same node?

**Comment by devMls** [comment]
I find that use dnsrr IS a option wirh Caddy

With this aproach 


https://caddy.community/t/load-balancing-problem-with-docker-dnsrr-mode/16316

But i don t know if this can be configured by this plugin

**Comment by francislavoie** [comment]
CDP is simply a mapping of labels to Caddyfile. So anything configurable in Caddyfile can be done with labels. Just read the README to understand the mapping.

That said, your post has lots of spelling issues, so I'm not sure I understand what you're asking for. You could use the `cookie` LB policy for sticky sessions https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#load-balancing

**Comment by lucaslorentz** [comment]
Multiple ways of doing sticky sessions. It could be based on cookies, headers, IP...
I would advise first deciding how to achieve that using only Caddy and Caddyfile config.
If you have issues writing your Caddyfile config using docker labels, feel free to open another issue and we can assist with that.
