### ISSUE TITLE
Latest version not available trough xcaddy build

### ISSUE THREAD

**Issue by Miggets7** [lucaslorentz/caddy-docker-proxy#549]
Version 2.8.9 cannot be found when using xcaddy build:

`xcaddy build --with github.com/lucaslorentz/caddy-docker-proxy/v2@2.8.9`

**Comment by emilylange** [comment]
Please use
```
xcaddy build --with github.com/lucaslorentz/caddy-docker-proxy/v2@v2.8.9
```

like the README says.
Note the `v` in `v2.8.9`.

**Comment by Miggets7** [comment]
Thank you, that was indeed the issue ;-)
