### ISSUE TITLE
How to enable brotli module

### ISSUE THREAD

**Issue by sowinski** [lucaslorentz/caddy-docker-proxy#553]
Hi,

how can I enable brotli plugin with caddy-docker-proxy?

Is this currently not supported?

**Comment by francislavoie** [comment]
You can build a custom image with extra plugins you need: https://github.com/lucaslorentz/caddy-docker-proxy#custom-images

That said, I can't recommend using the brotli plugin, it's very, very slow. You can instead use the `file_server` directive which supports `precompressed` to serve `.br` files.
