### ISSUE TITLE
Container tag vs build version mismatch? 2.8-alpine reports v2.7.5

### ISSUE THREAD

**Issue by alex-kowalczyk** [lucaslorentz/caddy-docker-proxy#561]
$ docker pull lucaslorentz/caddy-docker-proxy:2.8-alpine 
2.8-alpine: Pulling from lucaslorentz/caddy-docker-proxy
c158987b0551: Pull complete 
f21761f5d3df: Pull complete 
5e1723edd1f7: Pull complete 
Digest: sha256:366f18780be148cd13fac6493ead9e3c3e333e659025170474ab71d2cd004a37
Status: Downloaded newer image for lucaslorentz/caddy-docker-proxy:2.8-alpine
docker.io/lucaslorentz/caddy-docker-proxy:2.8-alpine

$ docker run lucaslorentz/caddy-docker-proxy:2.8-alpine version
v2.7.5 h1:HoysvZkLcN2xJExEepaFHK92Qgs7xAiCFydN5x5Hs6Q=

**Comment by francislavoie** [comment]
Because that's the Caddy version, not the version of the CDP plugin. That's normal.

**Comment by lucaslorentz** [comment]
Will register this plugin as a caddy module, so you can track the plugin version.
More details in https://github.com/lucaslorentz/caddy-docker-proxy/pull/562
