### ISSUE TITLE
risc-v releases?

### ISSUE THREAD

**Issue by olof-nord** [lucaslorentz/caddy-docker-proxy#571]
I was wondering if releasing builds for the riscv64 architecture is on the roadmap, and if not, if it could be taken into consideration.

RISC-V is an open standard instruction set architecture, which is under rapid development. Distributions including AOSP, Arch Linux, Debian, Gentoo Linux, OpenEuler, etc are also actively doing porting work for this architecture.

upstream caddy project is publishing a riscv build.

**Comment by francislavoie** [comment]
You can build it yourself https://github.com/lucaslorentz/caddy-docker-proxy#custom-images
