### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by shcorya** [lucaslorentz/caddy-docker-proxy#577]
I cannot compile my project because of `github.com/google/pprof v0.0.0-20230207041349-798e818bf904` being present in `go.mod`. I have removed the line in a fork where I also changed the module name and it seems to work fine.

The project that won't compile without the changed `go.mod` is https://github.com/coryaent/lowery.

**Comment by francislavoie** [comment]
Your Dockerfile is kinda weird. Why not do it like this, as documented? https://github.com/lucaslorentz/caddy-docker-proxy#custom-images

**Comment by shcorya** [comment]
Yeah, looking at that, you're right that I've done something odd. I will try with the recommended method and close this issue if it's fixed.
