### ISSUE TITLE
[Question] Is my thought right understanding?

### ISSUE THREAD

**Issue by jeyraof** [lucaslorentz/caddy-docker-proxy#58]
I want to use it as proxy-server for web-browser.
It can satisfy my needs. right?

**Comment by lucaslorentz** [comment]
The main focus of this project is to be a reverse proxy for docker. which is not what you described.

I think caddy forward proxy plugin supports what you described.

You would have to build your own docker image though, the image this repository creates doesn't have caddy forward proxy plugin.
You should consider using https://github.com/abiosoft/caddy-docker to build your own docker image.
