### ISSUE TITLE
Constant errors when not using swarm

### ISSUE THREAD

**Issue by ptman** [lucaslorentz/caddy-docker-proxy#59]
```
dockerd[674]: time="2018-08-16T11:37:52.592586915+02:00" level=error msg="Error getting services: This node is not a swarm manager. Use \"docker swarm init\" or \"docker swarm join\" to connect this node to swarm and try again."
dockerd[674]: time="2018-08-16T11:37:52.593329658+02:00" level=error msg="Handler for GET /v1.35/services returned error: This node is not a swarm manager. Use \"docker swarm init\" or \"docker swarm join\" to connect this node to swarm and try again."
```

Maybe something could be done to limit the requests and therefore error messages? Like only check for swarm once when caddy is starting and then remember it's not available?

**Comment by lucaslorentz** [comment]
Yes, we should do something to limit that.
I think it's possible to check if swarm is enabled via API.
Another option would be to add a flag to disable monitoring swarm services.

**Comment by ptman** [comment]
Excellent, thank you!
