### ISSUE TITLE
Enable localhost:2019/config/

### ISSUE THREAD

**Issue by sowinski** [lucaslorentz/caddy-docker-proxy#611]
Hi,

I currently trying to get the current config over the admin api.

I started to use `curl "http://localhost:2019/config/"` to see the current configuration. But it returns nothing.

When I go into the container to /config/caddy/Caddyfile.autosave I can see that there are my settings.
Also they are working fine.

I currently want to print my config and add something dynamically during runtime.
(I want to block some ips which ddos my server for example 24hours.)

Is this caddy feature turned of in caddy-docker-proxy?

**Comment by francislavoie** [comment]
You shouldn't try to use the admin API when using CDP, because any label changes will clobber any changes you make via the admin API. It's fundamentally incompatible.

What are you trying to do exactly? https://xyproblem.info/

**Comment by sowinski** [comment]
> What are you trying to do exactly? https://xyproblem.info/

1.) I have currently a scammer which I trying to break into my system. He is producing a lot of traffic and I want to block his IP temporarily.  (Without restarting the server if possible). What other option do I have?
2.) Next step would be to implement a rate limiter per IP which do not allow like 100 requests per minute or 10 POST per minute)

**Comment by francislavoie** [comment]
Use `iptables` to block the IP.

I don't understand why this would require the use of the admin API.

**Comment by sowinski** [comment]
Okay thank you!

So I won't touch the admin API anymore.
