### ISSUE TITLE
Caddy 2.8 Final Release

### ISSUE THREAD

**Issue by baer999** [lucaslorentz/caddy-docker-proxy#621]
Hello,

it would be great if you could build upon newest Caddy Final Release:
https://github.com/caddyserver/caddy/releases/tag/v2.8.0

Kind Regards,
Andreas

**Comment by francislavoie** [comment]
You can use it right away by writing your own Dockerfile:

https://github.com/lucaslorentz/caddy-docker-proxy?tab=readme-ov-file#custom-images

**Comment by francislavoie** [comment]
I'll just close this. You don't need to open an issue every time a new release is out @baer999, we get notifications on releases too.
