### ISSUE TITLE
Metrics handle subroute

### ISSUE THREAD

**Issue by devMls** [lucaslorentz/caddy-docker-proxy#674]
Hi

First of all. Great plugin!!

I am installing grafana for see metrics

I have differents domains, but when I see only one handler (subroute), but . Is possible that each domain or subdomain have their own handler?

![image](https://github.com/user-attachments/assets/f67f5f1e-88d7-4420-9dda-399c10f5fece)

**Comment by francislavoie** [comment]
Per-host metrics was added in https://github.com/caddyserver/caddy/pull/6531, coming in the next release (or use v2.9.0-beta.3 available now).

**Comment by plittlefield** [comment]
I'd love to be able to do this, but cannot access the metrics due to the localhost 127.0.0.1 restriction.

How did you solve this?
