### ISSUE TITLE
Does Not Work On Custom Image

### ISSUE THREAD

**Issue by nekromantik** [lucaslorentz/caddy-docker-proxy#675]
Hello
So I run caddy on docker on Unraid and use got a custom build with caddy-docker-proxy/v2 installed.
In the container I can see docker proxy listed when I go list-modules.
I then added VAR called DOCKER_HOST and set it to "/var/run/docker.sock"
However its not picking up any containers and nothing in logs.
Is there anything else you need to do to get it to run as module?

**Comment by francislavoie** [comment]
Show your Dockerfile. Show your docker-compose setup.

**Comment by nekromantik** [comment]
1
services:
  caddy:
    container_name: caddy
    image: ghcr.io/hotio/caddy
    ports:
      - "80:8080"
      - "443:8443"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
      - CUSTOM_BUILD
    volumes:
      - /<host_folder_config>:/config`

Yes followed readme

**Comment by francislavoie** [comment]
You're not using the official Caddy Docker image, nor are you building Caddy Docker Proxy from a Dockerfile as per the README. We don't support `hotio` images.
