### ISSUE TITLE
[Help] Both http and https for same site

### ISSUE THREAD

**Issue by accforgithubtest** [lucaslorentz/caddy-docker-proxy#678]
I am looking for help on how I can get caddy-docker-proxy to reverse proxy both http and https for the same site at the same time, with a single container for the other application.

My current state is
1. Adding caddy.tls paths to self signed certificates makes it reverse proxy via https. Making http requests auto redirects to https.
2. Removing caddy.tls configs makes it http only. Https requests dont work when no tls cert provided.
3. Only https or only http works fine. But not both with a single container configuration.

How can it get to serve http requests without redirecting to https, while also being able to serve https when requested ?

Context - i have a self hosted site with self-signed cert, which i want to be able to view on a amazon fire stick, but the unreasonable greedy corpo amazon removed the ability to add self signed certificates to  android trusted store, leaving no ways to avoid warnings each time, which are not possible to navigate with just the remote. This is also not a bug but as this has been the case for more than a year. Amazon also removed the section for adding self signed certs from their documentation for newer versions of the os. Leading me to loook for a way to provide access only via http just for the fire stick.

**Comment by francislavoie** [comment]
Just make two sites, one with `http://` as a prefix to the domain, and one without.

```
caddy: example.com
caddy.reverse_proxy: {{upstreams}}
caddy: http://example.com
caddy.reverse_proxy: {{upstreams}}
```

Why can't you use a real cert instead of a self-signed cert? If your server isn't publicly accessible, you can still get a cert using the DNS challenge.

**Comment by accforgithubtest** [comment]
Thank you so kmuch for your reply @francislavoie . Will give this a try.

> If your server isn't publicly accessible, you can still get a cert using the DNS challenge.

I am not a developer, but learnt docker for self hosting few software. are there any detailed guides for this using caddy docker proxy ? All guides i have seen needs me to have a domain.

**Comment by francislavoie** [comment]
https://caddyserver.com/docs/automatic-https#dns-challenge
