### ISSUE TITLE
add option to disable plugin through command line parameter

### ISSUE THREAD

**Issue by VanCoding** [lucaslorentz/caddy-docker-proxy#80]
As I've reported here:
https://github.com/mholt/caddy/issues/2326#issuecomment-432648116

my caddy server is currently not able to start up when the docker service is running, because i have a caddy executable which has this plugin compiled into it.

Is there a way to disable the plugin through a paramter?
I think it would be even be better to disable this by default and then require the user to enable it through a parameter, since probably noone expects caddy to interact with docker when a Caddyfile was provided.

Recompiling caddy without this plugin is not a convenient option for me. I'd rather keep using the version of my distro, which contains this plugin. This way, I can update caddy with the package manager.

**Comment by tehbilly** [comment]
I would love to use this plugin, however I have a similar issue with the inability to use it simultaneously with normal `Caddyfile`-based instances. I would like to have a command line option to enable/disable or to enable via a directive.

**Comment by grimpy** [comment]
I too ran into this problem a workaround is to set the DOCKER_HOST environment variable to a not working docker instace.
eg
`DOCKER_HOST=unix:///var/run/notafile caddy`

**Comment by VanCoding** [comment]
@grimpy cool, I'll try that. Thank you!

It'd still be better to have an option to enable it and having it disabled by default, though.

**Comment by francislavoie** [comment]
This should no longer be an issue with the Caddy v2 version of the plugin because it's now implemented as an explicit command, i.e. `caddy docker-proxy`. Closing.
