### ISSUE TITLE
add option to disable telemetry

### ISSUE THREAD

**Issue by sheychen290** [lucaslorentz/caddy-docker-proxy#85]

**Comment by lucaslorentz** [comment]
We don't affect caddy cli flags.
I think you can just follow caddy documentation on how to disable it.
https://caddyserver.com/docs/telemetry

**Comment by lucaslorentz** [comment]
https://caddyserver.com/docs/cli#disabled-metrics

**Comment by thoom** [comment]
The only way to completely disable telemetry is at compile time by setting the flag `enableTelemetry` to false. Would it be possible to generate a docker image with this disabled?

**Comment by lucaslorentz** [comment]
Yes, I will work on it

**Comment by thoom** [comment]
I was thinking about adding a PR for this. What would you expect the resulting Docker images to be named? i.e. `caddy-docker-proxy:alpine-no-telemetry`? Or would you rather move the default to no telemetry and instead `caddy-docker-proxy:alpine` is with telemetry disabled and `caddy-docker-proxy:alpine-telemetry` is what is currently built?

**Comment by thoom** [comment]
Or maybe just disable it for `caddy-docker-proxy` based on this comment: https://github.com/mholt/caddy/issues/2355#issuecomment-440072106?

**Comment by lucaslorentz** [comment]
I think we should go a bit more towards adding a cli option + env variable to disable telemetry instead of doubling the number of tags we have in docker image.

**Comment by lucaslorentz** [comment]
I'm still not sure if it should be enabled or disabled by default.
@mholt Maybe you can provide some feedback about the feature, will it be discontinued?

**Comment by mholt** [comment]
We don't have any plans to discontinue telemetry. We might change its defaults in Caddy 2, but Caddy 2 will have a monitoring platform as well so we will have to see how that changes things!

**Comment by EarthlingDavey** [comment]
I know this issue was closed a while ago, but it's still coming up as a to google result. 

As a workaround for docker, the telemetry url can be effectively blocked with an extra host argument of `--add-host telemetry.caddyserver.com:127.0.0.1` or for docker-compose:

```
extra_hosts:
 - "telemetry.caddyserver.com:127.0.0.1"
```

**Comment by francislavoie** [comment]
Caddy v2 has no telemetry.
