### ISSUE TITLE
caddy-basic-content missing for containers

### ISSUE THREAD

**Issue by Ivanca** [lucaslorentz/caddy-docker-proxy#93]
When using containers (not swarms) caddy-basic-content does nothing, why not make it work the same for containers?

I tried setting the env variable CADDY_DOCKER_CADDYFILE_PATH without success (file is not used)

Any advice?

**Comment by lucaslorentz** [comment]
caddy-basic-content example is using configs, which is a swarm mode feature:
![image](https://user-images.githubusercontent.com/2268284/56849184-a23fad80-68f1-11e9-9fc6-932848fef1a9.png)
So, if swarm is not enabled, caddy-docker-proxy skips configs as source of data.

I double checked the code and didn't see why CADDY_DOCKER_CADDYFILE_PATH would fail. Make sure the caddy file is mounted inside the caddy-docker-proxy container.

Can you please share the commands and tools you're using?

**Comment by lucaslorentz** [comment]
Please, share logs from caddy-docker-proxy container as well.

**Comment by lucaslorentz** [comment]
Just noticed CADDY_DOCKER_CADDYFILE_PATH was not released yet.
So it would only work if you're using an image with **ci** tag.

Soon I will release version 0.3.0 and it will be general available.

**Comment by lucaslorentz** [comment]
Based on https://github.com/lucaslorentz/caddy-docker-proxy/issues/102 I believe it is working.
