### ISSUE TITLE
I used django, can i used caddy-docker-proxy  instead of nginx?

### ISSUE THREAD

**Issue by find456789** [lucaslorentz/caddy-docker-proxy#97]
hi 

i have two sites, build on django(a python web framework)

i used nginx to serve static files and  handles the HTTP request

## now: 

The outside world     <->     nginx    <->   [Gunicorn](https://gunicorn.org/) 

## next plan : 
The outside world     <->     caddy-docker-proxy    <->   [Gunicorn](https://gunicorn.org/) 

---
can i used caddy-docker-proxy  instead of nginx?

---
thank you very much 

sorry , my english is not well

**Comment by lucaslorentz** [comment]
Keep in mind that caddy-docker-proxy is all about discovering docker containers and automatically configuring caddy. Caddy is the real http server.

That said, caddy would be a direct replacement for nginx.

caddy-docker-proxy would be a replacement for traefik or jwilder/nginx-proxy.

So, I recommend first switching to caddy with manual configuration. That way you get familiar with caddy concepts.

And later, if you run django inside docker, maybe adopt caddy-docker-proxy as well.
